### ISSUE TITLE
Stuff to do for release

### ISSUE THREAD

**Issue by Sandertv** [RevivalPMMP/PureEntitiesX#1]
Some things we have to do for the plugin to work properly:
- [x] Fix crash on startup, it's crashing with error `class Magicode\pureentities\PureEntities not found`
- [x] Create better issue/PR labels
- [x] Make a better name for the organization
- [x] Fix all console outputted errors
- [x] Set up gitter or a better IRC
- [x] Enable Poggit for auto compiling and lint checks
- [x] Configuration and Customization
- [x] Final debugging
- [x] Create Poggit release phar
- [x] Upload and Release on Github

**Comment by Magicode1** [comment]
I think the Class might be a mistake in changing my name. I changed all of the 'Milk' paths in it to 'magicode' so I may have missed one

Does it give a location?

**Comment by Sandertv** [comment]
Too bad it doesn't. I hoped changing the capital from the plugin.yml would fix it but it doesn't. It still gives the error with a capital M, so I think there's a capital letter somewhere.

**Comment by Magicode1** [comment]
Ohh, gotcha. I will look

**Comment by Sandertv** [comment]
Maybe we could call the organisation something like RevivalPM, reviving cool plugins that have been abandoned.

**Comment by Magicode1** [comment]
Ooohhh I like that

**Comment by Magicode1** [comment]
Ima change the name right now

**Comment by Sandertv** [comment]
I fixed the error in fact, got another one to go now :P

**Comment by Magicode1** [comment]
Lol, great job! I am making local changes, and pulling your changes down as fast as I can :) 

I renamed the Organization

**Comment by Sandertv** [comment]
Awesome :) There's a hidden milk somewhere around the BaseEntity.

**Comment by Magicode1** [comment]
Gotcha

**Comment by Magicode1** [comment]
I'm looking

**Comment by Sandertv** [comment]
I found some milks! I got to go to school in 3 mins though xD

**Comment by Sandertv** [comment]
For some reason it keeps creating forks when I try to edit though...

**Comment by Magicode1** [comment]
Lol, I am at school RN

**Comment by Magicode1** [comment]
Let me look at it

**Comment by Magicode1** [comment]
I invited you to Collaborate,

**Comment by Sandertv** [comment]
Yep, it works now! I got the milks away :P

**Comment by Sandertv** [comment]
I gotta head to school now, Cya in a couple hours!

**Comment by Magicode1** [comment]
Lol ok, have fun

**Comment by Sandertv** [comment]
I feel like we're quite a good team 😃 We could actually make something happen :)

**Comment by Sandertv** [comment]
I should get better at clicking at the comment button instead of close and comment though LOL.

**Comment by Magicode1** [comment]
I made a Gitter room. It is ready to go. I also added buttons on the readme

**Comment by Sandertv** [comment]
I saw! Thanks a lot!

**Comment by Magicode1** [comment]
About the team thing, I really think we are a good team too! Revive some classics, make our own(maybe) plugins, LEGEND. Maybe.

**Comment by Sandertv** [comment]
I agree! 😄
