### ISSUE TITLE
Entities jump as far as needed to jump over a wall

### ISSUE THREAD

**Issue by Sandertv** [RevivalPMMP/PureEntitiesX#10]
Spawned entities can not jump on 1 block high walls. Slabs and stairs are fine, but full blocks do not work at all.

**Comment by Magicode1** [comment]
That's a problem. The only time I have seen them be able to hop a 1 block was when a pig glitched 20 blocks into the air :)

**Comment by Sandertv** [comment]
Yep. Hitting them allows them to get up blocks too.

**Comment by Magicode1** [comment]
Ok, so we need an auto jump in the WalkingEntity ?

**Comment by Sandertv** [comment]
Yep guess so!

**Comment by tjespe** [comment]
This would really make the plugin a 100 times better!

**Comment by Sandertv** [comment]
Changed title, we gotta fix this issue now :P

**Comment by tjespe** [comment]
@Sandertv @Skull3x Comitted a change 27 minutes ago which seems to have fixed it. However it looks like the entities jumps higher than necessary.

**Comment by Skull3x** [comment]
Entities jump as far as needed to jump over a wall.

A wall at a specific height? Or a wall in general??

**Comment by tjespe** [comment]
The original issue was that entities were unable to "jump on 1 block high walls" so I guess a wall with 1 block height is what we're talking about.

**Comment by Skull3x** [comment]
@tjespe Not necessarily, my commit implements jumps but for walls higher than the entity. It tends to do something known as wall walking, similar to the Vanilla Spider. Due to:

```php
$this->motionY = 0.7;
```

I have not added anything to prevent that yet as of now

**Comment by Sandertv** [comment]
Yep. That's what we got left to do.

**Comment by Skull3x** [comment]
@tjespe @Sandertv I will work on that now or in the future if not implemented sooner :)

**Comment by tjespe** [comment]
As of now, all entities jump right over fences which kind of ruins farming and stuff

**Comment by Skull3x** [comment]
@Sandertv I like the 1st option better

**Comment by Skull3x** [comment]
@Sandertv Unless you plan on removing jump capabilities, I'm fine either way 👍

**Comment by Sandertv** [comment]
Alright, let's go for the first one then :) Let's not forget to make it so spiders DO keep this capability of wall climbing.

**Comment by tjespe** [comment]
I also think the 1st option is best becuase in "real minecraft" the animals will always try to jump over fences and stuff even though they can't.

**Comment by tjespe** [comment]
One thing you should keep in mind (although it's not super important) is that spiders should be able to wall walking and climb even though they're not on the ground

**Comment by Skull3x** [comment]
Yes, I agree. I will attempt to make this as similar to Vanilla as possible

**Comment by tjespe** [comment]
At least the entities don't drown anymore, which is [another issue](https://github.com/RevivalPMMP/PureEntitiesX/issues/13)

**Comment by Sandertv** [comment]
They don't? Do they stay on the surface now?

**Comment by tjespe** [comment]
I'm sorry, they do drown some times. It depends on whether or not there are any solid blocks around them, so when they go in to a small water they survive but when they go out in the sea they wuickly go to the bottom, as they did before.

**Comment by Skull3x** [comment]
@tjespe @Sandertv Yes, I will add swimming functions if they have not been added already right now. And could one or both of you check the gitter chat? :)

**Comment by Sandertv** [comment]
Oh of course! Sorry :P

**Comment by caspervanneck** [comment]
Is this fixt?

**Comment by Sandertv** [comment]
No, I'll leave this up to @Skull3x

**Comment by Sandertv** [comment]
Bump @Skull3x, could you have a try to fix this?

**Comment by Magicode1** [comment]
If he hasn't, we can get it done tomorrow.

**Comment by NycuRO** [comment]
@kniffo80 Please you can fix that? Is very important feature.

**Comment by kniffo80** [comment]
Puh, I'm not that good in maths :smile: but i can give it a try. It's already on my list for the things next to be done.

**Comment by kniffo80** [comment]
This can be closed - as i think this is solved now in latest kniffo80-dev ...

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX
