### ISSUE TITLE
Fireball issue

### ISSUE THREAD

**Issue by TacosYum** [RevivalPMMP/PureEntitiesX#105]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
 Missing parameter in ExplosionPrimeEvent::__construct()

## Reproducing the issue
1. Spawn Ghast 
2. Ghast shoots at player

## Client information
PocketMine-MP Version: 1.0
Plugin Version: 73cc288
PHP version: 7.0.13 (default)

## Optional information
Fireball error :
```
CRITICAL> Could not tick level "world": Argument 3 passed to pocketmine\event\entity\ExplosionPrimeEvent::__construct() must be of the type boolean, none given, called in /root/Tessnew/plugins/PureEntitiesX-1.0.0-bug-fixes/src/revivalpmmp/pureentities/entity/projectile/FireBall.php on line 82
```

**Comment by jasonwynn10** [comment]
According to the commit that was given, you are using the master branch?

**Comment by TacosYum** [comment]
Oops sorry no it was 73cc288 1.0

**Comment by jasonwynn10** [comment]
There shouldn't be any issues. Are you sure that you are using pmmp with API 3.0.0-ALPHA2 ?

**Comment by TacosYum** [comment]
Yes

**Comment by TacosYum** [comment]
Wait no I'm using Apples Genisys Spoon Tesseract

**Comment by TacosYum** [comment]
Could that be a issue?

**Comment by Magicode1** [comment]
Definitely. We don't promise any Spoon compatibility.

**Comment by jasonwynn10** [comment]
@Magicode1 no one ever reads the readme...

**Comment by archie426** [comment]
@jasonwynn10 Yep. You wonder how people who don't actually make accounts on GitHub -_-
