### ISSUE TITLE
WORLD array

### ISSUE THREAD

**Issue by starterdragon** [RevivalPMMP/PureEntitiesX#108]
- [x ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

Make an array of worlds in the config, from which only the mobs will spawn
...

**Comment by jasonwynn10** [comment]
This doesn't follow the issue tracker me is Invalid
Closing
