### ISSUE TITLE
Configurable options for monster spawning?

### ISSUE THREAD

**Issue by Sandertv** [RevivalPMMP/PureEntitiesX#11]
Should we add a config for things such as maximum monsters around player, despawntime (Oh! I got to add a task for that!) and such things? It could be cool to have an element of customization for users.

**Comment by Magicode1** [comment]
Yeah, definitely more customization than the pocketmine.yml .  Then, we can migrate that over if Pocketmine ever implements Mob AI, and make it a plugin where users can control the Pocketmine spawning!

**Comment by Sandertv** [comment]
I guess we'll just save this for the next update! (after the release)

**Comment by Magicode1** [comment]
Agreed.

**Comment by Magicode1** [comment]
Ohh I just got an idea... what about the ability to summon bosses?

**Comment by Sandertv** [comment]
The elder guardian is easily done, but the wither will be a little more work. Let's implement the normal mobs first and see how far we get :smile:

**Comment by Magicode1** [comment]
Alright!

**Comment by Magicode1** [comment]
I'm just gonna close this because it's kinda just sitting here
