### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by GGinChi-Ibook** [RevivalPMMP/PureEntitiesX#118]
[Server thread/CRITICAL]:
 Could not execute task revivalpmmp\pureentities\task\AutoSpawnAnimalTask: Argument 1 passed to revivalpmmp\pureentities\entity\animal\walking\Sheep::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\Chunk given, called in /root/first01/src/pocketmine/entity/Entity.php on line 513
TypeError: "Argument 1 passed to revivalpmmp\pureentities\entity\animal\walking\Sheep::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\Chunk given, called in /root/first01/src/pocketmine/entity/Entity.php on line 513" (EXCEPTION) in "/plugins/PureEntitiesX_Dev/src/revivalpmmp/pureentities/entity/animal/walking/Sheep" at line 49

1. just auto to spawn entity
2. start game 
3. join game
4. stand for a long time
5. debug display

## Client information
PocketMine-MP Version: 1.0 (delete as nescessary)
Plugin Version: 0.1.1 dev
PHP version: 7.0.13

**Comment by archie426** [comment]
Your details are incorrect, please change them

**Comment by GGinChi-Ibook** [comment]
@archie426 when spawn sheep,  "Argument 1 passed to revivalpmmp\pureentities\entity\animal\walking\Sheep::__construct() must be an instance of pocketmine\level\format\FullChunk, instance of pocketmine\level\format\Chunk given, called in C:\Users\15426\Desktop\Gen\src\pocketmine\entity\Entity.php on line 608" (EXCEPTION) in "/plugins/PureEntitiesX_Dev/src/revivalpmmp/pureentities/entity/animal/walking/Sheep" at line 49

**Comment by GGinChi-Ibook** [comment]
@archie426 i update this to 0.1.2 it waring

**Comment by GGinChi-Ibook** [comment]
Warning: Declaration of revivalpmmp\pureentities\entity\BaseEntity::entityBaseTick($tickDiff = 1) should be compatible with pocketmine\entity\Living::entityBaseTick($tickDiff = 1, $EnchantL = 0) in C:\Users\15426\Desktop\Gen\plugins\PureEntitiesX-1.0.0-bug-fixes\src\revivalpmmp\pureentities\entity\BaseEntity.php on line 0

**Comment by jasonwynn10** [comment]
This is an invalid issue because it doesn't follow the template

**Comment by JunkDaCoder** [comment]
can confirm this isssue though

**Comment by kniffo80** [comment]
Which server is used? Pocketmine or any other derivate?
