### ISSUE TITLE
AutoSpawnTask Errors

### ISSUE THREAD

**Issue by jasonwynn10** [RevivalPMMP/PureEntitiesX#119]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Console error is given after the player waits for mobs to spawn at night

## Reproducing the issue
1. player waits for mobs to spawn during the night

## Client information
PocketMine-MP Version: 1.0
Plugin Version:  3e1fc0f
PHP version: 7.0.13

## Optional information
```
Notice: Undefined offset: 0 in C:\Users\Jason\Documents\Minecraft\PocketMine-MP\src\pocketmine\level\format\Chunk.php on line 406
[18:15:47] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Return value of pocketmine\level\format\Chunk::getHeightMap() must be of the type integer, null returned
[18:15:47] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\level\format\Chunk::getHeightMap() must be of the type integer, null returned" (EXCEPTION) in "/src/pocketmine/level/format/Chunk" at line 406
```

**Comment by axs-gentoo** [comment]
It looks like this is triggered by the line:  $y = $level->getHighestBlockAt($x, $z);  in AutoSpawnTask.php's onRun() function.  The line right after this uses x/y/z to correct the position using getFirstAirAbovePosition(), with a comment that says getHighestBlockAt() doesn't work.  

I've tested using $y = $player->y instead, and it eliminates the error.  I don't know if this has resulted in mobs spawning in the ground or not; that is, I haven't traced whether or not getFirstAirAbovePosition() can handle the case where $y is a few blocks below ground level.

**Comment by jasonwynn10** [comment]
the reason this is an error is because it is trying to get the block one coord above the top of the world. it should start at 0 instead

**Comment by axs-gentoo** [comment]
Should the code just set $y=0 every time then?

**Comment by jasonwynn10** [comment]
I need to look at it more to decide. I have to take cave generation into account

**Comment by kniffo80** [comment]
I will comment this here tomorrow. Just one thing: setting always y=0 will fail in 90% of all spawns! Also setting y to player's y coordinate will fail when spawning in non-flat maps! Remember - y is the HEIGHT!

**Comment by jasonwynn10** [comment]
yes, so if we are trying to find the nearest air block above the specified coords, then why are we starting at the top of the world?

**Comment by kniffo80** [comment]
Okay - some more comments from my side.

1. y Axis is the height Axis - which means when setting always y=0 will fail in 99% of all time. Water level is 60 i think (or 62?) - so setting y=0 each time doesn't work.
2. setting y-coordinate to player's y-coordinate will fail in most cases when there are some "hills" around e.g.
3. yes, highest block doesn't make that sense - i'll implement a new method

So - summarizing - I'll adjust the y-coordinate finding not using getHighestBlock but starting with the player's y coordinate checking up and down for AIR blocks and then spawning the entity to the nearest non-AIR block.

@jasonwynn10 i think i should wait until the merge to master is done?!

**Comment by kniffo80** [comment]
I've pushed a bugfix for this on https://github.com/RevivalPMMP/PureEntitiesX/pull/121

Please check and merge if possible.

**Comment by kniffo80** [comment]
Anybody checked with latest 1.0.0-bug-fixes that auto spawn works correctly now?

**Comment by jasonwynn10** [comment]
I'll be testing later today

**Comment by kniffo80** [comment]
So I think we can close this issue? I've tested it with a new map / existing map with latest master. I don't get this error anymore (because the spawning mechanism now doesn't use getHighestBlock anymore).

@jasonwynn10 what do you think?

**Comment by jasonwynn10** [comment]
seems good to me

**Comment by axs-gentoo** [comment]
This particular error may have been addressed but my tests of the current code throw a ton (same one just repeated a lot) of different exception, do we open a new issue or try to fix the commits on this one?  I don't have access to my logs right now but I can post to this issue or a new one once I do.

**Comment by kniffo80** [comment]
@axs-gentoo Without a Logfile (or log output) it would be hard to address the issues :smile: 

So when this is resolved - and you get some other exceptions - open a new issue. We can investigate on that then. Thanks for testing and reporting back!
