### ISSUE TITLE
Missing Entities

### ISSUE THREAD

**Issue by Sandertv** [RevivalPMMP/PureEntitiesX#12]
I thought I'd make an issue to address all missing monsters and animals we still have to and can implement. Here's a list:
- [x] Guardian
- [x] Elder Guardian
- [x] Horse (and relatives)
- [x] Witch
- [x] Squid
- [x] Husk
- [x] Stray

If you think I missed any, please give an comment :)

**Comment by Magicode1** [comment]
Agreed. We should get these ASAP

**Comment by Sandertv** [comment]
I'll go for a new SwimmingEntity class. That'll make squids and guardians easier!

**Comment by Magicode1** [comment]
Yes, and make sure to specify that a) they drown in air and b) that they only spawn in water, and not as often :)

**Comment by Sandertv** [comment]
Yep. And for the guardians... They like jump when they're on land if I'm correct?

**Comment by Magicode1** [comment]
Yeah I think so. But do they actually spawn outside of temples?

**Comment by Sandertv** [comment]
They should spawn around the temples... No natural spawning for them until PocketMine implements structure generation 😆

**Comment by Magicode1** [comment]
Yeah.

**Comment by Sandertv** [comment]
Ticked husks and strays :)

**Comment by jasonwynn10** [comment]
all are added, they need implemented on the NewMobs branch
