### ISSUE TITLE
Genesis Error

### ISSUE THREAD

**Issue by TheClimbing** [RevivalPMMP/PureEntitiesX#126]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
On load this error comes up

## Reproducing the issue
Load any server which is 1.0.0.16 using the 1.0 branch

## Client information
PocketMine-MP Version: 1.0
Plugin Version:   PureEntitiesX v0.1.2_dev
PHP version: 7.0.14

## Optional information
`Warning: Declaration of revivalpmmp\pureentities\entity\BaseEntity::entityBaseTick($tickDiff = 1) should be compatible with pocketmine\entity\Living::entityBaseTick($tickDiff = 1, $EnchantL = 0) in phar://C:/Users/TheClimbing/Desktop/Genisys_Unsuportted/plugins/phar_PureEntitiesX-1.0.0-bug-fixes_pPnfc6Ns1j1jX7e.phar/src/revivalpmmp/pureentities/entity/BaseEntity.php on line 0`

**Comment by kniffo80** [comment]
I encountered this using e.g. Genisys - but not with original PocketMine-MP! Which server are you running?

**Comment by TheClimbing** [comment]
Actually yes that's Genisys, I should have said

**Comment by kniffo80** [comment]
So this plugin is mainly for PocketMine-MP. Please use this server software with this plugin. Anyway - when the merge from 1.0.0-bug-fixes is done into master, I can update the method in the BaseEntity so that it can be used also with Genisys and other forks. Meanwhile you should use PocketMine-MP :smile:

**Comment by archie426** [comment]
Please do not always expect support for 3rd party builds, however

**Comment by kniffo80** [comment]
@TheClimbing please check with latest master if this still occurs. I've checked the latest master branch on latest Genisys master - everything fine for me now.

**Comment by kniffo80** [comment]
@TheClimbing also tested the plugin together with latest master of Elywing. Working quite fine - the exceptions are gone (because the BaseEntity and some other have been updated to support the new parameter).
