### ISSUE TITLE
Entities Sink In Water

### ISSUE THREAD

**Issue by Magicode1** [RevivalPMMP/PureEntitiesX#13]
Entities don't swim. They sink to the bottom and die.

**Comment by Sandertv** [comment]
You'd almost feel for those poor zombies 😜

**Comment by kniffo80** [comment]
Should be fixed with latest PR (https://github.com/RevivalPMMP/PureEntitiesX/pull/141). After this got merged, maybe this can be closed - as walking entities then can "walk" through water ...

**Comment by kniffo80** [comment]
Not sinking anymore.
