### ISSUE TITLE
REQUEST - config to list worlds in which to enable the plugin

### ISSUE THREAD

**Issue by Starflux** [RevivalPMMP/PureEntitiesX#134]
- [x ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
...REQUEST - config to list worlds in which to enable the plugin

## Reproducing the issue
1. ...N/A

## Client information
PocketMine-MP Version: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
Plugin Version: PureEntitiesX v0.1.2_dev
PHP version: 7.0.15

## Optional information
...First of all great plugin and thankyou for your development.

I am running a server at home for my kids and i have multiple worlds.

some of these worlds i do not wish to load PureEntitiesX, i am currently using PEXP to disable them within a given radius but i would prefer in this case not to load them at all in the world if possible.

what do you think?

Kind Regards
Star

**Comment by Sandertv** [comment]
Take a look at the latest commit at PEXProtection. It adds a command (/pexp disableworld <name>) which should hopefully work for you. Good to hear you're having a good time using the plugin!

**Comment by Starflux** [comment]
thankyou that is exactly what i was after.

been through about 60 plugins over the last week and i am obviously missing the basics of reading properly.

**Comment by Starflux** [comment]
I just tested and other than repackaging as API 3.0.0-ALPHA3 it works perfectly.

thankyou soo much for the quick response.

**Comment by Sandertv** [comment]
Alright, good to hear!

**Comment by Starflux** [comment]
apologies it seems i did not test it thoroughly, i was still had radius configurations within my config.yml.

i have since done a fresh install and disabled my worlds although on reload the pure entities have spawned.

it seems it was my radius configs that were working earlier.

the console gives the following: 

Notice: Undefined index: radius in phar:///opt/PocketMine-MP-master/plugins/phar                                               _PEXProtection_xn6vPTzK82NrDQ0.phar/src/RevivalPMMP/PEXProtection/Main.php on li                                               ne 69

Notice: Undefined index: x in phar:///opt/PocketMine-MP-master/plugins/phar_PEXP                                               rotection_xn6vPTzK82NrDQ0.phar/src/RevivalPMMP/PEXProtection/Main.php on line 63

Notice: Undefined index: y in phar:///opt/PocketMine-MP-master/plugins/phar_PEXP                                               rotection_xn6vPTzK82NrDQ0.phar/src/RevivalPMMP/PEXProtection/Main.php on line 64

Notice: Undefined index: z in phar:///opt/PocketMine-MP-master/plugins/phar_PEXP                                               rotection_xn6vPTzK82NrDQ0.phar/src/RevivalPMMP/PEXProtection/Main.php on line 65

Notice: Undefined index: level in phar:///opt/PocketMine-MP-master/plugins/phar_                                               PEXProtection_xn6vPTzK82NrDQ0.phar/src/RevivalPMMP/PEXProtection/Main.php on lin                                               e 66

Kind Regards 
Star

**Comment by Sandertv** [comment]
I've made a new commit that should hopefully fix your issue.

**Comment by Starflux** [comment]
Works a treat now thank you again for your time.

**Comment by Sandertv** [comment]
Alright, great! Feel free to tell me if you encounter anymore issues!

**Comment by joshuagilmet** [comment]
having problem with no animals after loading pure. only creeps and zombies and stuff
