### ISSUE TITLE
Preparations for the new entity concept

### ISSUE THREAD

**Issue by jasonwynn10** [RevivalPMMP/PureEntitiesX#135]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
There is a new concept that dktapps is working on that will change how entities work.

## Reproducing the issue
1. N/A

## Client information
PocketMine-MP Version: [c578ca0](https://github.com/pmmp/PocketMine-MP/commit/c578ca01223e7bb242b0d7c0289f0e654e8933b6)
Plugin Version: N/A
PHP version: 7.0.15

## Optional information
https://github.com/pmmp/PocketMine-MP/commits/api3/new-entity-concept

**Comment by Magicode1** [comment]
Once this comes into effect, we will re-open this issue 😃
