### ISSUE TITLE
Animals spawn in nether and Bug with Blaze

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#142]
@kniffo80 

Sorry, but not need steps here or reproduce.

[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:46] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:47] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()
[Tesseract] [15:20:47] CRITICAL> Could not tick level "nether": Call to undefined method revivalpmmp\pureentities\entity\monster\flying\Blaze::isCheckTargetAllowedBySkip()

**Comment by NycuRO** [comment]
And other animals spawn in nether, wtf?: @kniffo80 

![image](https://cloud.githubusercontent.com/assets/13573011/23167026/ab4467cc-f84b-11e6-8f55-b4088669d255.png)

**Comment by kniffo80** [comment]
You know the issue template? And be polite please ... WTF is NOT polite. I NEVER played in nether. And please choose a correct title ... ERROR is not a title :rage:

I'll change title and re-check the spawning later. First, the actual PR needs to get merged to master. Then, I'll reformat the complete code and THEN i'll go for this ...

**Comment by NycuRO** [comment]
Man, please fix error, spam console :/ @kniffo80 (first)

**Comment by kniffo80** [comment]
I'll fix the first issue and push another commit to the actual PR. Be patient!

**Comment by kniffo80** [comment]
This should fix the issue (tested right now with spawning simply a blaze): https://github.com/RevivalPMMP/PureEntitiesX/pull/141/commits/c3a43bfc1bb4657a65b89a79ec6f19e6664395ed

**Comment by NycuRO** [comment]
Ok @kniffo80 . I test in 10mins.

**Comment by caspervanneck** [comment]
Hi

**Comment by kniffo80** [comment]
Latest commit in https://github.com/RevivalPMMP/PureEntitiesX/pull/141 has a commit that should now spawn correct entities in nether (as I assume that Biome::HELL is nether). So just try it out :smile:

**Comment by NycuRO** [comment]
Yes :)
