### ISSUE TITLE
TODO for height, weight and eyeheight? Baby's 

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#143]
@kniffo80 For height, weight and eyeheight need add one function.

Like in java:
"
    @Override
    public float getEyeHeight() {
        return 0.9f;
    }
"

This is very necesary. This method is now incorrect.

If exist baby's add to function like that:

"
    @Override
    public float getHeight() {
        if (this.isBaby() {
            return 0.9f;
        } else {
            return 0.4f;
         }
     }
"

NOTICE! Values is in float! Please add numers float. Now, it's incorrect all.

**Comment by kniffo80** [comment]
This will be a bigger code change. As height etc. pp are defined in variables only - there's no method that can be used now. So it will be a bigger change - at least in the plugin. And again: you show me code from somewhere and it's again JAVA ...

And again - I know this plugin is far from being perfect.

But answer one question: why do we need that at the moment? You say: "This is very necessary" ...

**Comment by kniffo80** [comment]
Take a look at the BreedingExtension class, function setAge: there the height and width of the entity is already set when baby and reset when adult:

```php
$this->entity->height = $this->adultHeight / 2; // because we scale 0.5
$this->entity->width = $this->adultWidth / 2; // because we scale 0.5
```
And as far as i can see the eye height is not used anywhere at the moment. Of course, when eye height is used we need to implement also eye height.

**Comment by NycuRO** [comment]
@kniffo80 It's more useful this method. Now .... it's broken and get errors... ( not in code, in movement and riding ).

**Comment by kniffo80** [comment]
You can ride? Interesting ... :smile:

Can you provide more information? Because "Now ... its broken and get errors" is not sufficient.

**Comment by NycuRO** [comment]
Watch on code MCPC ( it's same MCPE. I know that ) and watch why is implemented that's.

**Comment by kniffo80** [comment]
So when it's the same - we could use the complete code to host a MCPE server? When it's the same - why not using directly that code? Why are we doing this here?

**Comment by NycuRO** [comment]
@kniffo80 Ok, your oppinion.
