### ISSUE TITLE
Error spamming in console

### ISSUE THREAD

**Issue by kabluinc** [RevivalPMMP/PureEntitiesX#147]
This error keeps spamming in console randomly

`2017-02-23 [17:59:08] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\InteractionTask: Start block missed in BlockIterator
2017-02-23 [17:59:08] [Server thread/CRITICAL]: InvalidStateException: "Start block missed in BlockIterator" (EXCEPTION) in "/src/pocketmine/utils/BlockIterator" at line 169`

Also some entities like Cat, Pig, Sheep, Horse cant be damaged and some don't move like Cats, pigs and sheeps
Using PMMP

**Comment by kabluinc** [comment]
That error above is fixed in your latest PR. But a new issue has arised. a new config is not created if old one is deleted. even after a server restart.


This error shows

`Warning: yaml_parse(): end of stream reached without finding document 0 in C:\Desktop\New folder (100001)\src\pocketmine\utils\Config.php on line 143`

**Comment by kniffo80** [comment]
Please make a new issue for that. Will close this one. Thanks.
