### ISSUE TITLE
Error with CombatLogger

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#152]
[Tesseract] [20:52:51] CRITICAL> "Could not pass event 'pocketmine\event\entity\EntityDamageByEntityEvent' to 'CombatLogger v1.0.0': Argument 1 passed to Lambo\CombatLogger\Main::setTime() must be an instance of pocketmine\Player, instance of revivalpmmp\pureentities\entity\monster\walking\CaveSpider given, called in phar:///root/fac/plugins/phar_CombatLogger_zZTK1PZxhdzCa5Z.phar/src/Lambo/CombatLogger/Main.php on line 45 on Lambo\CombatLogger\Main
[Tesseract] [20:52:51] CRITICAL> TypeError: "Argument 1 passed to Lambo\CombatLogger\Main::setTime() must be an instance of pocketmine\Player, instance of revivalpmmp\pureentities\entity\monster\walking\CaveSpider given, called in phar:///root/fac/plugins/phar_CombatLogger_zZTK1PZxhdzCa5Z.phar/src/Lambo/CombatLogger/Main.php on line 45" (EXCEPTION) in "/phar_CombatLogger_zZTK1PZxhdzCa5Z.phar/src/Lambo/CombatLogger/Main" at line 51

@kniffo80

**Comment by kniffo80** [comment]
???

**Comment by NycuRO** [comment]
[Tesseract] [20:52:51] CRITICAL> TypeError: "Argument 1 passed to Lambo\CombatLogger\Main::setTime() must be an instance of pocketmine\Player, instance of revivalpmmp\pureentities\entity\monster\walking\CaveSpider given, called in phar:///root/fac/plugins/phar_CombatLogger_zZTK1PZxhdzCa5Z.phar/src/Lambo/CombatLogger/Main.php on line 45" (EXCEPTION) in "/phar_CombatLogger_zZTK1PZxhdzCa5Z.phar/src/Lambo/CombatLogger/Main" at line 51

**Comment by kniffo80** [comment]
What has this to do with PureEntities?

**Comment by Sandertv** [comment]
It's the fault of the combat logger for not checking if the damager is instance of a Player. There's no way for us to fix that.
