### ISSUE TITLE
Error Spawning

### ISSUE THREAD

**Issue by HAN-105** [RevivalPMMP/PureEntitiesX#154]
## Issue description
So actually, i was built .phar files from the latest source from this repository. it's working with my Genisys (with API: 3.0.0-ALPHA4). but I got error message, and there are no mobs/animals spawning in any biomes. So when i was checking about the "Entity.php" in src folder. it isn't there.. just missing.

## Client information
Genisys (MCPE) Target Version: 1.0.3.0
API: 3.0.0-ALPHA4
Plugin Version:  0.1.2_dev
PHP version: 7.0.15
DevTools (PocketMine-DevTools) Version: v1.11.2 (Latest Source, Built to .phar by myself)

## Optional information
- pureentities.log = `[31m2.3.2017 6:14:05 [WARN]  AutoSpawnTask: cannot find a suitable spawn coordinate [search.x:119] [search.y:70] [search.z:110][0m`
- Link Server Logs : http://pastebin.com/rfWFD6kr

**Comment by kniffo80** [comment]
So the error may be normal. About the Entity: it's not provided by PureEntitiesX - it's provided by the server. So you may have to check your server sources ...

**Comment by HAN-105** [comment]
oh thanks, the issue has been fixed.
