### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ehsanpey** [RevivalPMMP/PureEntitiesX#155]
The plugin crashes my server...

heres the CrashDump:
[Mon_Mar_6-16.42.54-CET_2017.txt](https://github.com/RevivalPMMP/PureEntitiesX/files/822216/Mon_Mar_6-16.42.54-CET_2017.txt)

**Comment by kniffo80** [comment]
KK - you're using newest PMMP it seems. Tomorrow I'll correct this. Thanks for reporting!

**Comment by kniffo80** [comment]
Hmmm ... can you tell me which version of PMMP you're using? Which branch?

**Comment by ehsanpey** [comment]
BlueLight

**Comment by kniffo80** [comment]
Please try https://github.com/RevivalPMMP/PureEntitiesX/tree/kniffo80-dev and report back if it works properly.

**Comment by ehsanpey** [comment]
It works great, thanks for fixing it  👍

**Comment by kniffo80** [comment]
Thanks for reporting back!
