### ISSUE TITLE
Plugin starts to highly lag the server

### ISSUE THREAD

**Issue by kabluinc** [RevivalPMMP/PureEntitiesX#156]
## Issue description
I tried using this plugin on a server for a week and within an hour of the server running, the server starts to lag allot and delay. For example the HUD of the server can be seen disappearing and appearing for 2 seconds and chat start to lag. I am using PeXProtection to make sure mobs only spawn in 1 world but still I am having issues with server performance. The server starts to get to constant 10-15 TPS. The server itself runs on a good host with 1Gbps network so there's no possibility of slow hardware. 

After removing this plugin, the server has no issues and even after 4 hours of running there is no lag and TPS is constant 20.

## Client information
PocketMine-MP Version: 1.0
Plugin Version: Latest from repo
PHP version: 7.0.13

**Comment by kniffo80** [comment]
Which server are you running? Using pure PMMP or any other fork/spoon?

At least - AI is very hard to implement without running into performance issues. That's one of the reasons all server out there have no AI at the moment.

I'm thinking about creating a completely new plugin with the knowledge i have today. But that's a lot of work to be done. Additionally it's very hard to find out the performance issue in this case.

First try to adjust the spawn values in the config.yml of the plugin. Maybe less mobs in the config? It's hard to say whats wrong - when you say it starts to lag after one hour or so it may be a problem of creating too many instances of something.

**Comment by kabluinc** [comment]
Thanks for the quick reply. I'm using the original PMMP and the plugin version im using is kniffo80-dev.

Iv set the spawn values of each mob to low numbers, like 1-3 max however still there is no apparent difference.

**Comment by kniffo80** [comment]
Have you tried - just for testing - create a new world (backup old one) and check again? I noticed it sometimes on old worlds ...

**Comment by kabluinc** [comment]
The server iv tried it on have a couple of worlds some of them old (mcr worlds) and some of them new (pmAnvil worlds). The only world i have mobs enabled on is in one of the new worlds. I use PeXprotection to disable mobs in the other worlds.

**Comment by kniffo80** [comment]
Okay - this needs a real deeper look. The more features we implement the harder it gets to find the performance killer. But I'll try. Thanks for reporting!

**Comment by Magicode1** [comment]
Thanks also for using the correct issue format, it helps a ton with figuring it out and solving the problem!

**Comment by kniffo80** [comment]
I had this issue now too. Just yesterday evening. I joined my public server and it started to badly lag. So I decided to restart the server. Shutdown took a long time and the server stopped gracefully shutting down. Then I deactivated PureEntities plugin and started the server again. After login I noticed the same lag as before with the plugin enabled. NOW it gets interesting - I logged in today in the morning again. Lag was gone :open_mouth:

Now here's my assumption:
When an entity gets killed - regardless of WHAT killed it - it drops ItemEntities to the ground. Now there's a depawn thread - which kills entities by specific rules. Each time an entity got killed - it drops items to the ground. This pollutes the world with "living" ItemEntities and the server has to tick each item entity. After a specific amount of time, the item entities are removed by the server (when a specific age is reached). Then the lag is gone. But this is only an assumption of me.

What I will implement now: entities only drop stuff when killed by EntityDamageByEntityEvent (lastDamageCause). Maybe this helps. So I'm afraid that this isn't really a problem of the plugin - the plugin only produces a lot of items on the ground. MAYBE that's the problem.

**Comment by jasonwynn10** [comment]
I have an idea on how to do the item dropping...

**Comment by kniffo80** [comment]
I already implemented something. I brought the changed plugin to my server this morning and will see if it lags today in the evening too. What I did: just drop stuff when the last damage cause is done by player.

Or you have another idea?

But keep in mind: its just an assumption from my side that the item entities are responsible for the server lag.

**Comment by kniffo80** [comment]
@kabluinc I've updated the kniffo80-dev branch with some smaller changes. I introduced the possibility to disable some characteristics of the plugin. Maybe, you can update the plugin and in the configuration (config.yml) set the following properties to false:

tasks.async
tasks.looking

And please report back if the problem still persists.

**Comment by kabluinc** [comment]
Okay many thanks. I will check and report back

**Comment by kniffo80** [comment]
You may also try out experimenting with the configuration. My server ran fine since yesterday. Smooth, really. Today in the evening, it started to lag. I think when I log in back tomorrow, the lag is gone again. Really strange thing ...

**Comment by kniffo80** [comment]
As I wrote: today in the morning everything was fine again. No Lag, all tasks activated. Strange issue. It seems that something pollutes the server's queues or something else which is cleaned up each x seconds/minutes/hours. Does anyone know if there's such an algorithm in PMMP? As I read - the following issue has been opened:

https://github.com/pmmp/PocketMine-MP/issues/466

Next thing I can try out: work without all the NBT tags and take a look if it's better then. Currently I've no idea what causes the lags, as I deactivated ALL stuff (like threads, logging etc. pp) while the server was idling. But it doesn't matter if there are entities living or stuff on the ground. There's NOTHING at the server, plugin executes no tasks but still after some time it gets laggy :expressionless:

**Comment by Magicode1** [comment]
This is so mysterious.....

**Comment by kniffo80** [comment]
The actual kniffo80-dev branch is updated. I did some code cleanup and added possibility to enable or disable NBT storage for the plugin. On my server I disabled NBT storage. Let's see how it works. If anyone else wants to try out and help finding performance issues: use the latest branch and experiment a little bit.

@kabluinc maybe you can update the plugin and try it out too. Any help is appreciated!

**Comment by jasonwynn10** [comment]
moved to #163
