### ISSUE TITLE
Make wolfs tamable

### ISSUE THREAD

**Issue by caspervanneck** [RevivalPMMP/PureEntitiesX#16]
can you make the wolf temable

**Comment by Sandertv** [comment]
We'll work on that soon. Right now we're prioritizing the generator and the jumping of the entities. 😄

**Comment by caspervanneck** [comment]
good 👍

**Comment by kniffo80** [comment]
Working on this currently - just FYI. I can tame wolves now and they follow the player, also when logging in back again and after server shutdown. But it needs a lot of work. Stay tuned ;-)

**Comment by kniffo80** [comment]
A little follow-up on this (sorry for delay):

https://github.com/kniffo80/PureEntitiesX/tree/kniffo80

Still under development. Will merge later when tested and bugfixed enough.

**Comment by kniffo80** [comment]
Still working on that. Found a lot of performance issues. Need to fix them. 

targetOption e.g. is used excessive - mostly to find out about the Interactive tag. I found a better and a lot safer way for getting to know, if a button text is shown or not.

So - a little tired now. But the next pull request will be a really big one :/

**Comment by archie426** [comment]
This is moved to bug list
