### ISSUE TITLE
Mob Armor And Enchants

### ISSUE THREAD

**Issue by jasonwynn10** [RevivalPMMP/PureEntitiesX#161]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Armour gives 0 damage reduction

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 1.0
Plugin Version: N/A
PHP version: 7.0.13

## Optional information
https://forums.pmmp.io/threads/working-armor-and-enchants-compatiable-with-pureentities.1506/#post-16781

**Comment by kniffo80** [comment]
No reduction? It should be reduced by a specific percent. I will check. Enchantment isnt implemented yet.

**Comment by jasonwynn10** [comment]
I think they mean that when mobs attack, the player's armour isn't accounted for?

**Comment by ALLINSEO** [comment]
@kniffo80 
yes you are correct when monsters attack defense (armor) is not accounted for. I have only tested this with zombies which hit you for 1 heart both time with wearing unenchanted armor and without I get hit for 1 heart

"Damage is split between the health and armor bars. Each full armor point takes 8% of damage, to a maximum of 80%, rounded up." <<- minecraft wiki
does yours function the same way?

**Comment by jasonwynn10** [comment]
The damages should also change depending on the server difficulty settings

**Comment by ALLINSEO** [comment]
I used to be able to use Mob_Spawners in a disable world, has this been changed?

right now they dont spawn anything if world is disabled

**Comment by kniffo80** [comment]
Alright - just for your information: mob equipment is only implemented for Zombies for now.
@ALLINSEO yes - i was taking the wiki as a template how to implement that. Not all is implemented at the moment - this takes some more reviews and changes :smile: 

I will take care of this as soon as the performance problem is solved.

**Comment by ALLINSEO** [comment]
@kniffo80 
by mob armor I assume that armor only works for the Monsters in the AI, thats what I got when I read the files anyway?

my request/report was about the player not getting damage reduction when a monster attack them. 
example; 
Zombie attacks a player > Base attack = 2 hit point
Player is wearing diamond armor(reduce by 80%) > $BaseAttack x .20 = .4 hit point loss 
or 1/4th a heart might have to be rounded to half a heart since from what I can tell the system only tracks half hearts but still same general idea.

Might be alot of work but would be great if it calculated that in though, if the damage is less then 1 hit point wait until it adds up to 1 hit point and take a Half Heart.

**Comment by kniffo80** [comment]
Okay - now i got it :smile: sorry for being a little short-brained today :expressionless:

**Comment by ALLINSEO** [comment]
no problem, the plugin you guys are developing is still awesome would just be much better with player armor. im trying to make a mob farm and 2-3 zombies constantly hitting you for 2 hit points each drains hp rather quickly.

**Comment by kniffo80** [comment]
I will keep an eye on this as soon as the other, more important issues are solved.

**Comment by kniffo80** [comment]
Added a new branch where armor points are counted in:
https://github.com/RevivalPMMP/PureEntitiesX/tree/damage-reduction

Enchantment still missing - not finished yet. But maybe @ALLINSEO can check again - at least for getting reduced damage while wearing armor.

Just FYI:
1 Armor Point = 4% reduction. And it's not depending on difficulty as far as i read the wiki.
