### ISSUE TITLE
Contact RevivalPMMP Team

### ISSUE THREAD

**Issue by BackEndNoob** [RevivalPMMP/PureEntitiesX#162]
@AppleDevelops @kniffo80 @eDroiid @jasonwynn10  @Magicode1 @archie426 @HimbeersaftLP  
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

I made a post on the forums [forum post](http://revivalpmmpforums.gq/threads/potions.6/) 
I am not sure if the Revival Forums are used still so I thought this was the easiest way to get in touch with the team

**Comment by archie426** [comment]
Yeah please still use the forums
