### ISSUE TITLE
arguments passed

### ISSUE THREAD

**Issue by DonkihotD** [RevivalPMMP/PureEntitiesX#165]
Argument 2 passed in 
![image](https://cloud.githubusercontent.com/assets/17106272/24586678/cfcd7b90-17bf-11e7-865d-f2eccb7b98db.png)

**Comment by archie426** [comment]
What server software are you using?

**Comment by jasonwynn10** [comment]
@DonkihotD 
1. Use the kniffo80 branch
2. you are using Tesseract correct?

**Comment by kniffo80** [comment]
Use latest kniffo80-dev.
