### ISSUE TITLE
Error in console.

### ISSUE THREAD

**Issue by kabluinc** [RevivalPMMP/PureEntitiesX#167]
This error keeps spamming console:

`2017-04-15 [20:04:07] [Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Call to a member function getBlockLightAt() on null
2017-04-15 [20:04:07] [Server thread/CRITICAL]: Error: "Call to a member function getBlockLightAt() on null" (EXCEPTION) in "/PureEntitiesX-kniffo80-dev/src/revivalpmmp/pureentities/task/spawners/BaseSpawner" at line 215`

Normally keeping server running

## Client information
PocketMine-MP Version: pmmp API3/Network 1.62dev for mcpe1.0.6
Plugin Version: 5b3e21bc4ad4a888542dc583f2689fd02749e3a6 kniffo80-dev
PHP version: 7.0.13

**Comment by kniffo80** [comment]
Ah you activated block light. Never used the function before. Will check soon. So long just deactivate block and skylight check in config.yml

**Comment by kniffo80** [comment]
Fixed with https://github.com/RevivalPMMP/PureEntitiesX/commit/9a36689b59d91aad72891885ff3532cc5ff37d2f
