### ISSUE TITLE
Warning messages 

### ISSUE THREAD

**Issue by amon28** [RevivalPMMP/PureEntitiesX#168]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
I just downloaded the plug in today I reloaded my server after putting the plug in then I received an error

 CRITICAL> Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /storage/emulated/0/Pocketmine/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/PureEntities.php on line 264
 CRITICAL> TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, instance of pocketmine\level\format\Chunk given, called in /storage/emulated/0/Pocketmine/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/PureEntities.php on line 264" (EXCEPTION) in "/src/pocketmine/entity/Entity" at line 632

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 1.0.6 (delete as nescessary)
Plugin Version: new (insert commit label here)
PHP version: 7.0.13 (default)

## Optional information
...

**Comment by jasonwynn10** [comment]
Use the latest kniddo80-dev branch
