### ISSUE TITLE
range where no monster can spawn

### ISSUE THREAD

**Issue by caspervanneck** [RevivalPMMP/PureEntitiesX#17]
plz add thad mij spawn is full mobs 

or add that dont spawn with licht

**Comment by Magicode1** [comment]
They shouldn't spawn when it is light out. Are you using the latest version? 

We will add spawn protection ASAP

**Comment by caspervanneck** [comment]
yes i us latest version

**Comment by caspervanneck** [comment]
@Magicode1

**Comment by Magicode1** [comment]
Ok. We will work on it. Expect it to be fixed soon :)

**Comment by Sandertv** [comment]
It's currently a bug they spawn in light. I think getLightLevel() doesn't work properly in PM yet. I'll add a check if it's night in a sec.

**Comment by caspervanneck** [comment]
oja my software is from pmmp zo must i use genisys

**Comment by Magicode1** [comment]
Nope! This is a plugin made for PMMP

**Comment by Magicode1** [comment]
Thanks for letting us know about the bug, we will fix it ASAP

**Comment by Sandertv** [comment]
Nah it's PMMP focused. I think it doesn't work with third party softwares either.

**Comment by Sandertv** [comment]
Try now @caspervanneck, they should now only spawn during the night. (From sunset till sunrise to be exact)

**Comment by caspervanneck** [comment]
i cant test i need to sleep @Magicode1 @Sandertv

**Comment by Sandertv** [comment]
Just tested and still doesn't seem to work... Hmmm.

**Comment by Sandertv** [comment]
I'm sorry to say I can't do anything more than make them only spawn at day for now.

**Comment by Sandertv** [comment]
All because PocketMine doesn't have proper light implemented.

**Comment by Sandertv** [comment]
You could possibly add a huge glass layer above your spawn, as monsters currently spawn on the highest block possible in a world.

**Comment by caspervanneck** [comment]
@Sandertv  is that working?

**Comment by Sandertv** [comment]
Yep, it is.

**Comment by Sandertv** [comment]
I've added a protection plugin in the README. You can properly protect it from monsters to spawn using that plugin.
