### ISSUE TITLE
No Mob Spawning?

### ISSUE THREAD

**Issue by EtchReborn** [RevivalPMMP/PureEntitiesX#173]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
When i try to spawn any mob egg nothing happends and when i look at my console i get warns..etc look down further for screenshots of console

## Reproducing the issue
1. I dont know
2. I really dont know

## Client information
Clearsky Version: 1.0.7
Plugin Version: (0.2.2Dev)
PHP version: No PHP (Only Clearsky phar)

## Optional information
I am not getting any CrashDumps or any other file i am only getting text in console
![screenshot_2017-05-20-10-16-16](https://cloud.githubusercontent.com/assets/28599276/26274251/e44eef8a-3d45-11e7-83b5-04b90e8969a4.png)
![screenshot_2017-05-20-10-15-58](https://cloud.githubusercontent.com/assets/28599276/26274254/f6b552d6-3d45-11e7-92d8-1e8cb909ea5e.png)

**Comment by jasonwynn10** [comment]
Are you sure you are using the latest build version?

**Comment by EtchReborn** [comment]
Yes i am

**Comment by jasonwynn10** [comment]
Wait, i just noticed that you aren't using PMMP. PureEntitiesX only works on PMMP due to the namespace changes.
