### ISSUE TITLE
Urgent Issue

### ISSUE THREAD

**Issue by jrodr10** [RevivalPMMP/PureEntitiesX#175]
## Issue description
```
Warning: Uncaught ErrorException: Declaration of revivalpmmp\pureentities\entity\BaseEntity::attack($damage, pocketmine\event\entity\EntityDamageEvent $source) should be compatible with pocketmine\entity\Living::attack(pocketmine\event\entity\EntityDamageEvent $source) in /home/DRv2/21/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity.php:0
Stack trace:
#0 /home/DRv2/21/src/spl/BaseClassLoader.php(128): pocketmine\{closure}(2, 'Declaration of ...', '/home/DRv2/21/p...', 0, Array)
#1 /home/DRv2/21/src/spl/BaseClassLoader.php(128): include()
#2 [internal function]: BaseClassLoader->loadClass('revivalpmmp\\pur...')
#3 /home/DRv2/21/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/entity/WalkingEntity.php(40): spl_autoload_call('revivalpmmp\\pur...')
#4 /home/DRv2/21/src/spl/BaseClassLoader.php(128): include('/home/DRv2/21/p...')
#5 [internal function]: BaseClassLoader->loadClass('revivalpmmp\\pur...')
#6 /home/DRv2/21/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/entity/mons in /home/DRv2/21/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity.php on line 0
Fatal error: Cannot make static method pocketmine\entity\Entity::getSaveId() non static in class revivalpmmp\pureentities\entity\BaseEntity in /home/DRv2/21/plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity.php on line 0 
```

## Reproducing the issue
1. start server with plugin

## Client information
PocketMine-MP Version: 0.16/1.0 (delete as nescessary)
Plugin Version: (insert commit label here)
PHP version: 7.0.13 (default)

## Optional information
...

**Comment by kniffo80** [comment]
Will take a look into this later.

**Comment by kniffo80** [comment]
@jrodr10 I've updated the following branch: https://github.com/RevivalPMMP/PureEntitiesX/tree/damage-reduction

Please use this branch along with latest PMMP and please report back if it works for you. I tested it for a short amount of time and it looks things are going normal again ...

**Comment by oddsized** [comment]
Had the same problem on PMMP v1.1.0 server, now using this branch an everything works OK. Still testing but THANK YOU.

**Comment by jasonwynn10** [comment]
@oddsized commit 4b57165 should have fixed that

**Comment by kniffo80** [comment]
Try this: https://github.com/RevivalPMMP/PureEntitiesX/releases/tag/0.2.2_dev2 (the pre-built phar)

**Comment by NycuRO** [comment]
@kniffo80 Hi , how are you? =)

Now, i'm abandonated MCPE, but i watch your commits.
PureEntities abandonated?

**Comment by kniffo80** [comment]
Hi @NycuRO fine so far. PureEntities is not abandoned yet. Simply less time to spare on this project. That's all :smile:
