### ISSUE TITLE
I spawn an entity: cant take damage of it, i spawn another, the one i spawned before disappears

### ISSUE THREAD

**Issue by kenygamer** [RevivalPMMP/PureEntitiesX#178]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
I spawn using mob spawner and i cant take damage of the mob, i spawn another mob and the one i spawned before disappears. Two errors.
...

## Reproducing the issues
1. ... Spawn a mob using mob spawner as always in inventory
2. ... Tap on it : cant take damage, or spawn another: the one i spawned before disappears and is replaced by the one i spawned now

## Client information
PocketMine-MP Version: 0.16/1.0 (delete as nescessary)
Plugin Version: (insert commit label here)
PHP version: 7.0.13 (default)

## Optional information
...

**Comment by jasonwynn10** [comment]
Can you please provide more information on the commit label?

**Comment by kenygamer** [comment]
@jasonwynn10 I do not think I have to add more information than the current one.

**Comment by jasonwynn10** [comment]
@kenygamer you did not add a commit label. This issue is invalid.
