### ISSUE TITLE
Incompatible API Version

### ISSUE THREAD

**Issue by nv0103nv** [RevivalPMMP/PureEntitiesX#179]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
When I start up PocketMine, I get an error stating "Could not load plugin 'PureEntitiesX': Incompatible API Version. However, the server doesn't crash. If I join the server no mobs are visible.

## Reproducing the issue
1. Run the version of PocketMine and the Plugin Version below.
2. In the server logs you should see the message about the incompatible API version. When joining the server, no mobs spawn.

## Client information
PocketMine-MP Version: 1.6.2dev "Unleashed" (API 3.0.0)
Plugin Version: https://github.com/RevivalPMMP/PureEntitiesX/releases/tag/0.2.2_dev2
PHP version: 7.0.13 (default)

## Optional information
Server log: https://pastebin.com/wcRfrWWj

**Comment by jasonwynn10** [comment]
That is a **PRE-RELEASE**! This Issue is invalid. Also, if you would care to note, **6 commits since this release**
