### ISSUE TITLE
Passive Mobs not spawning

### ISSUE THREAD

**Issue by Magicode1** [RevivalPMMP/PureEntitiesX#18]
Passive mobs are not spawning ever. It's just monsters.

**Comment by Sandertv** [comment]
Yep I know, I still have to add a task for that. 😋 
Once I merge the better entity generator I'll start working on that!

**Comment by Magicode1** [comment]
Sweet! I feel so bad not being able to do as much on the weekends, but the plugin is coming along nicely!

**Comment by Magicode1** [comment]
The bad thing is I am stuck on mobile for the most part, so I can really just comment and post issues..

**Comment by Sandertv** [comment]
No problem at all! I'll be less active in the rest of the week, so then it's your time to shine! 😃

**Comment by Magicode1** [comment]
Ya :D

**Comment by Sandertv** [comment]
I'm havig big trouble with spawning monsters only in dark locations. PocketMine doesn't have properly working functions for it. I'll just go use time for now, until PM implements better light checking.

**Comment by Magicode1** [comment]
Okay, I am working on Passive Mob spawning tasks.

**Comment by Magicode1** [comment]
Actually, I have no idea how your AutoSpawn task works (Maybe just coded in a different style??) DO you think you could get the Passive spawn going?

**Comment by Sandertv** [comment]
Basically what it does is it makes a random entity ID and spawns it on a random X and Y if it has the needed requirements.

**Comment by Sandertv** [comment]
But right now I'm working on improving the system so it works with biomes! I currently got the monsters done, now just the animals :D

**Comment by Magicode1** [comment]
I think I got the animals. You may need to test it, but it should work.

**Comment by Sandertv** [comment]
Alrighty! I'll give it a try :)

**Comment by Sandertv** [comment]
It works! Awesome!

**Comment by Magicode1** [comment]
YEAH!
