### ISSUE TITLE
WorldEnable

### ISSUE THREAD

**Issue by NiclasQueen** [RevivalPMMP/PureEntitiesX#182]
Please let the user set a world to enable the plugin in :)

**Comment by jasonwynn10** [comment]
https://github.com/RevivalPMMP/PEXProtection

**Comment by Sandertv** [comment]
https://github.com/RevivalPMMP/PEXProtection
It needs an API bump, but that should be fine.

**Comment by Sandertv** [comment]
@jasonwynn10 You were JUST faster :P
