### ISSUE TITLE
console error .plugin not working

### ISSUE THREAD

**Issue by optimusprime338** [RevivalPMMP/PureEntitiesX#183]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
...

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 0.16/1.0 (delete as nescessary)
Plugin Version: (insert commit label here)
PHP version: 7.0.13 (default)

## Optional information
```
[Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putEntityUniqueId() must be of the type integer, null given, called in phar:///home/multicraft/jar/pocketmine/pmmp/1.1.0/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 90" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 267
```

**Comment by caspervanneck** [comment]
ha know that there there not update it to latest pmmp. is it to hard ? @Magicode1

**Comment by caspervanneck** [comment]
btw @optimusprime338 what software are you using pmmp or somting else

**Comment by optimusprime338** [comment]
PMMP latest

**Comment by caspervanneck** [comment]
well then i know it

**Comment by optimusprime338** [comment]
Sorry , If it's my problem or mistake

**Comment by caspervanneck** [comment]
no its not yours its them
