### ISSUE TITLE
Needs API level upgraded to Alpha6

### ISSUE THREAD

**Issue by Anton404** [RevivalPMMP/PureEntitiesX#185]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
...

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: 0.16/1.0 (delete as nescessary)
Plugin Version: (insert commit label here)
PHP version: 7.0.13 (default)

## Optional information
...

**Comment by Sonnenwerk** [comment]
o/
Made my first time contribution with this request. Made a new branch API alpha 6. But can´t see it in branches. I made a pull request to merge to master (i think:-) ) . Pls check, if you can see the branch..and give feedback if it works or not.

**Comment by Sonnenwerk** [comment]
+add: I don´t know how to tag the issues..where is the tagging button ?

**Comment by Sonnenwerk** [comment]
also poggit is enabled now (did work fast and easy..found the right button)

https://poggit.pmmp.io/ci/Sonnenwerk/PureEntitiesX-API-v3alpha6-test1-/PureEntitiesX/dev:1

**Comment by Sonnenwerk** [comment]
Now it is alpha 7 :(
And i don´t have the skills to adapt the code to the new version of API...(((
