### ISSUE TITLE
 Error: "Call to a member function isInWorld() on null" (EXCEPTION) in "src/pocketmine/level/Explosion" at line 92

### ISSUE THREAD

**Issue by teracube** [RevivalPMMP/PureEntitiesX#193]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
2 Critical Error
```
2017-07-26 [11:17:12]  [Server thread/CRITICAL]: Could not tick level "world": Call to a member function isInWorld() on null 
2017-07-26 [11:17:12]  [Server thread/CRITICAL]: Error: "Call to a member function isInWorld() on null" (EXCEPTION) in "src/pocketmine/level/Explosion" at line 92 
```

## Reproducing the issue
1. Creeper and/or fireball exploded

## Client information
PocketMine-MP_1.6.2dev-311_7d777510_API-3.0.0-ALPHA7.phar

Plugin Version: (https://poggit.pmmp.io/ci/RevivalPMMP/PureEntitiesX/~/dev:97)
PHP version: 7.0.13 (default)

## Optional information
...
Thanks

**Comment by jasonwynn10** [comment]
second case of lost level reference #195

**Comment by Sandertv** [comment]
It loses level reference when it gets closed or when the entity dies, there should be a check for that.

**Comment by teracube** [comment]
hi,
What is the date of the next release please. The players of my server look forward to it. thank you for this great plugin. 
thanks
teracube

**Comment by archie426** [comment]
@teracube Please do not post off topic comments in issues.
I'm not exactly sure but I think you should just use the most recent builds you can

**Comment by teracube** [comment]
@archie426 
ok sorry for this off topic.
is this issue solved in poggit orphanage. fork ? 
sorry for my bad english

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX
