### ISSUE TITLE
#2011 Value 34970 is too large! / #2012 Value 32849 is too large! =) caused by PureEntities or not ?

### ISSUE THREAD

**Issue by totor29** [RevivalPMMP/PureEntitiesX#196]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
server crash

## Reproducing the issue
1. unknown

## Client information
PocketMine-MP Version: 1.6.2dev-315
Plugin Version: (insert commit label here)
PHP version: 7.0.13 (default)

## Optional information
https://github.com/pmmp/PocketMine-MP/issues/1251

critical error #2011 Value 34970 is too large!
https://crash.pmmp.io/view/2011

#2012 Value 32849 is too large!
https://crash.pmmp.io/view/2012

**Comment by jasonwynn10** [comment]
This issue could only happen while using a spawner. If you didn't use a spawner, then the issue is from PocketMine. In the future, please use the issue template when reporting bugs.

**Comment by totor29** [comment]
sorry, i'm a newbie, what is a spawner ?
I use only Pocketmine + plugins related in crashdump
ok for next issue template sorry
thanks

**Comment by jasonwynn10** [comment]
Have you ever played vanilla minecraft at all? A spawner is a block found in a dungeon which spawns mobs of a set type

**Comment by totor29** [comment]
ok thanks, but it's a new server with only :+1: 
PocketMine-MP 1.6.2dev-314: PurePerms 1.4.1-dev1; BlockPets 1.1.0; ItemCasePE 1.1.0-dev1; FactionsPro 1.4.4-dev1; SignPortal 1.1.3-dev1; AlwaysSpawn 2.2.3-dev1; Cameraman 1.1.0-dev; TreasureChest 1.2.1; PureEntitiesX 0.2.2_dev; SimpleAuth 1.8.1-dev1; SimpleAuthHelper 2.0.5-dev1; PiggyCustomEnchants 1.0.2; essentialsTP 1.1.1-dev2; ChatToDiscord 1.1.0; Parkour 1.5.3

I do not understand the origin of the bug.
Yesterday there was no bug in the same configuration.
How can i find the problem
thanks

**Comment by jasonwynn10** [comment]
I need you to fill in the template information for me to be of any help

**Comment by totor29** [comment]
the template information ?
is ist this file on attachment ?
thanks
[Downloads.zip](https://github.com/RevivalPMMP/PureEntitiesX/files/1180512/Downloads.zip)

**Comment by jasonwynn10** [comment]
What is your php version,your PocketMine commit hash, and your plugin commit hash?

**Comment by totor29** [comment]
my server is hosted and i just use a panel  ?
where find this information ?

thanks

**Comment by jasonwynn10** [comment]
type version command on console

**Comment by totor29** [comment]
This server is running PocketMine-MP 1.6.2dev-314 「Unleashed」 implementing API version 3.0.0-ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113)

**Comment by jasonwynn10** [comment]
can you tell me if you are using PMMP PocketMine?

**Comment by totor29** [comment]
I use and download PocketMine MP at this link
https://jenkins.pmmp.io/job/PocketMine-MP/

is it PMMP PocketMine?
thanks

**Comment by jasonwynn10** [comment]
It sounds like you are using 32 bit software, but then pmmp wouldn't run...
If the server is having issues without PureEntitiesX on it, then it's a PocketMine problem

**Comment by Sandertv** [comment]
Perhaps this isn't even PocketMine @jasonwynn10, we don't know what the host is actually running. As PocketMine dropped support for 32bit I guess this is a spoon that hasn't dropped 32 bit support.

**Comment by jasonwynn10** [comment]
@Sandertv we never decided to only support PMMP on this plugin, and @kniffo80 has made some parts to be compatible to 3rd party softwares, so what do you think we should do about it?

**Comment by Sandertv** [comment]
Not entirely sure. If this is indeed an issue with a third party software, then we can't do anything about it.
