### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by winterbuild7074** [RevivalPMMP/PureEntitiesX#197]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
I get these errors in console:
```
[Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Argument 1 passed to pocketmine\utils\Binary::writeVarLong() must be of the type integer, null given, called in phar:///home/mcpe/PocketMine-MP.phar/src/pocketmine/utils/BinaryStream.php on line 367
[Server thread/CRITICAL]: Error: "Call to undefined method revivalpmmp\pureentities\entity\animal\walking\Cow::getInventory()"
```
It crashed my server.

## Reproducing the issue
Join server

## Client information
PocketMine-MP Version: 1.1.4
Plugin Version: newest

## Optional information
```
[Server thread/CRITICAL]: Could not execute task revivalpmmp\pureentities\task\AutoSpawnTask: Argument 1 passed to pocketmine\utils\Binary::writeVarLong() must be of the type integer, null given, called in phar:///home/mcpe/PocketMine-MP.phar/src/pocketmine/utils/BinaryStream.php on line 367
[Server thread/CRITICAL]: Error: "Call to undefined method revivalpmmp\pureentities\entity\animal\walking\Cow::getInventory()"
```

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX
