### ISSUE TITLE
Could not tick level "world": Undefined offset: 0 in MobDamageCalculator

### ISSUE THREAD

**Issue by ZizzyZizzy** [RevivalPMMP/PureEntitiesX#198]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
```
10:34:36 [Server] Server thread/CRITICAL Could not tick level "world": Undefined offset: 0
Server thread/CRITICAL ErrorException: "Undefined offset: 0" (EXCEPTION) in "PureEntitiesX_v0.2.2.phar/src/revivalpmmp/pureentities/utils/MobDamageCalculator" at line 92 02.08 
```
## Reproducing the issue
It happens only when players are on the server.

## Client information
PocketMine-MP Version: `PocketMine-MP 1.6.2dev [#30c5487 2017-07-08] ���Unleashed��� implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)`
Plugin Version: v0.2.2_dev (be2c324)
PHP version: 7.0.14

## Optional information
Plugins (7): SimpleAuth v1.7.2-php7, PureEntitiesX v0.2.2_dev, PeacefulSpawn v2.5, MagicWE v0.3.0, BlockSniper v1.4.0, SimpleAuthHelper v2.0.4, EssentialsPE v2.0.0

**Comment by jasonwynn10** [comment]
The server is outdated

**Comment by ZizzyZizzy** [comment]
Actually, PureEntitiesX is outdated. It will not even load in ALPHA6 PMMP unless the API compatibility check is disabled in the source code.

I just tried PMMP commit #8bb0c53, which was the **very last ALPHA6 commit** before the API was bumped to ALPHA7, but it does not work with the older plugins, including PureEntitiesX, as dktapps changed a bunch of declarations:

`INFO Fatal error: Declaration of revivalpmmp\pureentities\PureEntities::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar:///plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities.php on line 82`

The same thing happens in PMMP ALPHA7 for the same reason.

**Comment by Sonnenwerk** [comment]
PureEnt runs with Alpha7. Buggy though, but it runs. You can change your server version up to latest dev.

**Comment by jasonwynn10** [comment]
@ZizzyZizzy you aren't using the damage-reduction branch for alpha7. That also makes this issue invalid

**Comment by ZizzyZizzy** [comment]
Neat, I wasn't aware that was an ALPHA7 branch.

Is there a branch that doesn't have the bug in the subject of this issue? That is, for ALPHA6 API.

**Comment by jasonwynn10** [comment]
Nope, and the lead developer for this project is taking an extended break, so many of the bugs won't be able to get fixed.
