### ISSUE TITLE
Entity base tick error on startup

### ISSUE THREAD

**Issue by Infernus101** [RevivalPMMP/PureEntitiesX#20]
Warning: Declaration of magicode\pureentities\entity\BaseEntity::entityBaseTick($tickDiff = 1) should be compatible with pocketmine\entity\Living::entityBaseTick($tickDiff = 1, $EnchantL = 0) in E:\PocketMine-MP\plugins\PureEntitiesX-master\src\magicode\pureentities\entity\BaseEntity.php on line 0

**Comment by Magicode1** [comment]
Thanks! We will get right on it!

**Comment by Sandertv** [comment]
Yep! I've noticed that too. It happens on startup!

**Comment by Magicode1** [comment]
It shouldn't cause any issues with your gameplay. But, we will try to fix that in the near future!

**Comment by Infernus101** [comment]
Does this have auto spawning and is it laggy?

**Comment by Infernus101** [comment]
Also you should give an option like which world do you entities to spawn..

**Comment by Sandertv** [comment]
Currently, yes there is auto spawn for monsters at night. We haven't tested the performance on larger servers so I'm not sure. We'll be working on a condig fairly soon, before the first real release for sure. ( no ETA yet )

**Comment by Infernus101** [comment]
what about animal entity like cow and pig spawning in the world?

**Comment by Sandertv** [comment]
We're working on that as well right now :)

**Comment by Infernus101** [comment]
cool! excited xD

**Comment by Magicode1** [comment]
Same!! It should be awesome!

**Comment by Magicode1** [comment]
Auto Spawning is implemented, and this bug is fixed.

**Comment by Infernus102** [comment]
YESSSSSSSSSS

**Comment by kniffo80** [comment]
... can be closed ...
