### ISSUE TITLE
Enable per world

### ISSUE THREAD

**Issue by optimusprime338** [RevivalPMMP/PureEntitiesX#200]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
...

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (insert commit hash here)
Plugin Version: (insert commit hash here)
PHP version: 7.0.14 (default)

## Optional information
... Can you please add so we can enable in them only in certain world or regions!!

**Comment by 95CivicSi** [comment]
Most recent versions of PureEntitiesX have an option available in config.yml called `enabledworlds`.  This can set as an empty array to enable in all worlds or the array can have the world names specific to where you would like spawning to be available.

**Comment by 95CivicSi** [comment]
Additionally, PEXProtection is available for more specific spawn control.

https://github.com/RevivalPMMP/PEXProtection
