### ISSUE TITLE
Error: Declaration of Stray::getMaxHealth() must be compatible with Living::getMaxHealth(): int

### ISSUE THREAD

**Issue by HyperCoffee8142** [RevivalPMMP/PureEntitiesX#205]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Server creashes on startup, shows the error.

## Reproducing the issue
1. start up server

## Client information
PocketMine-MP Version: 1.6.2dev-513 "Unleashed" (API 3.0.0-ALPHA7)
Plugin Version:  v0.2.3
PHP version: 7.0.14

## Optional information
...
#### Server Log during Error:
[23:03:20] [Server thread/INFO]: Loading pocketmine.yml...
[23:03:20] [Server thread/INFO]: Loading server properties...
[23:03:20] [Server thread/INFO]: Selected English (eng) as the base language
[23:03:20] [Server thread/INFO]: Starting Minecraft: PE server version v1.1.0.55
[23:03:20] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[23:03:20] [Server thread/INFO]: This server is running PocketMine-MP version 1.6.2dev-513 "Unleashed" (API 3.0.0-ALPHA7)
[23:03:20] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[23:03:20] [Server thread/INFO]: Loading recipes...
[23:03:20] [Server thread/INFO]: Loading resource packs...
[23:03:20] [Server thread/INFO]: Loading PureEntitiesX v0.2.3

Fatal error: Declaration of revivalpmmp\pureentities\entity\monster\walking\Stray::getMaxHealth() must be compatible with pocketmine\entity\Living::getMaxHealth(): int in phar://C:/PocketMine-MP/plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Stray.php on line 40
[23:03:20] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[23:03:20] [Server thread/EMERGENCY]: Please upload the "C:\PocketMine-MP\crashdumps/Wed_Aug_30-23.03.20-AWST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
bin\php\php.exe: Exit 1.

#### Crash Dump:
PocketMine-MP Crash Dump Wed Aug 30 23:03:20 AWST 2017

Error: Declaration of revivalpmmp\pureentities\entity\monster\walking\Stray::getMaxHealth() must be compatible with pocketmine\entity\Living::getMaxHealth(): int
File: PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Stray
Line: 40
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[31] use pocketmine\level\Level;
[32] use pocketmine\level\sound\LaunchSound;
[33] use pocketmine\nbt\tag\CompoundTag;
[34] use pocketmine\nbt\tag\DoubleTag;
[35] use pocketmine\nbt\tag\ListTag;
[36] use pocketmine\nbt\tag\FloatTag;
[37] use pocketmine\Player;
[38] use revivalpmmp\pureentities\data\Data;
[39] 
[40] class Stray extends WalkingMonster implements ProjectileSource {
[41]     const NETWORK_ID = Data::STRAY;
[42] 
[43]     public $height = 2;
[44]     public $width = 0.781;
[45]     public $length = 0.875;
[46]     public $speed = 1.0;
[47] 
[48]     public function getSpeed(): float {
[49]         return $this->speed;
[50]     }

Backtrace:

PocketMine-MP version: 1.6.2dev #513 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT KUYA-PC 6.3 build 9600 (Windows 8.1 Professional Edition) AMD64
PHP Version: 7.0.18
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWmtv4ziy/SuEM8B2X1iOH3EeHmSBoDuz05hOx7eTRvbhRUBLlM2JJGpEKo5nMP/9nipSsuzO
NO5i98Pmw7TFR7FYrDp1ipzfek7nqjcbTYcno+H0ZDjs91RVmao3+63ntiW6eteP725v5h8+Xj9e
f/58+7nX7+XKWrmivvcqzmQlnTaFMKmo1LN+llmZ5+ViUdaVUoXTTiu7WPCv7WKRm8I6VS0WG5k9
6WK1WNy5Sm5ns5VyN/LlRyUzt37zVuS1dWKpRGzyEvKXmRIb7daiNPGTcrku1E7mR/0MSYciZkIX
DtqmOiNV51DnOqjz10G5ltWxreLjjsrHXY2PvfDjoO9xUPeYtYXUDBr0ZifD3/u9MqtXuujNXFWr
fi82iSLrTUZYtLZqT+NMPasMCtM/30PKZPzHg6ypiwRjZV3E6zv64BmTV2YUS7dYOAljvoO5aOi9
XPHok2+Ofm9qGLYZO/3m2I/aumbk6TdH/pAZ2Q49e2XoPJNbVXH3eej+huck0kmoiv/yjAvMwL8n
Q/wL57NW8JEI9eJUkVjx4A/qxp+b0HmZqRzSrJhX5mcVO7gDrFnFSvxGcuiYBP5imiA+Xd8/3H7+
6fHDe3EpaM3Z7O7+89XfaOmTcVh6EqaUsJ6OxXdrpVdrhwljHnZy0L3RCRz3UgwHZ+cjHjE9GJGp
YhWGnJ9NecjpwRBbKpVgxGgw5P6zoMv5/rgUzsLRiFi4oykUBykdiN/tRRhOf5VydVWI79xa2+jP
vACJng7DmN97cG7YNoY//+Of/d5KFaqSGTl3IXOOKT7UGxxqdDPH1GdVWSyOntHgdDBO1DMal7XO
kt5sOpogVCrjTGwgY0SfstQYOxkMB8Po6uP8x6szjF9ph8bh//MPEyr5lOklzRmcD0ZoqIN6D7pI
zMaKT/fipy9/u4rm78TpYCJYIXFxOhyKN80QTCT/SIFs2IDMxHWiyY5vxdXN+9MTCC3XJUSeQdfR
OT5/hbM1uvveR2NpzQ+fPt2jgT82gIUWIKy3Ygm8zBVcM3xbVcFsA1imVBV5POYdzdsv8c4UqV4J
QrFFtSiOHuAGV/VKTIZiPJkNJ7PRqbh6uLsX4+HojEbkxiWXN0oXP2GhMnXU5heJyC5/0FWayl2O
LkaTMTWuMDAHkF0OWaJ8iUqOWXs5OuVJpdwUEZ2mYne7jEbUvFlrp6IMSHFp0pRaVCGBMNEvtaq2
l6boNFUIuGaULAqAVqzCKpGM1xogyGEbZsksM5sozSjSmmleC1noXGbNON+Wm2XTkBqEetRuKEwF
/Cexqdrv8rlsfiY6TXVcZ257yZvybu9MFVnlHKDFXlIzo7S36MZUWbJrswikzhBKo5fvr3+4+vLx
nlpp44MSwIVpyeX/8B/2VzsTWfmsgtrPWm2iBJaUsMvlCTWRm7UoOtjmGXmKuJG6IPCCk9QhE5Ov
COxb7MUnfEfcrxXAttmHkJUSbq2EKeBobg2QiOkoOPHqIs7qBM4G8V/5KMm6M7mipO++lmllqvrC
oKeyJFIsKyWfxBawG2QJnQqch041r4CjqOBJ2ZYEf1KbVtxxolKJs7BiY4o/OSHLUslKkLVybDaG
W2yhviAM8/verFUh6nJVyQQCBouCXNwLmy0KcXS/RnKJMjRBi0wWqxpURlDWZpOFcLAa35mBfP0r
G5WmvlurOOxifyIUWDtX2tkxaMNgo590qRItB6ZaHdPXMSXPR5M+fri7fTydXETjR5oHM7aCZmLR
QxZY9Gihh7Ui2wlnoE+RCOxSWFexfQHIhc2kg924m63JmkIP/FKOjxTYq5Hi1rJIMj7kHIJ9LOyW
TBE3Cu12XTvAIOLGMztS5s5LjjNjVeLVuqIYFBTe0EQEVBPPWor/pfjGEI7zKPTMBDEimni3xjzJ
KdZAm7CKPyoZBAnQAAu1SzgC7+5q/gEj3dokZKddRwS1llBqJ/6aEaWRgx0LCm0Bd4VHkKrLrQh+
hOEBf9renRmOHjQMbQq4lEwS5EfrPY/UhK89QR1pwU0IlwT8banIHjC6+qVGysBxrPQzxoLI1Eq8
CUsCmN9CuF8PuKcIaiOc5mqlqhl6aeVPdb6EtRFOV3ZbxPfSPsHjqycE0ID6v+AQ2D+bTdKodWWA
m3AJjLZ9wTAkAlzBZftMniuf0tgsG7WktrwuEDk0hGXfsctgPwiuyrwATZ2CCbAddvWiVY2s6tX5
kFKE0hCKxL7Q7k+wnKt4VqIoK7AXHswVb7ADontjsgjvIQq7nLEkilYC6mrLsfqXzCxhWGtSJ3wz
vC/XjjApVyu53DooJO68KkNeXFs6Xh/p2NNGs2JsbEEpxMtp7G/ZLqmGuwCmgNcFi0qBEc2K/vix
mZqddmWwD0OhQTbDOitWMmLFZmK4YKhgVHaAGpn8l6ufQ9NvKE+J8t9S3jpT8voBqlp9gjQrEFKU
DoEyQRtas1HpZHhx6rWaq0obTkcUi5YWjBmQg3ZtvI2wFKAmIR/jERHiQflIYxg3qC0KRCjsRujw
R2b15gSnyRjhKdb9sAUnXJKB6NtFsocjWuGWIIQyHA8ffD2Ytu1xKIEJSxVTIrRsFtLV29jPbTcA
S6rS7rYJAuj3ad++qlDY9cTveiWrJc4/AvnOPGejCHvVquxOpEqYI8IcxG4ui5pTblcL0JEavvC2
32DCgTMEb/C4mqYNNuQ7LxuIW5/v+AsesTZ1lrSKaCDIphA71clvRcmaY4Mg8n6P4ugHjoSvsJF9
xc9uN5VWJm8gluaG/qiLSp0zxSbC0R26wiv+05lH3Dle18WT9fa+kQDYOkdyKRIIaxge7UZ49usj
ZLcE+UqQyyEiWFxE/KYGbJ4E9d4b33F4anw1UzQSaGjjH15OGPYf2CrnnygGeVd+s8EFmoWoo03a
3xS1KArl6AhaxgaPyHwCXEqH6oD4hyRyi7wHNwpgxHHn+Wjo9RgU7pEoFbIJj7qo1fRQvFdbR7L7
Ihp1fJhSHi8buUYVoMn01IPJLsUy36f8lvgzJO7G9IPmojHoNBA/ooqBeS9BgeGv7+Zf+pgLDZaA
HX9bwGDNYd2Kj1j8TJwHPrBjCpYN0xk6EFcJwmgts/QY3N6Tl0TBvcJCWBIHAHg3RTcO26TckdWh
R9cvFHPEfmTW9/FMC4caeiDgNopjjVL8l3kxbwjCjqoT96FJG0D8gnh6UUbhs0vFUIWpZb3yx28C
VApKEhU7tHpRce05DmEOFeODtteSRzB1QVU+0IUmNUa8t2aEj8UHWRUE052ZVL0EYCYpQUBfJEgX
tJndyFxu6XJJAlKgUFUXdJNKYYzt5BzSkNxgPC2HPRaRTqPQtqOvIFN/FiMiUSFjElvm/TdMmXdE
mBkY9CL42oy3FfivFcfAElcjIo5XsfcdKJLY3QmizmWImflqxoBFk6c2tYZqeDTDEN27oZJ79lUU
/Wrrc+pq9ZfYOUJcSeetiu3wev2GvDAphDtxOvX3WJReCxNnuhQ8E85zA3vGkjwnN88Nxba1sv7e
11K1uUSd80SEXMdrPiqqVbdwAF+ZZtvddV8wur82aCR6NTsG6WpL52f9Er5etd4mxPiDTWy7KAsi
y3T0/o+pi9rJSVZhB4nN1cJeJauaskaw0zlfw/PQgHy1DWVWDHGOwS9MifyUmSjhJM864wJvL1Zj
FI/II0EcYwjzEFiFMMMRboyHgTdQ/vJ0hFyCLjOoPXCQxlP2mhuG5wugOwJrcvGltKqz2JsR3at+
vUpfjOk29LUO5eLBW4Zsq7pacKzck2Sqp5sTVUhLfj1yUG8svrnYXWlQGuDSlygznZPMNnJrvewg
pwNdPt0F8G8gLBgzkOCCbJ8dkoB+M2rv8ufVCxiuwq5yA9jh6ooZBiUczmvN3sgqpCSVnwhb+gkz
cN76zPShM5ddp1D+WmGpvKylSilD8aUaZTI6IC+cEIGv2jo8BKcIkEBFD3U13ZwoqsTLbbglCvyk
5bacPFLJ1/TBWiG1pXXGw4x12TYiVNOxpxdcjVd0NeNY+WanPxsqij2xtDJXHM2EgUQ6GgJ2eERk
j+aIwMuEPLQn7B0zZ9h5yZ4pp8NXTSkreoLhmw1GUhg0TA3e6C02Jhin+8yoLoGoqoNLcaakX4Rv
Uzu54j0vFJCF8ISO2ycdBAwScS7CtoQv7xsSxlO6WxZHEWLoSKwqZLWdUXb3B41dBl8bJqSjjdR8
FfRLrXx+hN+E+Qw13B5ZOEKgLf+ytNKUdRakhd9EhQ4ELwpGgaj0qc3fCEfsn+SZVB6I8JDXto4C
IFFemwlfQzTuAusXdTkTF76w8I7OcOWZQ5AFKWdDhm1/BQ2hU5/paaG2kdtkvtSIKD8kXPf6q6CZ
hz+6tcJJrIVv9ZwuOKCPjEPiQDET0T3ifkubI/ZawWR0kZqdi60N+RUvOehcK4N4s36FKbY5VZMc
fRb2ta2iVB6HbrHrZoWZNMjVqlKrcAfV3u5RTUKvSU+v78brQ+Lsa/qQvXyY8BEfzoZP+N5ZS7UC
V9pVHNxqys695Du6mua7UpWZkvJwH9hermUfzdgI3Qe7pgIAg0lVhRosIpQuiH3RoMDgajokhHxH
lgjPYR1mV6POsc7DfIOnQRodlO9u5NsD2/gNDuiNdKCN9/q8ZQOBzpFEGt7QcDoUSie0GnPiMKe5
3Ry04kNHV35jwm/SxZDS+OSC83r06TJWSHfejEefbu+vZ/QS4dsYrqjqDYVawCu6fkUlm3C5otNW
DspV7GJHxDoMm8UFZG5oE7IQWIC30PWLJLrlP4hkQ79wRLPmrLgLiEC3VjPxDya9yP19vsb6J0n0
aaghYN2XD94BXa1V9HjAFyjN0xFXKa/lcWbCTC4sF2RkuRznoqFoYF4d1XlVVoB/CXppInzj3Ltb
bSZ++Hh1Pxt/f9afXryM+pOXSX/8/ej7BATJQ/sbVyl8AIYvz4c+A/ivk+lbfmji13QyiKXn3ncg
Ad3Hz2UMlrjuttDzQ5HIaq8t/A8kbQO5b/c71RnCuduyBhrx6zG9qWqc+XO392cb3pZPuD+Pq23p
ugPu5h+7n2W8r/ZnlYYbkW6r9XXuXhOIFzaTdNvyrf0l4zff8EtMqWscIeJFRK+v0+HJ8Aw/v/uA
Q1lO4+nF8DQ5mY4V/TqbjOXFZDmcjtLJ+fhMDcdnJxfL84n4DrKdeVIFktmeLX7VJW92NBlM6dO/
cbfd+HzhJ8CdeU2Oz/FwOBmNxhdomL+/7fbD5wpr96bccQHy15s9sx2I3STJy0E33RXsK4vGTaUP
TvMBFQxAk1/mJ4MJuURdZV8ZVXdb5mt2ojG+x3QS6HZqwiLOIv8/FFjODnZPztI/j3XbtpL3MW5e
6MPlIj/ajwanpI3JHxPjkGK681Z7x77K9579/055+nbOPGHX/vvv/wfavOmp
===END CRASH DUMP===

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX
