### ISSUE TITLE
Hello hello

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#206]
Hello hello.

About this plugin, i like them and it's a very very good.

I can port them to Nukkit? 👍

**Comment by jasonwynn10** [comment]
I would recommend asking the developers at the new repo:
https://github.com/poggit-orphanage/PureEntitiesX

**Comment by NycuRO** [comment]
Yes, but this is official repo, need get this permission. If you want, i ask and them.
