### ISSUE TITLE
BaseEntity public function attack changed in ALPHA7 PMMP

### ISSUE THREAD

**Issue by ZizzyZizzy** [RevivalPMMP/PureEntitiesX#207]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

The attack function was updated. Parm 1 is needed now and must be damage amount. Almost all of your files under entites/ need to be updated to reflect the change. Easy fix, just time consuming and not backwards-compatible.

Update to the latest official PMMP build. Attempt to load PureEntitiesX v0.2.3, check crash file.

[Server thread/CRITICAL]: TypeError: "Argument 2 passed to revivalpmmp\pureentities\entity\BaseEntity::attack() must be an instance of pocketmine\event\entity\EntityDamageEvent, none given, called in phar:///home/multicraft/servers/server3/plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Wolf.php on line 320" (EXCEPTION) in "PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/BaseEntity" at line 252

## Client information
PocketMine-MP 1.6.2dev [#02f42eb 2017-08-20] Unleashed implementing API version 3.0.0-ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113)
Plugins (4): EssentialsPE v2.0.0, SimpleAuth v1.8.1, PureEntitiesX v0.2.3, SimpleAuthHelper v2.0.4

Honestly changes like this should bump the API. It's deceiving to have an ALPHA7 working plugin break 7 days later because PMMP source changed ever so slightly.

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX

**Comment by ZizzyZizzy** [comment]
Ugh, the source code has changed in the last 11 days again. BaseEntity.php doesn't even exist now.
Once I finish updating PHP to 7.2 for today's change, I'll test and comment here if it's still broken. (From what I see in today's PMMP source, the $damage var is gone from the declaration.)
