### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by QuiverlyRivalry** [RevivalPMMP/PureEntitiesX#208]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
... Started server showed this error

## Reproducing the issue
1. ...Start server
2. ...

 
## Client information
PocketMine-MP Version: (his server is running PocketMine-MP 1.6.2dev+poggit.1250 「Unleashed」 implementing API version 3.0.0-ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113))
Plugin Version: (latest)
PHP version: 7.0.14 (default)

## Optional information

07.09 19:51:06 [Server] Server thread/CRITICAL ErrorException: "Declaration of revivalpmmp\pureentities\entity\BaseEntity::attack(pocketmine\event\entity\EntityDamageEvent $source) should be compatible with pocketmine\entity\Living::attack($damage, pocketmine\event\entity\EntityDamageEvent $source)" (EXCEPTION) in "PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/BaseEntity" at line 538
07.09 19:51:06 [Server] Server thread/CRITICAL Could not load plugin 'PureEntitiesX'
...

**Comment by Sandertv** [comment]
You're using an outdated PocketMine version. Please update to the latest version.

**Comment by QuiverlyRivalry** [comment]
chscbsbcnsbc pmmp updates regurlary and my host every flipping month d\dbsn\bdbdnbd
