### ISSUE TITLE
Monsters Spawn in sight and in rapid numbers constantly.

### ISSUE THREAD

**Issue by Glyphs** [RevivalPMMP/PureEntitiesX#21]
Alright, this had been happening before commit:  https://github.com/RevivalPMMP/PureEntitiesX/commit/47af8d1123836442544e57a74b5a2386b0029bd0 but has just gotten far far worse..

![image](https://cloud.githubusercontent.com/assets/10164439/21098992/28281d64-c06c-11e6-9ffc-598a52d8d756.png)

Monsters are spawning at a very rapid pace and just endlessly multiplying if you stand still. I don't think that's how it's supposed to work, there should be some spawning on chunk generation, and some dynamically.. But as far as I recall there's an upper limit as to how many there are active at once per chunk? It is impossible to even walk around because of the sheer amount of monsters instantly coming to kill you.

EDIT: They also all seem to spawn in the same holes?
![image](https://cloud.githubusercontent.com/assets/10164439/21099112/b1e3e146-c06c-11e6-9842-ba1427b3bf70.png)

**Comment by Magicode1** [comment]
Hmmm, this hasn't happened for me. Me and @Sandertv will look at this, stay tuned.

**Comment by Magicode1** [comment]
I made a new commit ( [Here](https://github.com/RevivalPMMP/PureEntitiesX/commit/5c99a9ef2cfd2535eb173bc891d7d7999fc4630a) ) that fixes this. Let me know if it works!

**Comment by Glyphs** [comment]
Can confirm this works a lot better.

![image](https://cloud.githubusercontent.com/assets/10164439/21099673/cdd2822e-c06f-11e6-89a0-6bdb5c90d3c0.png)

There's still a good bunch of mobs around (as there usually are at night), but it no longer instantly spawns 10-20 around you as soon as it turns night now!

**Comment by Magicode1** [comment]
Awesome! Have fun with it! Thanks for posting this issue!

**Comment by Sandertv** [comment]
Monsters tend to get all together in the holes because they don't have the ability to jump up blocks yet. We're working on this!
