### ISSUE TITLE
Causes PocketMine-MP v1.7dev-26 "[REDACTED]" to stop accepting console commands.

### ISSUE THREAD

**Issue by 95CivicSi** [RevivalPMMP/PureEntitiesX#210]
This issue was initially reported by mrvanes in the comments of issue 209.  

mrvanes, please provide the following information to help us recreate your problem.

OS used to run PocketMine-MP including any significant Version number (eg. Ubuntu 16.04, Windows 10, macOS 10.13).

How you installed PocketMine-MP (including any control panels or wrappers).

How you installed PureEntitesX,

Any other known, relevant steps to reproduce the issue you are having.

Server Logs or CrashDumps that can show any related errors.

**Comment by mrvanes** [comment]
OS: ubuntu 16.04, fresh install from mini-iso, fully updated
PocketMine installed from
```
$ wget -q -O - https://get.pmmp.io | bash -s -
```
PHP 7.2RC1 built from (all requirements fullfilled, no compile errors)
```
https://github.com/pmmp/php-build-scripts
```
After build, I moved the bin/php7 dir to pocketmine/bin/ dir, to replace existing php7 binary.
start.sh now works like a charm.
cd plugins/
```
$ git clone https://github.com/RevivalPMMP/PureEntitiesX.git
$ wget https://poggit.pmmp.io/r/11519/PocketMine-DevTools.phar
```
restart the PM server
```
reload
```
Now, DevTools and PureEntitiesX load but console is non-responding.

**Comment by 95CivicSi** [comment]
I have been able to confirm your problem.  It appears that console output for help (and possibly other commands) is being redirected to the PureEntitiesX log.  mrvanes if you type `stop` into the console, does the server stop?

**Comment by 95CivicSi** [comment]
Also, check and see if this solves your problem. 
[PureEntitiesX.zip](https://github.com/RevivalPMMP/PureEntitiesX/files/1295834/PureEntitiesX.zip)

 This is the plugin as it was at this commit:

[https://github.com/RevivalPMMP/PureEntitiesX/tree/35709a8433886ba2807032b6c49f21e0411f21a2](url)

**Comment by mrvanes** [comment]
1. Yes, the server reacts to stop.
2. I can confirm the linked zip fixes the problem.

**Comment by 95CivicSi** [comment]
This problem should be fixed with this update:

Commit: https://github.com/RevivalPMMP/PureEntitiesX/commit/88f66801031da34fca75372dfcfe11d3b13bc3c1

Newer Updates from the MCPE-1.2 branch should include this fix as well.
