### ISSUE TITLE
jump

### ISSUE THREAD

**Issue by RubyTemple** [RevivalPMMP/PureEntitiesX#213]
all entity jump 2 block.

i have pmmp
i have a standard config.yml

**Comment by 95CivicSi** [comment]
Thank you for splitting the problems.  Please provide the following information to help us figure out what is happening.

Version of PocketMine-MP being used (eg. 1.62-dev360).

OS used to run PocketMine-MP including any significant Version number (eg. Ubuntu 16.04, Windows 10, macOS 10.13).

How you installed PocketMine-MP (including any control panels or wrappers).

How you installed PureEntitesX.

PureEntitesX Configuration File.

Any other known, relevant steps to reproduce the issue you are having.

Server Logs or CrashDumps that can show any related errors.

**Comment by jasonwynn10** [comment]
Actually this is a known bug... all entities will jump as high as needed to reach where they want to go.

**Comment by Emis02** [comment]
Core: PocketMine-MP 1.7dev alpha7
Os: Ubuntu 17
Pl: by Poggit
Config: standard

**Comment by cyphr3x** [comment]
> Actually this is a known bug... all entities will jump as high as needed to reach where they want to go.
I wish that were true.  Typically when they encounter an obstacle even a single block high they just pump in place forever.

**Comment by 95CivicSi** [comment]
This was fixed with https://github.com/RevivalPMMP/PureEntitiesX/commit/f85a659901564620b88ac0db0b59f2537a210f38
