### ISSUE TITLE
i have an error

### ISSUE THREAD

**Issue by Emis02** [RevivalPMMP/PureEntitiesX#217]
i hadd this error when i put:
"_enabledworlds: - bw_"

 TypeError: "Return value of revivalpmmp\pureentities\PluginConfiguration::getInstance() must be an instance of revivalpmmp\pureentities\PluginConfiguration, null returned" (EXCEPTION) in "plugins/PureEntitiesX_dev-111.phar/src/revivalpmmp/pureentities/PluginConfiguration" at line 67

**Comment by 95CivicSi** [comment]
The enabledworlds option requires that you put a list of worlds inside square brackets.  Each world has to be separated by comma.  Example:

`enabledworlds: [world, lobby, myworld]`

You can leave this list empty if you want Mobs to spawn in all worlds.

`enabledworlds: []`

**Comment by jasonwynn10** [comment]
Another format would be:
```
enabledworlds:
 - bw
```
