### ISSUE TITLE
Eggwars shop

### ISSUE THREAD

**Issue by Emis02** [RevivalPMMP/PureEntitiesX#218]
I put in the world eggwars the shop that are crawlers and the PureEntitiesX plugin has taken them all away

Config

enableworlds: [SF]

But the ew shop are in pizza world!

**Comment by 95CivicSi** [comment]
Check the plugin and make sure this post is in the right area.  You said PureEssentialsX plugin in your post but this issue is listed under PureEntitiesX.

**Comment by Emis02** [comment]
Yes sorry pureessentialsx

**Comment by Emis02** [comment]
I have wrote badly

**Comment by Emis02** [comment]
How do I remove villagers From the action of this plugin?

**Comment by 95CivicSi** [comment]
Recent updates to the master branch will solve some of the problems you are dealing with.  Particularly the removal of entities not generated by PureEntitiesX.
