### ISSUE TITLE
PocketMine-MP support

### ISSUE THREAD

**Issue by kenygamer** [RevivalPMMP/PureEntitiesX#224]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Protocols issues, plugin doesn't initialize in PocketMine-MP servers.
...

## Reproducing the issue
1. ... Install PureEntities in any PocketMine server.
2. ... Restart the server and any players join will result in a Server Closed.

Take a look at the `EventListener` class

## Client information
PocketMine-MP Version: 1.7dev-31
Plugin Version: v0.2.5-PM1.7dev2
PHP version: 7.0.14 (default)

## Optional information
...

**Comment by 95CivicSi** [comment]
You haven't provided enough information to resolve your issue.  We need to know what version of PocketMine-MP you are using and any errors you get during startup.

For Reference:
![pureentitiesx verified](https://user-images.githubusercontent.com/3009473/30778271-6c0991ac-a09f-11e7-8e4d-92404cb3d463.png)

**Comment by kenygamer** [comment]
Ok, now.

**Comment by jasonwynn10** [comment]
Are there any debug outputs or crash logs?

**Comment by kenygamer** [comment]
@jasonwynn10 Give me 10 hours.

**Comment by 95CivicSi** [comment]
Also, are the clients that  are connecting using Minecraft PE or Windows 10 edition that is a version before 1.2?

**Comment by kenygamer** [comment]
@jasonwynn10 There are classes not found like `pocketmine\network/protocol/Info` instead of `pocketmine\network\mcpe\protocol\ProtocolInfo`

**Comment by jasonwynn10** [comment]
This repository doesn't support spoon use

**Comment by kenygamer** [comment]
@jasonwynn10 I'm using the official PocketMine-MP.

**Comment by 95CivicSi** [comment]
@kenygamer Please check this version of the plugin and see if it solves your problem.
[PureEntitiesX_v0.2.6-PM1.7dev65.zip](https://github.com/RevivalPMMP/PureEntitiesX/files/1329100/PureEntitiesX_v0.2.6-PM1.7dev65.zip)

**Comment by jasonwynn10** [comment]
@kenygamer namespace issues don't come from using API 3.0.0-ALPHA8 of pmmp. They come from using spoons and old software

**Comment by TheDiamondYT1** [comment]
@jasonwynn10 He is saying that the correct protocol namespace contains the `mcpe` directory where as this plugin does not, it include the old namespace. Apparently. I haven't checked.

**Comment by jasonwynn10** [comment]
I can assure you, this plugin utilizes only the new namespaces @TheDiamondYT1

**Comment by TheDiamondYT1** [comment]
oh then idfk what he's on about

**Comment by 95CivicSi** [comment]
Information in the original post is lacking of significant information and appears to be incorrect.

Check your PHP version (update to 7.2 if necessary) and start a new issue if your problem persisits.

**Comment by kenygamer** [comment]
@95CivicSi Hello, I installed with the link you provided and my server with the plugin doesn’t respond to anything, except the `stop` command. Can you please fix this weird issue?
#
Best Regards,
/ Kevin Andrews

**Comment by 95CivicSi** [comment]
@kenygamer What you are describing is different from the original issue.  The console response problem was reported in #210 and resolved with this commit:

https://github.com/RevivalPMMP/PureEntitiesX/commit/88f66801031da34fca75372dfcfe11d3b13bc3c1

**Comment by kenygamer** [comment]
@95CivicSi Thanks, any link to the new version in order to test?
