### ISSUE TITLE
Parrot AI

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#235]
Can you add this https://github.com/BlockHorizons/ArtificialIntelligence to plugin ? @95CivicSi 

Sure, with permission of @Sandertv .

**Comment by 95CivicSi** [comment]
I'm checking on it.  Actually making a TODO list right now with "Add Parrots" as one the items on the list.

**Comment by NycuRO** [comment]
@95CivicSi Ok

**Comment by 95CivicSi** [comment]
Updates made today start the implentation of parrots.  You can get the current build here.

https://poggit.pmmp.io/r/13344/PureEntitiesX.phar

**Comment by 95CivicSi** [comment]
Updated Build that fixes Parrot related crashes is here:

https://poggit.pmmp.io/r/13349/PureEntitiesX_dev-138.phar
