### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by QuiverlyRivalry** [RevivalPMMP/PureEntitiesX#243]
- [ ] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

Hi,
As a feature I’d be thankful if there is a command like /disable radius 20 which disables animals spawning in a radius of 20 from the centre.
...

## Reproducing the issue
1. ...
2. ...

## Client information
PocketMine-MP Version: (insert commit hash here)
Plugin Version: (insert commit hash here)
PHP version: 7.0.14 (default)

## Optional information such as Client OS/Version What was happening when the error occured.
...

```
Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)
```

**Comment by jasonwynn10** [comment]
https://github.com/RevivalPMMP/PEXProtection
