### ISSUE TITLE
iProtector Support

### ISSUE THREAD

**Issue by JunkDaCoder** [RevivalPMMP/PureEntitiesX#25]
Is there anyway you can add support for iProtector so they cant spawn in certian areas?

**Comment by caspervanneck** [comment]
I dont think so

**Comment by Sandertv** [comment]
We'll work on that a bit latern

**Comment by Magicode1** [comment]
I think that might be an option in the near future, we just don't exactly know what we want to do with PureEntities yet (we got so much unexpected support, what do we do now? :) ) We may add an API or something for other plugins to hook into, once we finish fine tuning it. Just bare with us until we finish all the updates and Mobs :)

**Comment by Magicode1** [comment]
@JunkDaCoder , we are now working on an event called 'CreatureSpawnEvent' which can enable/disable spawning in certain areas.

**Comment by Sandertv** [comment]
We've finished a protection plugin just now. We've added the link in the README of this project. :)
