### ISSUE TITLE
plugins entity error

### ISSUE THREAD

**Issue by yunseo2723** [RevivalPMMP/PureEntitiesX#258]
I have summoned an animal with this plugin, and the entity that was summoned after a few days has disappeared. What should I do?
Below is the contents of the config file. Please let me know what you want to fix.
# Default Config File for PureEntitiesX

# set where entities can spawn ["world", "flat"], or leave empty to allow entities to spawn in any level
enabledworlds: []

# set how often the spawn and despawn task will be trigered
spawn-task:
  trigger-ticks: 300
  use-block-light: false
  use-sky-light: false

# after how many ticks an entity gets despawned (if not tamed)
despawn:
  after-ticks: 72000

# configuration of panic mode for some entities
panic:
  enabled: true
  ticks: 100 # how long is an entity in panic mode

# task definitions - to have full functionality, enable all!
tasks:
  spawn: false # set to true to enable spawn / unspawn tasks
  async: true # set to true for mob equipment working and relogging tamed entities working
  looking: true # set to true to enable entity interaction and enderman looking for detection e.g.

# when set to true the creeper will explode and also destroy blocks
creeper:
  block-breaking-explosion: false

breeding:
  emit-love-particles-constantly: true

# control logfile logging
# possible: debug, warn, info
# in production environment info info or warn should be set - otherwise it will take a lot of performance!
logfile:
  loglevel: info

# describes the distances that are used for specific actions
distances:
  interact: 3 # defines until which distance an interaction with an entity is possible
  find-partner: 49 # defines whe maximum distance when love mode is active and is searching for another partner
  tamed-teleport: 20 # defines how many blocks the player can move until the tamed entity teleports to it's owner (when not sitting)
  tamed-follow-player: 14 # define the distance between owner and tamed entity when it stops wandering around and get back to player

ticks:
  block-interest: 100 # define how many ticks pass by before

idle:
  chance: 80 # 20 percent of idle after walking around
  min-idle: 100 # minimum idle in ticks
  max-idle: 500 # max idle in ticks
  time-between-idle: 20 # time that has to pass at least between each idling status in seconds

xp:
  enabled: true # enable experience pickup system - disable if you have problems!

# control max spawning values ​​...
max-spawn:
  bat: 10
  chicken: 50
  cow: 50
  horse: 10 # also donkeys and so on ...
  ocelot: 10
  parrot: 10
  pig: 50
  rabbit: 10
  sheep: 10

  blaze: 10
  cavespider: 10
  creeper: 10
  enderman: 10
  ghast: 10
  irongolem: 10
  magmacube: 10
  pigzombie: 10
  skeleton: 10
  slime: 10
  spider: 10
  wolf: 10
  zombie: 10

# control spawn probability with each spawn run for each entity
# probability is configured as percent (20 means 20% chance of spawning)
probability:
  bat: 0
  chicken: 100
  cow: 100
  horse: 0
  ocelot: 0
  parrot: 0
  pig: 100
  rabbit: 0
  sheep: 0

  blaze: 0
  cavespider: 0
  creeper: 0
  enderman: 0
  ghast: 0
  irongolem: 0
  magmacube: 0
  pigzombie: 0
  skeleton: 0
  slime: 0
  spider: 0
  wolf: 0
  zombie: 0

# please only tune the following when you know what you're doing;)
performance:
  check-target-tick-skip: 5 #
  check-interactive-ticks: 10 # how often does the plugin check if an interactive button is displayed - the lesser the value the more performance is needed
  check-interactive-correction: true # setting this to true the interactive button finding a lot better but more unprecise and consumes more performance
  check-enderman-looking: 10 # how often does the plugin check if a player looks at an enderman
  check-pickup-loot: 10 # how often do entities look after things they can pick up (configure ticks between checks)
  enable-logging: false # enable file logging (set to false for productive environments)
  enable-nbt-storage: true # enable to store to NBT - this has to be set to true

# mob equipment configuration
mob-equipment:
  # each entity is configured here!
  zombie:
    # chances for pickup loot, wearing armor and weapon in percent for easy | normal | hard
    wear-pickup-chances:
      can-pickup-loot:
        easy: 0
        normal: 55
        hard: 75
      armor:
        easy: 0
        normal: 15
        hard: 20
      weapon:
        easy: 1
        normal: 10
        hard: 20
    # chances of different armor pieces, perplexy (easy | normal | hard)
    wear-chances:
      helmet:
        easy: 100
        normal: 100
        hard: 100
      helmet-chestplate:
        easy: 75
        normal: 75
        hard: 90
      helmet-chestplate-leggings:
        easy: 56
        normal: 56
        hard: 81
      full:
        easy: 42
        normal: 42
        hard: 73
    # chances of different armor pieces, perplexy
    armor-types:
      leather: 37
      gold: 48
      chain: 13 # not used yet
      iron: 2
      diamond: 1

**Comment by 95CivicSi** [comment]
Did not follow issue template.
