### ISSUE TITLE
Add Riding Feature to Horses, Llamas and Pigs

### ISSUE THREAD

**Issue by LagHD** [RevivalPMMP/PureEntitiesX#259]
We need Riding, it's been a long-wanted feature that we've still been patiently waiting for ._.

**Comment by 95CivicSi** [comment]
This feature is listed in the Bedrock TODO list.  

https://github.com/RevivalPMMP/PureEntitiesX/issues/236

**Comment by 95CivicSi** [comment]
Duplicate of https://github.com/RevivalPMMP/PureEntitiesX/issues/246

**Comment by 95CivicSi** [comment]
This will likely be added following the movement refactor and update to the AutoSpawnTask, however, I'm not going to guarantee an ETA.

**Comment by LagHD** [comment]
Kk thanks
