### ISSUE TITLE
 skeleton does not hold the bow

### ISSUE THREAD

**Issue by WaldoFS** [RevivalPMMP/PureEntitiesX#262]
## Required Information
  __PocketMine-MP Version:__ 1.7dev-581 3.0.0-ALPHA10
  __Plugin Version:__ 0.2.8-3.alpha10
  Where you got the plugin: poggit.pmmp.io
    
## Steps to reproduce the issue.
1.  spawn skeleton
...

**Comment by 95CivicSi** [comment]
This was already on the current TODO list ( #236 ) but I'll leave this open for tracking.

**Comment by 95CivicSi** [comment]
This appears to have been fixed with the updates to MobArmorInventoryPackets in PocketMine-MP 3.8.4
