### ISSUE TITLE
Entity is not registered

### ISSUE THREAD

**Issue by TheClimbing** [RevivalPMMP/PureEntitiesX#265]
This happend after I killed a spider and i think pick up the dropped items https://crash.pmmp.io/view/8940
Used Pocketmine-MP dev build #601
PHP 7.2.1
Android client

**Comment by TheClimbing** [comment]
With Build #602 is even worse the console gets spammed with errors

**Comment by 95CivicSi** [comment]
@TheClimbing, Please disable TeaSpoon and let me know if the problem is still present.

**Comment by jasonwynn10** [comment]
This is a known issue of the TeaSpoon plugin. It can only be resolved by deleting all entities in the world with an NBT editor.
