### ISSUE TITLE
Lag on server

### ISSUE THREAD

**Issue by llronaldoll** [RevivalPMMP/PureEntitiesX#267]
too lag on server when installing plugin 
pocketmine build 516

**Comment by 95CivicSi** [comment]
Please fill out the issue template.

**Comment by llronaldoll** [comment]
![image](https://user-images.githubusercontent.com/5334591/34911862-e15400d8-f8b9-11e7-92d9-f7e09bdc4284.png)


server lagging and spamming error on console

PocketminePE build 516 or 616 somo erro

**Comment by jasonwynn10** [comment]
duplicate of #266
