### ISSUE TITLE
How to install the plugin !! ? 

### ISSUE THREAD

**Issue by MrTa7** [RevivalPMMP/PureEntitiesX#279]
i have download it and i put the zip file in my server but it didn't work

my server is work with 3.00 Alpha 11

**Comment by MrTa7** [comment]
>

**Comment by jasonwynn10** [comment]
@95CivicSi I think this goes beyond just an unfilled template... 🤦‍♂️

**Comment by jasonwynn10** [comment]
@MrTa7 https://pmmp.readthedocs.io/en/rtfd/faq/plugins.html

**Comment by 95CivicSi** [comment]
The plugin has to be installed as a .phar.  You can get the 3.0.0-ALPHA11 release from https://poggit.pmmp.io/r/22748/PureEntitiesX_dev-218.phar

Put that file in your plugins folder and restart the server.
