### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by LagHD** [RevivalPMMP/PureEntitiesX#280]
## Mob AI is broke as off new pmmp Dev Build 731

**Comment by 95CivicSi** [comment]
Issue Template was not followed. Additionally, the README and Poggit release page both state that the release of PureEntitiesX for 3.0.0-ALPHA11 is targeted to work with PocketMine-MP Version: 1.7dev-698.  Any changes made in the core beyond that point are not supported.
