### ISSUE TITLE
Server Thread !

### ISSUE THREAD

**Issue by MrTa7** [RevivalPMMP/PureEntitiesX#281]
what is the problem of my console when i put this plugin ?

it's keep showing this message : |

17.02 12:08:21 [Server] Server thread/CRITICAL Could not tick level "world": Call to a member function getInLove() on null
17.02 12:08:21 [Server] Server thread/CRITICAL Error: "Call to a member function getInLove() on null" (EXCEPTION) in "PureEntitiesX_dev-220.phar/src/revivalpmmp/pureentities/components/IdlingComponent" at line 123
17.02 12:08:21 [Server] Server thread/DEBUG #0 PureEntitiesX_dev-220.phar/src/revivalpmmp/pureentities/entity/WalkingEntity(90): revivalpmmp\pureentities\components\IdlingComponent->checkAndSetIdling()
17.02 12:08:21 [Server] Server thread/DEBUG #1 PureEntitiesX_dev-220.phar/src/revivalpmmp/pureentities/entity/WalkingEntity(121): revivalpmmp\pureentities\entity\WalkingEntity->checkTarget()
17.02 12:08:21 [Server] Server thread/DEBUG #2 PureEntitiesX_dev-220.phar/src/revivalpmmp/pureentities/entity/animal/WalkingAnimal(107): revivalpmmp\pureentities\entity\WalkingEntity->updateMove(integer 1)
17.02 12:08:21 [Server] Server thread/DEBUG #3 src/pocketmine/level/Level(775): revivalpmmp\pureentities\entity\animal\WalkingAnimal->onUpdate(integer 5545)
17.02 12:08:21 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2394): pocketmine\level\Level->doTick(integer 5545)
17.02 12:08:21 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2551): pocketmine\Server->checkTickUpdates(integer 5545, double 1518865701.2172)
17.02 12:08:21 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2290): pocketmine\Server->tick()
17.02 12:08:21 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2163): pocketmine\Server->tickProcessor()
17.02 12:08:21 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1746): pocketmine\Server->start()
17.02 12:08:21 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(385): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
17.02 12:08:21 [Server] Server thread/DEBUG #10 /jar/PocketMine-MP.phar(1): require(string phar:///jar/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by 95CivicSi** [comment]
While the error messages are somewhat helpful, I can't do anything with them unless you fill out the issue template as I don't have the rest of what I need to figure out what is going on.  This is closed until the issues template is properly filled out.
