### ISSUE TITLE
PureEntitiesX_dev-220 bug

### ISSUE THREAD

**Issue by KenMizz** [RevivalPMMP/PureEntitiesX#282]
## Required Information
  __PocketMine-MP Version:__ 99ef3e6
  __Plugin Version:__ dev-220
  Where you got the plugin: https://poggit.pmmp.io/ci/RevivalPMMP/PureEntitiesX/PureEntitiesX

## Optional Information
  __PHP version:__ 7.2
  __Other Installed Plugins:__ Devtools
  __OS Version:__ Windows 10
    
    

## Steps to reproduce the issue.
1.  install plugin
2.  Enter world
...

## Description
 Call to member function getInLove() on null

![snipaste_2018-02-18_21-53-36](https://user-images.githubusercontent.com/16635884/36361054-00d82386-14f7-11e8-8cad-51d51733475e.png)
```

```

**Comment by 95CivicSi** [comment]
This problem is caused by an API change in PocketMine-MP that is not compatible with 3.0.0-ALPHA11.  The version of PureEntitiesX you are using is targeted to be compatible with PocketMine-MP 1.7-dev698 which can be found here:
https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-698

Please revert your PocketMine-MP core to that version and see if you still have this error.

**Comment by TDMidkwhatisxd** [comment]
PocketMine-MP Crash Dump Mon Feb 19 14:41:29 EET 2018

Error: Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported
File: vendor/pocketmine/pocketmine-nbt/src/tag/NoDynamicFieldsTrait
Line: 29
Type: notice

Code:
[20] */
[21] 
[22] declare(strict_types=1);
[23] 
[24] namespace pocketmine\nbt\tag;
[25] 
[26] trait NoDynamicFieldsTrait{
[27] 
[28] 	private function throw() : void{
[29] 		throw new \RuntimeException("Dynamic field access on " . \get_class($this) . " is no longer supported");
[30] 	}
[31] 
[32] 	public function __get($name){
[33] 		$this->throw();
[34] 	}
[35] 
[36] 	public function __set($name, $value){
[37] 		$this->throw();
[38] 	}
[39]

**Comment by TDMidkwhatisxd** [comment]
I'm done with this plugin

**Comment by 95CivicSi** [comment]
@TDMidkwhatisxd The error you posted has the same root issue as the original poster. You are using a bleeding edge version of PocketMine-MP.  The README for this Repository and the Poggit release page both declare that the current copy of this plugin is targeted to work with 1.7-dev698.  Have you tested this plugin with that version, or any of the other released version of 3.0.0-ALPHA11?

Released versions of PocketMine-MP can be found here:
https://github.com/pmmp/PocketMine-MP/releases

**Comment by TDMidkwhatisxd** [comment]
My bad I forgot to download the release ...

**Comment by TDMidkwhatisxd** [comment]
Ummm, even if I don't use bleeding edge, as you know earlier versions of PMMP crash due to XP glitch, it got fixed in latest version

**Comment by 95CivicSi** [comment]
I've been testing this against 1.7-dev743 since I posted my previous response and have had no errors so far.  If you get errors on that release, I'll fix them immediately.
