### ISSUE TITLE
CompoundTag is no longer supported

### ISSUE THREAD

**Issue by SuperKali** [RevivalPMMP/PureEntitiesX#284]
## Required Information
  __PocketMine-MP Version:__ https://github.com/pmmp/PocketMine-MP/commit/aa11dbb928f6a0f6e298876beab655c2634c9b91
  __Plugin Version:__ 3.0.0-ALPHA11
  Where you got the plugin: https://github.com/RevivalPMMP/PureEntitiesX/tree/OverhaulAutoSpawnTask/

## Optional Information
  __PHP version:__ 7.2
  __Other Installed Plugins:__  DevTool
  __OS Version:__ 1.2.10
    
    

## Steps to reproduce the issue.
1.  the mobs not working beacuse the console give me this error
...

## Description
  

```
22:08:00 CRITICAL > RuntimeException: "Dynamic field access on pocketmine\nbt\tag\CompoundTag is no longer supported" (EXCEPTION) in "vendor/pocketmine/pocketmine-nbt/src/tag/NoDynamicFieldsTrait" at line 29
```

**Comment by jasonwynn10** [comment]
The version of PocketMine you are using is unsupported. Please use the release version which this plugin in intended to be used for
