### ISSUE TITLE
Mob:  Pulled a Houdini 

### ISSUE THREAD

**Issue by ghost** [RevivalPMMP/PureEntitiesX#287]
__PocketMine-MP Version:__ (Release #743)
  __Plugin Version:__ (Dev Build #220)
  Where you got the plugin: (https://poggit.pmmp.io/p/PureEntitiesX/0.4.0)
    

After a fresh install,

Hitting any 'mobs' will cause them to fall 1-3 blocks in depth.
On a skyblock style server this is pretty problematic as it happens instantaneously as you make contact with the entity, causing the mob/entity to fall into the void.

**Comment by 95CivicSi** [comment]
Thanks for getting this filled out.  I'm currently working on this and other related mob movement issues.
