### ISSUE TITLE
Mobs sometimes don't die when supposed to

### ISSUE THREAD

**Issue by genboy** [RevivalPMMP/PureEntitiesX#289]
PocketMine-MP Version: Release #717 ALPHA11
Plugin Version: 0.4.0
Where you got the plugin: (https://poggit.pmmp.io/p/PureEntitiesX/0.4.0)

Installed Plugins:
Pocketmine Devtools, BigBrother, Festival, Worlds, PureEntitiesX, Colormatic, LiveXYZ, Texter, Treasure Chest, PurePerms, Parkour,Cameraman, ProfileUI, GrabBag, MOTDshuffle, EssentialsPe, Specter, AnyVersion, Blocksniper, Realtime, ClientConsole, ClearLag
    
Steps to reproduce the issue.
1.  Set time to day time, let the sun shine!
2.  Mobs wil catch fire but don't die untill I slay them.
[3.  Slay a creeper -  Explosion keeps going for a while ]  

Description
Mob damage/hurt/die seems instable. Player survival mode is unbarable when Mobs sometimes do not die. Most of the time Zombies keep burning untill I slay them,

  [Creepers keep exploding after a hit or 2 untill I call /peremove] 
With the latest fix b57939b creeper explodes a bit to quickly, but the explosion doesn't break the game anymore so thank you! 

@humeden [issue](https://github.com/RevivalPMMP/PureEntitiesX/issues/287) and 
@feikede [issue](https://github.com/RevivalPMMP/PureEntitiesX/issues/252) do have something in common i think, something with the mob resetting it's own life/status/position or reacting to slow before life/status/pos reset (or something :).

There are no error logs going out from this, problem is player survival mode is unbarable with creepers keeping exploding - I've seen the Todolist and just wanted to add this as an important note.

Thank you for the life PureEntitiesX brings to my server!

**Comment by 95CivicSi** [comment]
The problems with creepers are fixed in this update:

https://poggit.pmmp.io/r/24576/PureEntitiesX_dev-223.phar

Hopefully I'll get the mobs on fire fixed soon.

**Comment by genboy** [comment]
i think i noticed the improvements in a short testrun, nice! 
Will test it some more, hope i can help someday, good luck with the mobs!

**Comment by genboy** [comment]
Working great! 
Other anomalies are probably related with other issues like https://github.com/RevivalPMMP/PureEntitiesX/issues/252#issuecomment-371137755

**Comment by ZandercraftGames** [comment]
Mobs also sometimes die when they arent supposed to.

**Comment by 95CivicSi** [comment]
As of version 0.6.5, this problem seems to be resolved.  Any future issues of similar nature should be reported in a new issue please.
