### ISSUE TITLE
move

### ISSUE THREAD

**Issue by majovec** [RevivalPMMP/PureEntitiesX#292]
17:30:43 CRITICAL > ErrorException: "Declaration of revivalpmmp\pureentities\entity\BaseEntity::updateMovement() should be compatible with pocketmine\entity\Entity::updateMovement(bool $teleport = false)" (EXCEPTION) in "plugins/PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity" at line 521

**Comment by BI0MER** [comment]
Compatible PocketMine-MP Version: 1.7dev-743 https://github.com/pmmp/PocketMine-MP/releases/tag/1.7dev-743
