### ISSUE TITLE
BlockBreakEvent Crashes server

### ISSUE THREAD

**Issue by Magicode1** [RevivalPMMP/PureEntitiesX#3]
The `BlockBreakEvent` will sometimes throw fatal errors on the server. It's pretty much in danger of crashing whenever someone breaks a block.

That may be a tiny problem :-1:

**Comment by Sandertv** [comment]
What are the errors that show up?

**Comment by Magicode1** [comment]
I will copy it when I get home. I cant really test it on my laptop at school 😋

**Comment by Sandertv** [comment]
Same :P

**Comment by Sandertv** [comment]
Okay I assume it is the last couple lines of code that error the server, because like you said they only show up sometimes and it has the mt_rand(1, 9) thing.

**Comment by Magicode1** [comment]
Yeah, that would explain it

**Comment by Sandertv** [comment]
Does this still happen?

**Comment by Magicode1** [comment]
Nope! I think it had something to do with the Silverfish. I still need to take the Spawning waaaaay down

They spawn like every 3 blocks! :)

**Comment by Sandertv** [comment]
Yeah it's still kinda insane how often they spawn :P

**Comment by Magicode1** [comment]
Yeah, I enabled the plugin on my private server, and I instantly got player complaints about dying from massive silverfish spawns

**Comment by Magicode1** [comment]
Is it really necessary to have them spawn at all?

**Comment by Sandertv** [comment]
Maybe make them only spawn on depths with very low Y?

**Comment by Magicode1** [comment]
Yeah, that would probably be optimal

**Comment by Sandertv** [comment]
Closing the issue as it is fixed, I like having a clean issues tab :P xD
