### ISSUE TITLE
It crashes the server

### ISSUE THREAD

**Issue by EpicPinkCreeper** [RevivalPMMP/PureEntitiesX#308]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ (insert commit hash or version number here)
1.7dev-963
  __Plugin Version:__ (insert commit hash or version number here)
dev # 243
  Where you got the plugin: (url where the plugin was downloaded from.)
poggit

## Optional Information
  __PHP version:__ 
  __Other Installed Plugins:__ 
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  go on server
2.  walk around a bit
3. it crashes
...

## Description
  

```

Fatal error: Class 'pocketmine\level\generator\biome\Biome' not found in phar://C:/Users/epicp/Downloads/MCPE SERVERS/PocketMine-MP whitelisted survival/plugins/PureEntitiesX_dev-243.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask.php on line 308
[12:18:04] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[12:18:04] [Server thread/EMERGENCY]: Please upload the "C:\Users\epicp\Downloads\MCPE SERVERS\PocketMine-MP whitelisted survival\crashdumps/Wed_May_9-12.18.04-CDT_2018.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[12:18:06] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on http://crash.pocketmine.net/view/29503469 or use the ID #29503469.


```

**Comment by Ellf** [comment]
Just for your information, I'm also getting this error on PocketMine-MP 1.2 API 3.0.0 Alpha 11.

[Fri_May_11-13.49.28-UTC_2018.log](https://github.com/RevivalPMMP/PureEntitiesX/files/1995558/Fri_May_11-13.49.28-UTC_2018.log)

**Comment by 95CivicSi** [comment]
Your crash dump is using 
```PocketMine-MP version: 1.7dev #985 [Protocol 223; API 3.0.0-ALPHA12]```

The problem here is that the versions of PocketMine-MP that you are using, are not released versions. Currently, PureEntitiesX is compatible with the most recent release.  Released versions of PocketMine-MP can be found here:

https://github.com/pmmp/PocketMine-MP/releases

**Comment by Ellf** [comment]
Thank you for the reply @95CivicSi, seems my server hosting company is using the newest autoupdated build but doesn't give the option to roll back to the previous version. I'll contact them and ask them to use the release built for my custom jar.

**Comment by theoriginalspre** [comment]
problem with rolling back server versions, is they are not compatible with 1.4.0, and once mpce auto updates to 1.4.0 there is no way to roll that back. so if your version is 1.4.0 there will be no mobs in pocketmine until pure entities is updated. I have thoroughly tested this. 1.4.0 will not load 1.7dev-937, instead closes with a server outdated error. 1.4.0 requires pocketmine 1.7dev-1001. of course, the fact that pocketmine has been around this long and cannot natively spawn mobs without your plugin is concerning.

**Comment by CaptainDuck** [comment]
I've found a fix for this, just set the spawn task to 'false'

See here:
https://github.com/RevivalPMMP/PureEntitiesX/blob/master/resources/config.yml#L23
