### ISSUE TITLE
Enabling sheap shearing

### ISSUE THREAD

**Issue by tjespe** [RevivalPMMP/PureEntitiesX#31]
I see that there is an open issue about taming wolfs and I guess this is kind of the same. Anyway it would be really great if you made it possible to shear sheep.

**Comment by Sandertv** [comment]
As soon as entity jumping is fixed, we'll see if we can do anything about it! :)

**Comment by tjespe** [comment]
Sounds great!

**Comment by Sandertv** [comment]
I thought I'd just mention it. I've been working on shearing sheep and it works. Well, sort of. Currently just the shear button shows up whenever you look at any entity. Expect it to be fixed soon :)
