### ISSUE TITLE
There are no animals :/ Just creepers and zombies and skeletons. I have not changed anything anywhere. Vanilla PMMP install version 1.7dev with pureentitiesx

### ISSUE THREAD

**Issue by joshuagilmet** [RevivalPMMP/PureEntitiesX#314]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ (insert commit hash or version number here)
  __Plugin Version:__ (insert commit hash or version number here)
  Where you got the plugin: (url where the plugin was downloaded from.)

## Optional Information
  __PHP version:__ 7.2
  __Other Installed Plugins:__ just Pure
  __OS Version:__ Ubuntu server 16.0.4
    
    

## Steps to reproduce the issue.
1.  ./start.sh
2.  
...

## Description
  

```

Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)

```

**Comment by 95CivicSi** [comment]
Please fill out the missing information in the original post.
