### ISSUE TITLE
 Please fix the error.

### ISSUE THREAD

**Issue by yunseo2723** [RevivalPMMP/PureEntitiesX#316]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ (insert commit hash or version number here) 3.0.4
  __Plugin Version:__ (insert commit hash or version number here) PureEntityX v0.5.0 (
Latest version downloaded on July 4)
  Where you got the plugin: (url where the plugin was downloaded from.)

## Optional Information
  __PHP version:__ 7.2
  __Other Installed Plugins:__ 
  __OS Version:__Linux
    
   
I get the following error.
<img width="956" alt="32" src="https://user-images.githubusercontent.com/25340054/42259784-e26fd978-7f9c-11e8-94a0-c3e0bc9a6d31.PNG">

**Comment by 95CivicSi** [comment]
Are you running the plugin from source?
