### ISSUE TITLE
Best config to decrease lagging

### ISSUE THREAD

**Issue by CuongVnZ** [RevivalPMMP/PureEntitiesX#323]
It's not an error but i seem that PureEntitiesX is the big lag cause of my server
My timings : https://timings.pmmp.io/?id=27
So show me how to config pureentitiesx to decrease lag?
thanks

**Comment by 95CivicSi** [comment]
Part of this is an internal issue which we are working to resolve.  The next release for PureEntitiesX will have better response to the config file to help server owners reduce complications.
