### ISSUE TITLE
Can not hurt zombie, skeleton by hit its head

### ISSUE THREAD

**Issue by CuongVnZ** [RevivalPMMP/PureEntitiesX#325]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version: lastest
  __Plugin Version: lastest

## Optional Information
  __PHP version:__ 7.2
  __Other Installed Plugins:__ only pex
  __OS Version:__ win sv 2012
    
    

## Steps to reproduce the issue.
1.  hit into the HEAD.
2.  
...

## Description
  Zombies and skeleton can not be hurted when i hit into its head
When i set the nametag to zombies or skeleton, the name tag show between head and body ( http://imgur.com/KuGBS66 )

```

Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)

```

**Comment by 95CivicSi** [comment]
Fixed in https://github.com/RevivalPMMP/PureEntitiesX/commit/fddd075938321e7679cade15b57dbf14bd19aa01
