### ISSUE TITLE
[RFC] Removal of the PureEntitiesX Logger

### ISSUE THREAD

**Issue by jasonwynn10** [RevivalPMMP/PureEntitiesX#328]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
The PureEntitiesX Custom Logger was originally created by @kniffo80 44ed56ed4da209d9cfaa7ec1e310715434e1c31b to reduce console spam(or so I believe). The logger itself was overkill, so I reduced the lag caused by it with threaded logging f63cbfe0146d15cf8ac9041388f6c049a500140b , but it still causes much lag on the server. One server log is good enough and reduces the difficulty of debugging problems for server admins by having all the information in one location rather than in seperate logs.

## Benefits
- Less Lag
- Easier problem-solving

## Costs
- console spam when debug enabled

**Comment by 95CivicSi** [comment]
Are you setting up a PR for this or do you want me to handle it @jasonwynn10 ?

**Comment by jasonwynn10** [comment]
I'll make the PR when I get all the changes compiled

**Comment by ZandercraftGames** [comment]
The "Skipping World" console logging mechanism is also annoying...

**Comment by jasonwynn10** [comment]
> The "Skipping World" console logging mechanism is also annoying...

That's a part of the Server software. We cannot control that.

**Comment by ZandercraftGames** [comment]
@jasonwynn10 How so? Its prefix is of PureEntitesX and also it says its skipping putting entities in that world. That doesnt seem to be a natural part of Pocketmine.

**Comment by ZandercraftGames** [comment]
@jasonwynn10 Or at least add an option in the config to disable this or minimize the console logging of irrelevant and annoying things.
