### ISSUE TITLE
Actually it's a purpose.

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#332]
So it's not needed a Issue Template.

Can you make ticking movement in other thread and loading entities / tiles too? I mean, 1 thread for ticking movement ,  1 thread for loading entities / tiles.

An extension for pmmp actually for loading entities / tiles. 

Just for make better.

**Comment by 95CivicSi** [comment]
I'll see what I can do,

**Comment by NycuRO** [comment]
k, but do fast, bcs is easy

**Comment by NycuRO** [comment]
@95CivicSi Anything?

**Comment by 95CivicSi** [comment]
Haven't had time to work on this yet.

**Comment by jasonwynn10** [comment]
Threading would actually make the plugin function slower due to serialization latency between threads. It's not really recommended unless you have a thread-blocking task like waiting for a reply from a remote website

**Comment by NycuRO** [comment]
@jasonwynn10 TheMapModder explained much thing about Asyncronised and Threaded things in them Issue on pmmp.

I think this will be ok if fiber know how to do it.

**Comment by jasonwynn10** [comment]
https://github.com/SOF3/forums-common-sense/wiki/PocketMine-Plugin-Development-FAQ#what-is-threading-does-it-make-the-server-faster

**Comment by 95CivicSi** [comment]
After some significant review on this, I feel like @jasonwynn10 is correct.  Trying to run these tasks on separate threads is probably not best given the current state of PureEntitiesX or PocketMine-MP and how php and pthreads work.  I will reconsider this in the future if there are significant changes to php or pthreads.
