### ISSUE TITLE
Working Horses

### ISSUE THREAD

**Issue by CupidonSauce173** [RevivalPMMP/PureEntitiesX#333]
It's more a features request...
Can you make the horses so we can ride them ?

**Comment by Katana-Steel** [comment]
duplicate of #246

**Comment by CupidonSauce173** [comment]
So it won't happen?

**Comment by jasonwynn10** [comment]
Unfortunately, the development time it takes for a new feature to be added is extremely long. I wouldn't get your hopes up.

Closing as duplicate #246
