### ISSUE TITLE
Crash when booting server

### ISSUE THREAD

**Issue by FaanMaario** [RevivalPMMP/PureEntitiesX#337]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:_3.6.0_ (insert commit hash or version number here)
  __Plugin Version:_0.6.0_ (insert commit hash or version number here)
  Where you got the plugin: https://poggit.pmmp.io/p/PureEntitiesX/0.6.0 (url where the plugin was downloaded from.)

## Optional Information
  __PHP version:_7.2_ 
  __Other Installed Plugins:_KitUI 1.3.2 by Infernus101 for API(s) 3.0.0
PiggyCustomEnchants 1.4.2 by DaPigGuy for API(s) 3.2.0
MagicWE2 5.7.2 by XenialDan for API(s) 3.0.0
iProtector 3.1.1 by LDX for API(s) 3.0.0
MCPEToDiscord 1.4 by Jackthehaxk21 for API(s) 3.0.0, 3.1.1
AntiToolbox 1.0 by FaigerSYS for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0, 4.0.0
BlocksConverter 1 by matcracker for API(s) 3.0.0
BlazinFly 1.8.6 by iiFlamiinBlaze for API(s) 3.0.0
Lullaby 2.2.1 by PresentKim for API(s) 3.0.0, 4.0.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
MysteryCrate 8.0.1 by JackMD, DaPigGuy for API(s) 3.0.0
InvSee 0.0.1 by BlockHorizons for API(s) 3.0.0
ScoreHud 3.0.0 by JackMD for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
CustomAlerts 2.1 by EvolSoft for API(s) 3.0.0
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
MSpawns 2.2 by EvolSoft for API(s) 3.0.0
DevTools 1.13.0 by PocketMine Team for API(s) 3.0.0
KDR 1.0.0 by JackMD for API(s) 3.0.0
essentialsTP 1.2.1 by  for API(s) 3.0.0
SignEdit 1.4.5 by OtorisanVardo for API(s) 3.0.0
TeaSpoon 1.0.1 by CortexPE for API(s) 3.5.1
Slapper 1.4.2 by jojoe77777 for API(s) 3.1.0
ManyWorlds 2.2.0 by aliuly for API(s) 3.0.0
PortalsPE 1.1.1 by luca28pet for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
PureEntitiesX 0.6.0 by milk0417, RevivalPMMP for API(s) 3.0.0
PlayerInfo 2.0.3 by Matthww for API(s) 3.0.0
KillMoney 1.0.0-beta by kenygamer for API(s) 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
BlockSniper 3.2.3 by BlockHorizons, Sandertv (@Sandertv), Chris-Prime (@PrimusLV) for API(s) 3.2.0
Texter 3.0.6 by yuko_fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421 for API(s) 3.0.0
BetterVoting 1.0.2 by Twisted for API(s) 3.2.0
TradeUI 1.3 by xBeastMode for API(s) 3.0.0, 4.0.0
JoinUI 0.1 by  for API(s) 3.0.0, 3.0.2, 4.0.0
Cameraman 1.1.1 by ChalkPE for API(s) 3.0.0
CustomShopUI 3.0.0 by TinyPixelDevz for API(s) 3.3.2
AutoClearLagg 2.0.0 by Potatoe for API(s) 3.0.0
UnclaimFinder 0.1 by Ayzrix for API(s) 3.0.0
SlapperRotation 1.2.1 by jojoe77777 for API(s) 3.0.0
BlazinJoin 1.1.5 by iiFlamiinBlaze for API(s) 3.0.0
LiveXYZ 0.7.0 by dktapps for API(s) 3.0.0
CustomFeed 1.0.0 by xZolpha for API(s) 3.0.0, 4.0.0
CombatLogger 0.0.6 by Jack Noordhuis for API(s) 3.0.0
TempBanUI 1.9 by SonsaYT for API(s) 3.0.0, 4.0.0
NoVoid 1.0.0 by BlazeTheDev for API(s) 3.0.0
SoupFFA 1.0.0 by Jackaboi for API(s) 3.4.1
SkyBlock 2.2.7 by GiantQuartz for API(s) 3.0.0
SuperVanish 2.2 by ErkamKahriman for API(s) 3.0.0
TapToDo 2.3.0 by georgianYT for API(s) 3.0.0
Capes 1.1.0 by Unickorn for API(s) 3.0.0, 3.0.0-ALPHA12, 4.0.0
CommandShop 1.0.0 by BoxOfDevs Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0
Repair 1.0.1 by JackMD for API(s) 3.0.0
TopVoter 3.1.0 by SalmonDE for API(s) 3.0.0
x 1.0.0 by tim03we for API(s) 3.0.0
AutoInv 0.0.10 by JackNoordhuis for API(s) 3.0.0
MobStacker 1.1.8 by TheWalker0 for API(s) 3.0.0, 4.0.0
FactionsPro 2.1.4-t1 by Tethered_, edited by VMPE Development Team for API(s) 3.0.0_ 
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  
2.  
...

## Description
  
When I install the plugin, server crashes immediatly.

```

Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)

``PocketMine-MP Crash Dump Fri Feb 8 01:41:16 CET 2019

Error: Call to undefined method revivalpmmp\pureentities\entity\monster\walking\PigZombie::isAngry()
File: plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/WalkingEntity
Line: 67
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PureEntitiesX v0.6.0

Code:

Backtrace:
#0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(94): revivalpmmp\pureentities\entity\WalkingEntity->checkTarget(boolean )
#1 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/WalkingEntity(121): revivalpmmp\pureentities\entity\monster\WalkingMonster->checkTarget()
#2 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(183): revivalpmmp\pureentities\entity\WalkingEntity->updateMove(integer 1)
#3 src/pocketmine/level/Level(840): revivalpmmp\pureentities\entity\monster\WalkingMonster->onUpdate(integer 845)
#4 src/pocketmine/level/Level(785): pocketmine\level\Level->actuallyDoTick(integer 845)
#5 src/pocketmine/Server(2451): pocketmine\level\Level->doTick(integer 845)
#6 src/pocketmine/Server(2598): pocketmine\Server->checkTickUpdates(integer 845, double 1549586476.245)
#7 src/pocketmine/Server(2346): pocketmine\Server->tick()
#8 src/pocketmine/Server(2209): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1785): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/leo/factionbe/, string /home/leo/factionbe/plugins/)
#11 (1): require(string phar:///home/leo/factionbe/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.6.0 [Protocol 332]
Git commit: 02a6ca84a912f768481191522a0ec6866e10ad5d
uname -a: Linux FactionBE 3.10.0-862.11.6.vz7.71.8 #1 SMP Fri Aug 31 18:21:42 MSK 2018 x86_64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : Linux, linux``

**Comment by 95CivicSi** [comment]
Source cause https://github.com/RevivalPMMP/PureEntitiesX/commit/95b0157e8f1bddcb292fa26cace029c84cacce2a#diff-cde2bf816671308201dba3728df526b2


Note to self:
A great example of why you shouldn't do batch updates.
