### ISSUE TITLE
Not a bug but a suggestion

### ISSUE THREAD

**Issue by provsnoobgaming** [RevivalPMMP/PureEntitiesX#339]
i hope when configuring the plugin there is a way to deselect a world example of you have a skyblock server but you can't let the mob spawn at the spawn but at the island i don't think that we can do that maybe you can config at the worlds [-spawn] so it will not spawn at the world spawn

**Comment by 95CivicSi** [comment]
This is currently handled through another plugin.

https://github.com/RevivalPMMP/PEXProtection
