### ISSUE TITLE
Tamed crash

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [RevivalPMMP/PureEntitiesX#343]
If someone teleport with /home to another world and have a tamed wolf, sv crash.
Dont have the crashdump because i removed all and removed the plugin too, just now a player told me , how he crashed sv several times by  mistake.

U can close the issue, i told u just  to help.

**Comment by 95CivicSi** [comment]
Do you know what version of PM?

**Comment by TDMidkwhatisxd** [comment]
Latest artifact

**Comment by ZandercraftGames** [comment]
This happens on my server whenever someone even tries to tame anything. But it doesnt crash the server, only kicks the user for an Internal Server Error.

**Comment by 95CivicSi** [comment]
@ZandercraftGames if you can provide the logs or error info from the logs where this happens, it would be helpful.

**Comment by 95CivicSi** [comment]
I don't have enough information to troubleshoot this problem.
