### ISSUE TITLE
Plugin crash

### ISSUE THREAD

**Issue by Diamond946** [RevivalPMMP/PureEntitiesX#344]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version: 3.8.4
  __Plugin Version: 0.6.0
  Where you got the plugin: https://poggit.pmmp.io/p/PureEntitiesX

## Optional Information
  __PHP version: *
  __Other Installed Plugins: StairSeat v1.3.0, Slapper v1.4.3, ItemCloud v1.3.1, EconomyAPI v5.7.2, EconomyShop v2.0.10, EasyHomes v1.0.2, SignEdit v1.4.6, PlayerHead v1.0, KeepInventory v1.0, PureEntitiesX v0.6.0, EconomySell v2.0.10, EconomyPShop v2.0.3, AllSigns v1.0.11, EasyTeleporter v1.1.0, VanillaCoordinates v1.0.0, SimpleWarp v4.0.1
  __OS Version: *
    
    

## Steps to reproduce the issue.
1.  
2.  
...

## Description
  

```

2019-06-14 [15:24:44] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\MobArmorEquipmentPacket::$slots" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 164

```

**Comment by Diamond946** [comment]
But it's still make my server crashed :(

**Comment by 95CivicSi** [comment]
I need the crash dump file that is associated with this.

**Comment by Diamond946** [comment]
How to send the crash dump?

**Comment by Diamond946** [comment]
Please help me with this :(

**Comment by 95CivicSi** [comment]
You can download and test the updated version that fixes this problem from Poggit:

https://poggit.pmmp.io/r/60398/PureEntitiesX_dev-293.phar

**Comment by Diamond946** [comment]
Can you please give me the plugin page link, not the download it self?

Pada tanggal Min, 16 Jun 2019 13.57, Aaron Salyer <notifications@github.com>
menulis:
