### ISSUE TITLE
error directly 

### ISSUE THREAD

**Issue by JesusDesmadres** [RevivalPMMP/PureEntitiesX#349]
pocketmine 3.8.5
error: https://crash.pmmp.io/view/2548972

**Comment by 95CivicSi** [comment]
What were you doing when this happened?

**Comment by JesusDesmadres** [comment]
I just went in and put a villager

**Comment by JesusDesmadres** [comment]
in a spawn and then he's going to put a cow and crashes

**Comment by DenielWorld** [comment]
#335

**Comment by TDMidkwhatisxd** [comment]
He used or use teaspoon, tested on my sv and had to replace all mobspawners while constantly crashing my sv. xd

**Comment by 95CivicSi** [comment]
I am finding the same issue that TDMidkwhatisxd mentioned.  This is probably due to incompatibility with TeaSpoon versions of MobSpawners.
