### ISSUE TITLE
Sheep despawn instead of dying when killed

### ISSUE THREAD

**Issue by tjespe** [RevivalPMMP/PureEntitiesX#35]
For some reason, sheep just despawn instead of dying. At least they do on my server. Instead of the death animation and item dropping they just freeze and then despawn a moment later. This makes it impossible for the players to get any wool, becuase sheering isn't implemented yet.

I don't know if this is a bug I have or if it's a bug with the plugin.

I thought correcting the Item::get() call on line 37 of Sheep.php would fix it, but it didn't. Anyway, I think that line is supposed to be:
`return [Item::get(Item::WHITE_WOOL, 0, 1)];`
instead of
`return [Item::get(Item::WHITE_WOOL, 1)];`

**Comment by Sandertv** [comment]
Yep I've noticed that too. I'll look into it :)

**Comment by tjespe** [comment]
The exact same issue seems to be the case for endermen as well

**Comment by Sandertv** [comment]
Yep, found that out too.

**Comment by Sandertv** [comment]
👍
