### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dapwestwood** [RevivalPMMP/PureEntitiesX#352]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ (insert commit hash or version number here)
  __Plugin Version:__ (insert commit hash or version number here)
  Where you got the plugin: (url where the plugin was downloaded from.)

## Optional Information
  __PHP version:__ 
  __Other Installed Plugins:__ 
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  
2.  
...

## Description
  

```

Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)

```

![Screenshot_20190722-133037](https://user-images.githubusercontent.com/32587372/61643328-cf231700-accc-11e9-9c3f-3b8f3f7e5b56.png)
Its was cool plugins, but the plugins always make my server due to on the pureentitiesx plugins can u fix this please?? Thank you...

**Comment by 95CivicSi** [comment]
Fill out the missing items.  I cannot help without knowing that information.
