### ISSUE TITLE
Mobs can't jump!

### ISSUE THREAD

**Issue by kpietsch70** [RevivalPMMP/PureEntitiesX#358]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
 If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".
 
 ## Required Information
 **PocketMine-MP Version:** 3.9.3
 **Plugin Version:** 0.6.3
Where you got the plugin: https://poggit.pmmp.io/p/PureEntitiesX/0.6.3
 
 ## Optional Information
 **PHP version:**
 **Other Installed Plugins:**
 **OS Version:** Windows 10
 
 ## Steps to reproduce the issue.

 
 ...
 
 ## Description
 Mobs can't jump. They try and fail.
 
 ```

**Comment by MCCStudios** [comment]
Also, when mobs are submerged in water, they keep floating and jumping, they dont move or swim along with the flow of water

**Comment by 95CivicSi** [comment]
Jumping problems fixed in https://github.com/RevivalPMMP/PureEntitiesX/commit/f85a659901564620b88ac0db0b59f2537a210f38
