### ISSUE TITLE
Monsters burn at too low light levels

### ISSUE THREAD

**Issue by tjespe** [RevivalPMMP/PureEntitiesX#36]
Skeletons and Zombies burn to death even though it's very dark.

**Comment by Sandertv** [comment]
Probably relates to #33

**Comment by tjespe** [comment]
Yes probably

**Comment by tjespe** [comment]
I see that the burning criteria is not based on light around the entity but on the server time. It probably shouldn't be like this, but as of now I believe it's easy to fix the issue by changing lines 71-77 in Zombie.php to this:
`$time = $this->getLevel()->getTime() % 24000;`
`        if(`
           ` !$this->isOnFire()`
            `&& ($time > 12000)`
       ` ){`
           ` $this->setOnFire(100);`
        `}`

The internal clock in Minecraft has 24000 ticks each day and starts at 6 am (sunrise)

**Comment by Sandertv** [comment]
We currently can not use light as it's simply not properly implemented in PocketMine.

**Comment by Magicode1** [comment]
Yes, checking for block light is not implemented in PMMP, so we need to go off of the time. As soon as PMMP implements Block Light, we can get this working asap.

**Comment by Sandertv** [comment]
Yep, @jasonwynn10 is correct.

**Comment by jasonwynn10** [comment]
I just realised that this is a duplicated issue #33
