### ISSUE TITLE
Mobs suicide them selves

### ISSUE THREAD

**Issue by Invy55** [RevivalPMMP/PureEntitiesX#364]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__  3.11.3 for Minecraft: Bedrock Edition v1.14.0 (protocol version 389)
  __Plugin Version:__  PureEntitiesX v0.6.4 (Dev #304)
  Where you got the plugin: https://poggit.pmmp.io/r/70579/PureEntitiesX_dev-304.phar

## Optional Information
  __PHP version:__ PHP 7.3.11-1~deb10u1
  __Other Installed Plugins:__ MultiWorld v1.5.2, Slapper v1.5.2, Alias v1.2.3, BuilderTools v1.2.0-beta2, VanishV2 v1.3, StairSeat v1.4.0, InvSee v1.0.0, PurePerms v1.4.3, BlazinFly v1.8.7, DevTools v1.13.5, SizePlayer v1.1.0, FormAPI v1.3.0, MapImageEngine v1.1.3, PureChat v1.4.11, StaffTools v1.0.0, RedstoneCircuit v1.0.1, iProtector v3.1.1, MIE_Converter v1.0.2, NoStarving v0.0.1, SlapperRotation v1.2.1, Banner v0.0.1, SlapperCache v2.0.1, SlashSkin v1.0.0, VoidTP v1.0.2, pluginp v1.1.0
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  Create a platform in the sky
2.  Spawn an entity like a horse
...

## Description
  Every time I spawn an entity on a platform in middle air it kills its self by falling down 

```

Replace this text with console / error logs or crash dumps. (Do not remove the triple backticks above and below this.)

```

**Comment by Adam1609** [comment]
The calculation of mobs isn't always like vanilla. For example, if you have a Skyblock server, and monster appeared in your island, they will fall.

**Comment by Invy55** [comment]
> The calculation of mobs isn't always like vanilla. For example, if you have a Skyblock server, and monster appeared in your island, they will fall.

oh

**Comment by 95CivicSi** [comment]
Currently, I am unable to reproduce this with version 0.6.5.  This may be a performance related issue as movement calculations are known to have problems when the server is heavily loaded.  Will re-open or create a new issue if the problem arises again.
