### ISSUE TITLE
Server Crash 🤔

### ISSUE THREAD

**Issue by usser1976** [RevivalPMMP/PureEntitiesX#366]
PocketMine-MP Crash Dump Mon Jan 27 21:56:02 CET 2020

Error: Return value of revivalpmmp\pureentities\entity\monster\walking\Wolf::getPositionNearOwner() must be an instance of pocketmine\math\Vector3, null returned
File: plugins/PureEntitiesX_dev-302.phar/src/revivalpmmp/pureentities/traits/Tameable
Line: 192
Type: TypeError

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PureEntitiesX v0.6.4

Code:

Backtrace:
#0 plugins/PureEntitiesX_dev-302.phar/src/revivalpmmp/pureentities/entity/monster/walking/Wolf(353): revivalpmmp\pureentities\entity\monster\walking\Wolf->getPositionNearOwner(object pocketmine\Player, object revivalpmmp\pureentities\entity\monster\walking\Wolf)
#1 plugins/PureEntitiesX_dev-302.phar/src/revivalpmmp/pureentities/entity/monster/walking/Wolf(131): revivalpmmp\pureentities\entity\monster\walking\Wolf->checkFollowOwner()
#2 plugins/PureEntitiesX_dev-302.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(181): revivalpmmp\pureentities\entity\monster\walking\Wolf->entityBaseTick(integer 1)
#3 src/pocketmine/level/Level(904): revivalpmmp\pureentities\entity\monster\WalkingMonster->onUpdate(integer 1209155)
#4 src/pocketmine/level/Level(837): pocketmine\level\Level->actuallyDoTick(integer 1209155)
#5 src/pocketmine/Server(2536): pocketmine\level\Level->doTick(integer 1209155)
#6 src/pocketmine/Server(2677): pocketmine\Server->checkTickUpdates(integer 1209155, double 1580158562.4687)
#7 src/pocketmine/Server(2403): pocketmine\Server->tick()
#8 src/pocketmine/Server(2250): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1811): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#11 src/pocketmine/PocketMine(297): pocketmine\server()
#12 (1): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.11.4 [Protocol 389]
Git commit: 13f28d8454fc499e1869190ccbbad077bff5853f
uname -a: Linux cc4813cff81e 5.2.0-0.bpo.3-amd64 #1 SMP Debian 5.2.17-1~bpo10+1 (2019-09-30) x86_64
PHP Version: 7.3.6
Zend version: 3.3.6
OS : Linux, linux

**Comment by 95CivicSi** [comment]
You're using an unreleased version of PureEntitiesX. The supported version can be obtained from Poggit:

https://poggit.pmmp.io/p/PureEntitiesX
