### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by supercrafti** [RevivalPMMP/PureEntitiesX#367]
PocketMine-MP Crash Dump Tue Feb 4 16:45:19 CET 2020

Error: Return value of pocketmine\entity\Living::getArmorInventory() must be an instance of pocketmine\inventory\ArmorInventory, null returned
File: src/pocketmine/entity/Living
Line: 452
Type: TypeError

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PureEntitiesX v0.6.3

Code:

Backtrace:
#0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/utils/MobDamageCalculator(83): pocketmine\entity\Living->getArmorInventory()
#1 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Zombie(141): revivalpmmp\pureentities\utils\MobDamageCalculator::calculateFinalDamage(object JackMD\NameSpaceRemover\CustomPlayer, double 2)
#2 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(72): revivalpmmp\pureentities\entity\monster\walking\Zombie->attackEntity(object JackMD\NameSpaceRemover\CustomPlayer)
#3 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(198): revivalpmmp\pureentities\entity\monster\WalkingMonster->checkAndAttackEntity(object JackMD\NameSpaceRemover\CustomPlayer)
#4 src/pocketmine/level/Level(904): revivalpmmp\pureentities\entity\monster\WalkingMonster->onUpdate(integer 76161)
#5 src/pocketmine/level/Level(837): pocketmine\level\Level->actuallyDoTick(integer 76161)
#6 src/pocketmine/Server(2536): pocketmine\level\Level->doTick(integer 76161)
#7 src/pocketmine/Server(2677): pocketmine\Server->checkTickUpdates(integer 76161, double 1580831119.6955)
#8 src/pocketmine/Server(2403): pocketmine\Server->tick()
#9 src/pocketmine/Server(2250): pocketmine\Server->tickProcessor()
#10 src/pocketmine/Server(1811): pocketmine\Server->start()
#11 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#12 src/pocketmine/PocketMine(297): pocketmine\server()
#13 (1): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.11.4 [Protocol 389]
Git commit: 13f28d8454fc499e1869190ccbbad077bff5853f
uname -a: Linux 10c6b4ee64c8 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64
PHP Version: 7.3.6
Zend version: 3.3.6
OS : Linux, linux

Loaded plugins:
MultiWorld 1.5.2 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
StarterKit 1.0.1 by TheNote for API(s) 3.9.0
BlazinVanish 1.0.4 by iiFlamiinBlaze for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
MiezeMC 1.0.0 by  for API(s) 3.11.1
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
MapImageEngine 1.1.2 by FaigerSYS for API(s) 3.0.0
Slapper 1.5.2 by jojoe77777 for API(s) 3.9.0
SignIt 1.1.0 by Wertzui123 for API(s) 3.0.0
PureEntitiesX 0.6.3 by milk0417, RevivalPMMP for API(s) 3.9.0
CB-Heads 2.4 by Enes5519 for API(s) 3.0.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
SimpleSwim 1.0.0 by TheDeibo for API(s) 3.1.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
SimpleReplies 1.0.2-1 by jasonwynn10 for API(s) 3.0.0
MiezeMC-Booster 0.0.1 by  for API(s) 3.11.4
NameSpaceRemover 1.0.0 by JackMD for API(s) 3.0.0
EnderChest 1.0.0 by School for API(s) 3.0.0, 4.0.0
AutoClearLagg 3.0.0 by Twisted for API(s) 3.0.0
ScoreHud 1.1.1 by JackMD for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.0.0
AntiVoid 1.1.0 by FiberglassCivic for API(s) 3.0.0
Repair 1.0.1 by JackMD for API(s) 3.0.0
DevTools 1.13.5 by PocketMine Team for API(s) 3.4.0
SimpleBanner 0.0.2 by  for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
WingUI 5 by Array for API(s) 3.11.0
ChestShop 2.2.6 by MinecrafterJPN for API(s) 3.0.0
MyPlot 1.6.11 by Wiez, Exxarion, jasonwynn10 for API(s) 3.4.0
MIE_Protector 1.0.4 by FaigerSYS for API(s) 3.0.0, 4.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWm1v2zgS/iuCdnFIsbH1Ylt++VAgcRJs9uKuEaft3lZFQEm0zZoStZSUxFn0fvsNKVmmlDix
E/eAw6XYbsUhOTPPDDmcIf23PmU8ROn1DeYJYZE+sA/1lIRYH1idntlrWZbVP9QpStJTzhnXB3/r
6TKGbv0K/slph3qIkwTNBPUSpxmPtBtEM6yxqRYzf4HTkETYdXGUknTpuhfkhkSzwWCG0yMeMn4e
3UAX48uDd1qYJanmYQ1FGomSFEX+AzZkNdx1q9MPtSijVONSBRyAXlNonxEqFIvniA8Mw5izEBuC
kc/RNDXWjJtihJFwX6EZucpGrjGMiAXTnOFTI2EUBaI+aHeEPTny4fuL/pOpxTSbATBjnHF8KqYQ
nPyxFs3xDQHbxWEYGzEMwcUQI0sJTYwR805QCJYeIupnFAHqg17r3eAJMzfeP2Jm0O8n68W6FFBD
Bg7C3LhFdAGCjD9Z6BF8YLUtUEiZ7LrqbNeVUFz3ESyDgV984zMSIZr3HzDvG/ZT7TfkL0YnrvsB
hXgSg0kvcchg3bruEBYNC8cULTE/1AKWeRRrtkRp7wvl5xzlKG8edO2nQa6cUEx33cJKrpubqfEe
pSkAkhotd4MogbV+EDCr39sRWZVB470/x/7iKAqOXgewrdV2GMU3mBoX4v8HfbP9Si1Z9DEOYKEd
kCjFM8y1rmM5lpTceUpyr9Wt7TfZC9tN/ANu9dMMUbo8YVfEXzzC3alzn2AOFjiwOy3nSc7BJo7d
TRydbl3XvKfwkWCXGyGpci330PoMaDr9TkdK622S1jZbG6SlQm85ub9pst0xn5g85syHIwaiXR66
zA1srJ5lbWADZwlPi+lWffpYfo7g88DutjdwuL72xeLhmZ+ulvMxSvAQDsfkgqFAxJ6Crk5fhTtE
ogs2m4lRwASW4hfL+arVz6Oy024/7Fzt+ByF/RSKft3zSW6hfGpLO8iD9F8Z4figEOn0vmovOybX
ksUZ+U7/+v1Qx/+L+cJuRzugzF1yDTIYvcEhDIX5JArArH6qr/qBVonS0OGzQOQEX9/Sg7f04C09
eEsP3tKDt/Tg/yY9ONRnOMIcUZEfREhcN+jrQY3RGNTwwHjrawm91bSsZlvQM0IDfWB1e71DnSTX
Ab7RB1NEEwynLWcp8xmwbfX6IISI09hqTe1e0Gt32lO/3e9jq+f0rb7p+56HArPb9abTTq/TmgJv
jhaUeDDHbFp20wRKVmh3QaLsTrNM3/HaGDttv6e1m7DuzYbZ9GLWdBooDJy2BufmZDTWTrBHICWR
Q5xuw/4lwJ5lZta/YWz/F0s7sE2r3zD7jZb5TrvrOdeOgCbuFwZ6t9lqOtC6x1EggedN6LxmyUoV
IMgGlY0yEUmEQUcZTclnxoWZSvMqxEN9bVar2WnaQEFZOmc8EWnI8B778/HoBN8k0PGJ3JHF8E95
mbLM0iRbEPheIErIIhGeRDERs1pNEwwGbRwhiA0gGrYCuCTAMeBI8lQnYdP0RCWESCZHvhAZh+BK
2Aqh0PRWaArbQtWawi4SC+X3ydXn3y8vToB0i72EpALfPE3jBJYm+HyeeU2fhYYCxFAYgbEmYrdj
/k+xPkoLKcSqhWAxVC10NccfGEhV0fdfjr5gB6Gk1CAPCM9hFlCOKbon0ScUkWSugKmQ63DaVTiE
nFEUEhKJSXhfPq1ydV1Vo2prG5jSdRDnU5FWr2FWyCpMG3ZNrwoTlmxGl/uCl3ODxE1oEOca1L02
uTq6vPo4fm6djiDKTgmmgRIzG6tgnkLaYoQoz8VUtGCUEcH3eDRUd3lBqXvcrJhCNQFEVeulNpjM
TdNfwCknDrBc8vYLV+SlY8zDRD0DSloVQLvZqvrSaZ+dmab2Dw2sIY7U82hKIsjo9uXd61yA65Ya
KZ8vCEVyrpKQ53yEC1F8LqqY02gmq8q1J6sdVXtY9Zh9hgikDpN/TfZlgJKhcKiqSb29jasnFMUx
5mqsLSjPHEXf2DeGu+LPvmJtkgvebpk+4si1RsYKgwBIZtF55SzJCXWvVbeh/hnz9D4jlt3al9vW
HOE0kTq8GOmalVGgKTbt+hajunHV2401bLPp1DdvSOjCbFtdoF7mJdp4BCnfnjz8RNWnarlzlFZU
rdbUwi7D48avGAVqLCtJ1WOpdvaeRjjpdKz+vhbAih+AlbWyUEH93ma7QiklbAYp9dVYAVQhV1e2
Xdu4ewKjSoSavSr/+ahDwpjiyS0JKxuzJD59Roqs7AQTj1U8Y70czFry9mfkKZSULFwejc8VCApR
hdBpduvhk0XYg7/7WlsFO/BErgHwdN2KNlv65BLHVGzBultW9Lpn7EYtAf+GEhbdLqPIMvcFTmEp
QqeizvbuKnKgxjFjIl97mJeVPdUIWS8wavlZe4/52XWhwfag6ndxCqoHXc9sqfx6b18e23xZuPX2
igLMh3OcqEe3QnwGzsSfM0YfwDnU26+L4Cv52wM5ylI2pBjxCzSbKViqdBVO65GAd0tgZQT7ck+a
s3NdEMF8oQQFJVy3rtOueUmh5lGypFk4GhpVfiLG+IzjXzP18qMk1RMy67+xQFfSd6uNhnOU1jIs
SapXRpb1WGm0Ewal7noAByoBPwVpCVRaIOgPyIJYloxPGyu6vqFqEsquv/ZQM0k2YJzz6GaC1VKp
IDyzW48pFNe/Mk7uC6X34eIKU9fNNXHd/L53q50LGc0nRtTFWpKeqR7OiIf5TFwvD8kN8fcGiWOU
zq+QeA6hy2MSIflyWii1/nqBRx9jbZT8votyIEZEPWEKwjP3cT9m2+ayX1w/5WyMAgGAO8E3V3Be
qGlPSaq5utXsVBGuL8e1K4zCCtT2y6Gu5LuuosluZdFaM6PkUSZ6xyiKqnW/Sq4nQT+khoAtuex0
VildLnmH21Xx2IB53W8Vcr0UMhseTtFWl+o/4vrcy3VLc7/WNH3NFXqFFdjmjPGwWpmsKFWLtOqB
a8Otjv2K5L3k6LqFEuXHVrfLEJA+qkgKQqW+qoD4oqOQ3sX611qu/vKbG5C4Q6khE8TJnMXqjUNJ
q1452PL9SHHAaPVwh/lv4w+7pQpKvfcEmlIV11W12nX5xWwGrQbj8RxFaIaNNTNRbi3HlKk5UkGo
Lj/nQYb0GUohoJze3SEuRh1urCd3Dq3V4ryIjVAzL4W88v5ifArNk9NPpBAv7/Un6ZLKoHiKkuWQ
hSGKApHbTgmlSo6VY4SFssL6RLiWRjo/vS6eDFilIq3Qn3kh2ny9/MpiR71mVhWqNZ/fEeIFdP0I
vQypoIJc+azdjDmLISTKOwdBjhEHK8DyL7TBdymOEpnNgoWGkK4r77DiFxBKEzhFSUIVSuxXxid/
UdCqpb7k5o/Kq6bnh5AGKQQfUbAM4iqJL+OUyYOxJdMdv/gZXTkg46oO35LCd13pFFg08gKi7J+m
6tPyLFAbodo1R4mqmvhJHWimjp+ML5SW/BFKkL+Z21LT0Mt/MKAMCpdgFPmaXXxpHZHF2Q04srSG
ZptWx2ybXfj8+TwYaF3fh//6Dna6nakTdG3c8afm1Ha603YPW07Xt5Hn2S3tZ2n9KFUtMZ5XDLle
Fdf+PIsW8vcW+Qu/tFTMEnKnjk/nPL/JlUeSJX5ecKhzDPYWC2SW5cZYTb/EU4plIaQabR4y1aaJ
1CFR11RSJAt9aJCZJ1PhoiwXNkzZAkfkvuLCJZKr2i625z2J82SxI5vSsKQc/v37fwAG64hP
===END CRASH DUMP===

**Comment by 95CivicSi** [comment]
Just pasting in the crash dump does not help to get the issue you're having solved.  You can either modify this issue and fill out the template appropriately, or open a new issue with the template properly filled out.
