### ISSUE TITLE
Apollo? For Java?

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#37]
Hi.

2. You can create and for Apollo ( Fork of Nukkit , java software ) ?
3. I can implement in Apollo if you create and for java?

**Comment by Sandertv** [comment]
1. There's an addon plugin for this that we've made. Scroll down the README and click the link.
2. We're focusing on PocketMine. This plugin already exists in Nukkit if that's what you meant.
3. ^

**Comment by NycuRO** [comment]
@Sandertv Ok , edited issue. You can create and one branch specialy for nukkit?

Your modification and addon is very useful :)

And i want to implement in Apollo :)

**Comment by Sandertv** [comment]
Like I said, there already is a Nukkit version somewhere on github. And what is Apollo?

**Comment by NycuRO** [comment]
Apollo: https://github.com/NycuRO/Apollo

And you can send me link with Nukkit version?

**Comment by NycuRO** [comment]
And yes, PureEntities is deleted from github.

Exist and other for nukkit, but isn't ok.

Sorry if repeat ,but you can create ADDON and PureEntitiesX and for nukkit?

**Comment by Sandertv** [comment]
The Nukkit version seems to have just been removed. It used to be at: https://github.com/SW-Team/PureEntities

**Comment by NycuRO** [comment]
I know is removed. But you can translate Addon and PureEntitiesX ( sorry if repeat ) for Nukkit? Your editeds is very useful.

**Comment by Sandertv** [comment]
I'm sorry, but I'm not going to try and port it for Nukkit. First, I don't have a lot of knowledge about nukkit and Java, and this plugin needs a lot of work too until it's really flawless.

**Comment by NycuRO** [comment]
Ok :(

**Comment by caspervanneck** [comment]
hey @NycuRO

**Comment by NycuRO** [comment]
@caspervanneck Hi =]
