### ISSUE TITLE
Server Crash on line 427 in file Living

### ISSUE THREAD

**Issue by DragonfireHD** [RevivalPMMP/PureEntitiesX#375]
Error: Return value of pocketmine\entity\Living::getArmorInventory() must be an instance of pocketmine\inventory\ArmorInventory, null returned
File: src/pocketmine/entity/Living
Line: 427
Type: TypeError

Server Crashed after this

**Comment by 95CivicSi** [comment]
Duplicate issue #379 has more information to be able to find a resolution to this.  Please watch for a resolution on that issue.
