### ISSUE TITLE
Mobspawning in radus of spawn

### ISSUE THREAD

**Issue by NormalOcean6686** [RevivalPMMP/PureEntitiesX#378]
Please add were mobs won`t spawn in in certian radus around spawn so u can stop mobs spawning at world spawns please ... big issue

**Comment by 95CivicSi** [comment]
After some thought on this, I feel like this should be the responsibility of other world protection plugins. PEX will stay focused on implementing MobAI that starts with initial vanilla like behavior and strives to do it with as little performance impact as possible.
