### ISSUE TITLE
Add Config for worlds

### ISSUE THREAD

**Issue by AbisGameryt** [RevivalPMMP/PureEntitiesX#381]
Mobs spawn in every world. Even the hub. And they can also spawn inside the spawn so please make the spawn radius about 40-50 blocks away for world spawn. Thank you !

**Comment by UnclassifiedX** [comment]
For your spawning in every world issue: You can specify which worlds you want mobs enabled in via the config which looks something like this

# set where entities can spawn e.g ["world", "flat"], or leave empty to allow entities to spawn in any level
enabledworlds: []

**Comment by 95CivicSi** [comment]
After some thought on this, I feel like this should be the responsibility of other world protection plugins.  PEX will stay focused on implementing MobAI that starts with initial vanilla like behavior and strives to do it with as little performance impact as possible.
