### ISSUE TITLE
Crash when summoning Salmon Entity

### ISSUE THREAD

**Issue by cyphr3x** [RevivalPMMP/PureEntitiesX#389]
I was playing around with swimming entities and noticed that the following seemed to work OK:

- Squid
- Dolphin (doesnt fall if summoned in mid air)
- Tropicalfish
- Cod
- Pufferfish

But **Salmon** crashed the server with the following:
`[Server thread/CRITICAL]: ErrorException: "Undefined offset: 109" (EXCEPTION) in "plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/BaseEntity" at line 98
`

**Comment by benda95280** [comment]
Could it be possible to know the version of PMMP, and PureEntitiesX ? (Poggit Ver)
