### ISSUE TITLE
Undefined class constant 'JUMP'

### ISSUE THREAD

**Issue by panduwijayasaputra** [RevivalPMMP/PureEntitiesX#395]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ 3.10.1
  __Plugin Version:__ 0.6.6
  Where you got the plugin: https://poggit.pmmp.io/p/PureEntitiesX

## Optional Information
  __PHP version:__ 
  __Other Installed Plugins:__ 
  __OS Version:__
    
    

## Steps to reproduce the issue.
1.  Download the plugin
2.  Copy and paste to plugins folder
3. Start the server
4. Join to server
5. Server disconnect

## Description
  Server closed with error

```

Error: Undefined class constant 'JUMP'
File: plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/WalkingEntity
Line: 245
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PureEntitiesX v0.6.6

```

**Comment by benda95280** [comment]
No informations on crash ?

**Comment by 95CivicSi** [comment]
Please update your PocketMine-MP version to 3.11.8 or newer to work around this issue.  I missed updating the API version number before the release.

**Comment by panduwijayasaputra** [comment]
> No informations on crash ?

eNrtWmtz20aW/StddGoiZQm+KUrMylUaSR4rsSyuJa+zFaZcTaBJIgLQCBoQxaT83/fc2w0CoGRP
asdbNR+SODHRj/vq+zi3gT9aS53FMv/4oDIT6qQ1HbRbeRir1rQ/Pun3T/rjo+N2K5Imv8wynbWm
f7TybYrpln1ut2JljFzRyPskUMswUYHwscEIXycml0kuvv3h/fXsW6xdFlH0KoxocbqW2bTbvZh2
/yFj1b3GPj+Ty1zcqgzCdNOoWIWJ6c6KTF0meZiHyvzUoV1dk/ndTD2EDzJK4zjtplii3JIu/9h2
P8joPkxWvHOLbSlxd5y/ImVQjSA5zDYaw3CZ9PH759aLnvgXucgkjGVUMjvjp4N+7+hwKmpb5/P6
3vncbp7PGzJ6L4s0kLm61g/qIExytVKZ6B9C9Bd9QbKk2r9XeQw9upF6UFH3Df3/4Hg8/HPcrKw7
rlZY76VO3jPfimdvYNkOvsR2ckxKVpPzOc/O5zztvZR+Xsgo2l7ou9C/f0p8uE/cOtTBYDQafpFw
8BmCo88RHE9GewTtjPfSXyv/nqhZC5gG0bYIdLGIlKgirNM7ngyZ2fhzzIZPpC+Z5SQ1bz763OZB
70ubZ5n2EcQ6s1Qmn6HSnxyPP0MFYZ7ldvfx/u4Z/6T4PhhMBp8h8PEjJ4us8PMDvfhV+bn4uzTq
nPLIGy0DlbWFG69vL/IwgiNeyzB5o1crWgUi8MGfB+NfxMV0PqfkggV72WU+3y0cDr+80MXxfM7a
nXxJu5N98xhrOBtqPXHQ53j6rQgzdeDYH/d+Ef8sFVY8vOtZlUKelYJS3WHrl0/tlvoa+fr/N2NC
Skv6Y5g86OhBxdgBfgEM5OetchYjDc6Y8HWgSLfB8Aiz85z+/YTxwXCye+bH491jt/taJgHC7tci
TiGOUKU8g+HJblW4FAff5OvQeC9pHUL2b38TB3JhytFY56iT3svHQ/Ef4pnx3w8PxUvR6/TGtHNv
citOT0XvUPxBXEe9Hdd5XuN5cPg9T/dr06jSSvrrktlK5TZZHvLvWSS3qN8Hh0Ia8U3KT4d/iG4X
mSb5Nhf3id4IaEabBf7ka4XDzsjIQidKTLvMcFBjSJY4cKSQGkNyDF9Z/ofiP0/F6OTQajFs7IIm
6b04FYnaiDM/19nlA+w8k+SfpWKjpzu8l/Y03hUJoY+rACQqXa+Ccuv42a3EAhv2+U2n5Md249GT
jaVqMpdOPBBzbCaN1exYo+PamB05abreuDxP+1Qen1OjqsHk5E6fcWnyTOVFltRUpux3J7PVzmpj
a2dLmyzIP6w9ut991/r0F/z4C378BT/+gh//DvCj3VqpRGUyohqdSGonWw0yEGkBA1dtZ2vY6fc6
fRovwihA+zk5Risamo+BemhNlzIyCngg07n2NcgOj9GWrkJCCyO1GJ/4veFkMBwfHS2PxyfqxB8N
h4PjiVyORr1e7xihIgegncn7KFxgD1gNOj2MFE66D2ES6I0Rb+/E6/+5eItI6fQEiyL6k8nRUByU
K/qo32fXF0cjwifoK6etSQfC0+PvKglYFfeM6Y/aEPWrt2/vMMAPGyCaHfIxZKEmuqmZbA/1VNbq
dY46RxiRRb7WmaGkH4fRfW/Un2D0nU2as2sYGmch05AWDDsnUBnPKpGIf0gKh4dRA5VCbqKBOaOX
+UV9IJYMwL6Qh+tSErpDvGDD7d3Zu7v3dNAbtTBhTvqs8zw1cDWc27pYdHwdd2uiNmsVmegSUanj
7dnsqmaU2mDdIuPOpDNoWgTQZoH/Gibo/d9N4Mih8FgJQHM+b0jjVJ/d3N59uHn35qKhPCn036hV
USTPtc6CMKHUXFPsmcm6gn2WvaHg7VqhEk02k6+loikJzudPpUGl4lT4ZxT9Uan0KiEoprNtTcfm
+J56TeV+XGuJhIQshQLxtRRsEJ3PG+LYRP5ntLsFeFavi6Cm2G6o6ZODfa1+ANS8vvha6lhqqGOO
e/Xrn6tBKUhmkD5XVrSneZ7EskWkg8yLZohDfNp6Mds9iXOdLMOVoE5xns2TF3eFEj8UiRiI/tG0
fzwdj8SHq7+LQW/Qo/lIJqsC7ecpsik9ozMKTs+LRejL6CcasPw8Mutz46nO8lOgluGABldYFaMV
PGXasXz0LKw3p5abSeUm8ahqoHTjTE69Pg1v1jCCF6GpOdXLJY1Y43u/FSrbnuqkNpQhwN0I/eyk
gAQbxMTpd/zPPJFJogv0Ro61hzYtVBblG7cR3Rvmd8I6njBwQKdVPqcPqVsfhMtl6BdRvj21anIx
hY96RuU5nNecsi0ZOLKlIFEUVGNGqaC2hG4ATi8uX529f3NHo/BH7Rn5oBy/h1BtvLLHOz2moceF
fvTIb0vpqJztKn5nG0fkB4Iihu4N4AIFJISJ2RMENBYNf4JniLu1MkqUKgiZKe5EkVOpJZW58MmW
uVgoESZ+VAQqwA/xxAOJ1q2OsZNa2ic0jVwqwDXMZIZIigV653ux1UXmaFEvjJMIlyFzcK1wtCXC
b9G4luS6gVpKHIMRG+6jZZoqmQkyXwxlfeoDSELuq1nvzVolokhXmUTSXHXmCTmuJTadJ0K8+LBW
JJjINbgkgQAJBwVhg0wmJkKqDew0ixppsIGq+KVythcAUegrsba3GRiJibL1sTK8poIRE02YdZED
uCSeu/iZinnLIjvhR9qoYN5iyc6iSG8EBQVdjjh0Ih5CKf6LooLWcHh4bmoqKFHx1ts1dkq+P9IQ
yTGyxpCOlCgMjhlZDaZmFVEysRKJMTBEpJrxINoCgtUYXHIslpSgOF1f4DnTsDqJu9gKd1a03oXu
brpmjRcfUNXgcjg4GQSAw8aeL4lKzQhEkgY4hMKXrkoWiqwC6wM3y4jOZRWiXghgFiS6A8cU6e2Q
qFuOSBqK8pSHc6WuYIpp5v22iBcwO9z2zGwT/06ae3hWdg9H7fCC9zgOjp1SU1q2zgAxCrgHlpu2
4FAXLiUg4NqwRQzbGSo6bBtkeRqLiwQuSkss8Vv2H+gEN870I7rkXMEMUIlDI9kJR7Z1Al0tKRho
DTl9W4T5tzBfnvG2QFFaZZ/c2ywOoAMOXAzYLKyG5zSdMqn9YJDsfVmRJHScAaUtnfIhMAg3HXGh
HtxvEYerNbJFJs26XY9u55ltvtwq0tyOWoORYWLI5vTiw4XDwUwIQxtx8kGHAcR+XgLyEfI5DUPD
uzo1R8Nizy7aeRqqEZJ9trVR/49IL+A9VMaFHUegxWFOySNWK7nYAl91xK01dY+NGxqizdvv6NQ2
IVuePQpZYeNZQqWTGdZwid4OP4S9EgOZJZB6ydI6OU6r4PBcaRyUpjxAXkGMViymx6JNRY+0AHfO
8fkaZg7+7TUgXPQl+anm/mvym1ynLILLzzuRHDkjkD4IJCCxlgIR11Kqfm8wcoJxEvjAUeHkM99+
BQk5LlgkyhjCL1DdElQ3oR6VX3B211ZkG5H2ZtitVo8+sIOpNLKJ6+buciruXl/dijdX11d3SN6z
N1eXt2J2+U4AXP54+a4tsEjc3WDVpfjw+ubNpZi9uzm/vL3t7KeAhj0G4yNnjpnKQs0VnxKxIQX5
Iqu0xi7Z9mF71JqAcwsv8ZAKlU2zTAqgFHoiQcObSN/POZt1MsBBqrAJLXPMmLIlgtRbJXJbkZjH
DdUQAhK8ofN0NfmCA/U4tlT5hDesZUlce652704HuJdKTaXqsOd0NYfPi+Q0HzrNVzJbIDI8X0eR
hbycgJ63LocaieN2CbcLuTuWCd9yNiQB8ivgg4ftsibsO2Hphra8LpegZfWNqxDsiBub863DA57o
Igp2soQoIptEVPIbSzhl8aHoUa/ndAW3V5wsnhRJdh1LYafbMtNxWWztbrfCq7tm/YRJG3eST3xD
PONSDe+4LREpHVkGTuSGzpGDIk4tfLMYUbgJjybK87qgRW4Dy85ilhrQi54NenX6+4mBUbRR+MDh
AU5mTKEoMeRrnNqqhLOUtAL3HswyaZcHaTGCQ60dKw0t/aydqO3y10Vyb0rZz2VKo2FcxKixKK+Z
KLsLOkhhOyUrRWVXfjNlTckR89THgOZTJxEz9AhmFyi6o92JXWg7te/ThI0o61n6dnEZQpaWW1jX
jJGD56OjUzvdLiAKYxXAR7IepLMAw1JJ+VWSsHushpV22ObsafUpOdPiCu2SASPqMxzdL5P6kh/O
k0TldGBTVyIAzdY6shBzIXN0qgT1WWSgJriQKzKc22xr5WZtaVmoHdi05e1F/ZTKKUqr2TYn4m3h
9WsHyIfHjL28FMaVAM7aFY7lxpUgZGA1p2aJgT5txqATqyNeAwvCl04Z3Inz2fs29kKGBeJrEwZw
e8YKNnvu6HtMfyomJeyuELlh69TWdsRZgES1ltGyS29LuU0IFHzYsQJTQZct5GC1QKzKXo1YvRW5
fKSsRhBTRm2bNIm1u2juCGQfxbmMkPT7WTIrcXjVfFKbQZs2qKhEs0iT1HPPe43PtQtIE/6udkdN
iL08YUO10KEpIHrrObWqOzoZ2E2HHTFzeyJ6RUkbpOuCnZswx2UmV6QdjgtqmTRiMEOtbQzhKQ/I
jI7wPArpsoR7dXo/oUwuru/es6QGKpHaiyIXdDfAp1yxs31Hp0xDcV54tGvK0lIABGpRrKZlL/NS
9KmHcUiOulaeLztWY5t5VXaytM05Sp+I2bxlqZ2vNXpUcs6yhVFlk8rJjd4rCyMfyiRK1y3lFRHN
VfEuUdORCZTMyxwDSe0LjxIyc7sFF2K4YlIgNIYvifajMBW8F3a8llvYkJwldq+ZXfp3OZPzllfO
WZamyhbl1VH9uuKO7xusA9gvBe1NDa91p10Y1+r78Prc5gW3x7N7piIFoHgII2Jjc56LZ8eFkrZM
VjtQndC2aL92tMtVjfuqZ6+IbJd3FuuCfHppk7NzcTKlvSXkYkThzL07DoZ+czXB5ndcW2qbWfFE
2V5xoSyxhaJPMwRfNHI5WJcewIfO94+NKmXVJ0Y79RGZQu6Lmtq3ouBGH348J2XveTFlBkoB37uw
I0LYcjP9vZNmyN5NnbRnX9CbWrbwqQAxI74mrV3FXF0ws0WkCUVSSJI9VUYnDVyL1BULp51wNw9l
teM9DdVBzxMD8UKs0LOYyjzV7cbOQp2nJnLBupEhNzVIHED89mxSnRZR6YzugdI+r3Ep4pj4MRj2
UhfVlFwpUKeihJl8VWqvc6au4NHtE7dYdtjWC3dckKO6Fwgqs5G7e/TR0t7QLtqaw+kayGypaweC
IPPs67PdyrWmg2FROvRerhNqljjRyTamFgHxkdN1nm8q0anvcfOimmcVOGPJ1SpDs2kvlnY3dwSk
6OuS+339WD4E8M3FDb1b9lwOtKWAcsJGWRwq+Ysg4mhY8EoBHuvU7pZReXaWt55pD+eJUXGedt75
Eope4rnUXYdTPK7rpgNCTchNarc8baTHdC3bGIYZqF7lO8SCzLtU6KJxhEhACdUDO1vWFXtnJBu3
Ru41UK3eFEBnKG2cxMpc4Qjyydv5kseTk7a61o86D+MqVbuCRERpfYkb6GQpXxJDvg5zm8qrz07F
wM3UOZTW/HLJc1nbnq6NitotQ3ktnIe5s2d5n7B2g5wwqCFwGNMlDLqeBYwPGGSFyx0hIHUoYi/7
KQGVTbZNcaDnMmRZ2GQUSuMQPECXjNOofCIMABndWU3LQ7Nz8Fu67ZmKn7l4o3y2+frnFyLK4Lyq
kvWXEKwGAaksDFyDXb7A4c75uYLF9ZwLtGEsyY0ZzieErK7a1sW3fFkG+1PQKx8qCrZ4VRyn4tWb
s7vp4PtJe3zy2G8PH4ftwff97wPla5tiD/JM4QG59fS4ZzOxfRqNDy3qsff99b7WRjiVFtjYXTsx
8uB7I5yavxX2e5oiK3NyCeaz3UU+ZxzQQaXy+U2MKQ3mlW8Z4AsW3r14xamGWfH6BpGCgYL7mLQ2
4jHW6lQ3ZDrlVlA9IvEZ1wf59wSXDWN+WGQRAqhubcvM60jfkD6NjWwVsTFjtWT6wCLZLle32i31
mKuE/Ihf758DINS/Eln4gETr+gi94UkCmTXGdPwx0DmSYWPUfcxbDRRZVH+mFFF/XoYR8md9ZBU3
vllZo3zUn0NE2UN94Ffj3s9P+F12vLCvq+pLCIhB/KA+lvpNrd+ppevDGzs57ZvmEPBJXB+5nb2p
P8Zb81vEH9q4X2Lcoe956BpeAE70+uPeqDfBz2+uEBIT38efkyN1NBkvj4LJQI39ZW85OJosR8eq
fzTxB3KxGAzFN6Cd63uVAB00LLaV/LZzAC78lU+Ysj36Y/tovyjarcbjY9w8E03qDHq9Yb8/OMHA
7OKmYapAf2RV9gcxFDaPE+kiMaax8DakhPDTdcNGexLgkTrSploY3GThnnek7l6OP2MadPr09RUE
Xjeds6rWHxmL8Ydw9rMqdpJwtQgTSV9+0Hdd/F0Ok8TPDhmAE1pgP8Qa8FdffrZNc80DQx5YBU/O
PGy4CdtmWB/KFKKBwm5VWGe04nz69L/4oB6l

**Comment by benda95280** [comment]
It seems your not using the last version of PMMP.
Could you try with an updated version ?
