### ISSUE TITLE
Spawners don't work

### ISSUE THREAD

**Issue by usser1976** [RevivalPMMP/PureEntitiesX#408]
Hello, 
we tried the last 5 versions. Free Spawn Mobs in Worlds works well. Unfortunately, Spawner don't work, we tried everything, waited 30 min. No mobs from Spawner.

Version:
PocketMine-MP 3.13.0 für Minecraft: Bedrock Edition v1.14.60 (Protokollversion 390)
and
PocketMine-MP 3.13.1 für Minecraft: Bedrock Edition v1.14.60 (Protokollversion 390)

PureEntitiesX Version 327

**Comment by 95CivicSi** [comment]
I haven't identified the root cause of this yet, but I feel like it has something to do with how spawn eggs are created.
