### ISSUE TITLE
Skeleton Arrows Shoot Backwards

### ISSUE THREAD

**Issue by HyperFlareMC** [RevivalPMMP/PureEntitiesX#409]
https://github.com/RevivalPMMP/PureEntitiesX/wiki/Issue-Reporting-Guidelines
If you do not follow the guidelines at the above link, your issue will be closed with a Resolution Status of "Invalid".

## Required Information
  __PocketMine-MP Version:__ 3.14.0
  __Plugin Version:__ 0.6.6
  Where you got the plugin: https://poggit.pmmp.io/p/PureEntitiesX
    
    

## Steps to reproduce the issue.
1.  Spawn a Skeleton
2.  Get in a gamemode where it can attack you
...

## Description

Issue is quite simple, skeletons arrows shoot backwards when they have a target locked in.

```

No crash dump, just incorrect arrow direction.

```

**Comment by 95CivicSi** [comment]
Try the updated version:
https://github.com/RevivalPMMP/PureEntitiesX/releases/tag/0.6.7
