### ISSUE TITLE
Spawner Problem

### ISSUE THREAD

**Issue by MonoAdrian23** [RevivalPMMP/PureEntitiesX#414]
PureEntitiesX Latest Dev
Pocketmine 3.14.0
If you break down a MonsterSpawner by being a spawnegg, the mobs will continue to spawn

Steps to Reproduce
1. Place a Mob Spawner
2. Choose youre favorite Spawnegg and put it in
3. Destroy the Mob Spawner
4. Mob spawns continue without Mob Spawner

Sorry for my english, greetings from Germany

**Comment by 95CivicSi** [comment]
"Latest Dev" isn't a valid version number.  The problem you're describing should have been fixed here:
https://github.com/RevivalPMMP/PureEntitiesX/commit/4ab1dbd684913bc6a328aa695619648044c59ea2
