### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by MonoAdrian23** [RevivalPMMP/PureEntitiesX#416]
At First, thanks for hard work at this plugin!
Can you add in config, Only allow Mob Spawner ?
Many Server doesnt need Mobs in any worlds.
Spawns only Mobs with Mob Spawner, and Not random in a world.
Comes good in Mobfarms.
Thank you very much!

**Comment by 95CivicSi** [comment]
In the config, there is a section like this:
https://github.com/RevivalPMMP/PureEntitiesX/blob/stable/resources/config.yml#L21-L25
```php
tasks:
  spawn: true # set to true to enable spawn/unspawn tasks
  async: true # set to true for mob equipment working and relogging tamed entities working
  looking: true # set to true to enable entity interaction and enderman looking detection e.g.
```
Changing "spawn" to "false" will do what you are asking.
If you need more specific control than that it would need to be handled through another plugin like https://github.com/RevivalPMMP/PEXProtection
