### ISSUE TITLE
-----

### ISSUE THREAD

**Issue by PikyCZ** [RevivalPMMP/PureEntitiesX#42]
this problem :::
 Declaration of revivalpmmp\pureentities\entity\BaseEntity::entityBaseTick($tickDiff = 1) should be compatible with pocketmine\entity\Living::entityBaseTick($tickDiff = 1, $EnchantL = 0)

**Comment by Sandertv** [comment]
Aware of this. It doesn't affect anything though.

**Comment by Magicode1** [comment]
Please also use an accurate title,.
