### ISSUE TITLE
Entity Squid

### ISSUE THREAD

**Issue by Scherzhertz** [RevivalPMMP/PureEntitiesX#421]
16.07 05:52:41 [Server] INFO 05:52:41 Server|CRITICAL > Error: "Class 'pocketmine\entity\Squid' not found" (EXCEPTION) in "plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/animal/swimming/Squid" at line 27
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #0 vendor/pocketmine/classloader/src/BaseClassLoader(138): include()
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #1 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #2 (): BaseClassLoader->{closure}(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #3 (): spl_autoload_call(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #4 src/pocketmine/entity/Entity(465): ReflectionClass->__construct(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #5 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities(181): pocketmine\entity\Entity::registerEntity(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #6 src/pocketmine/plugin/PluginManager(182): revivalpmmp\pureentities\PureEntities->onLoad()
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #7 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[74] /plugins/PureEntitiesX.phar, array[3])
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #8 src/pocketmine/Server(1608): pocketmine\plugin\PluginManager->loadPlugins(string[56] /plugins/)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #9 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #10 src/pocketmine/PocketMine(304): pocketmine\server()
16.07 05:52:41 [Server] INFO 05:52:41 Server|DEBUG > #11 (11): require(string[96] phar:///custom.phar/src/pocketmin)
16.07 05:52:41 [Server] INFO 05:52:41 Server|CRITICAL > Could not load plugin 'PureEntitiesX'

**Comment by Scherzhertz** [comment]
This is the latest version 0.6.9 , i also tried 0.6.7 from poggit

**Comment by 95CivicSi** [comment]
You didn't fill out the issue template and you've left out crucial details that are needed.  It appears that you are using a non-release version of PocketMine-MP.  PureEntitiesX does not work on custom forks or modified versions of PocketMine-MP and support for those won't be added.

**Comment by Scherzhertz** [comment]
Well i also tried on latest non modified pocketmine

**Comment by 95CivicSi** [comment]
There's no way that you got that error on a released version of PocketMine-MP.
https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/entity/Squid.php

Even the 4.0.0 branch still has this mob in the same namespace:
https://github.com/pmmp/PocketMine-MP/blob/master/src/entity/Squid.php

If you're not using a phar from the [PocketMine-MP GitHub releases](https://github.com/pmmp/PocketMine-MP/releases) or [PocketMine-MP's Jenkins site](https://jenkins.pmmp.io/job/PocketMine-MP/) then it's not a released version.
