### ISSUE TITLE
Mobs Drops nothing

### ISSUE THREAD

**Issue by MonoAdrian23** [RevivalPMMP/PureEntitiesX#422]
Dev Build 345
Pocketmine 3.14.1

Killed mobs gives no Loot
Reproduce
1 Spawn a Mob
2 Kill IT
3 No Loot

**Comment by 95CivicSi** [comment]
You're using a build from the master branch.  The master branch is currently in a very broken state and many things are not working on it.  Use the official releases to ensure best stability for your server.  Right now, the best build to be testing with would be https://poggit.pmmp.io/r/95938/PureEntitiesX_dev-344.phar

**Comment by MonoAdrian23** [comment]
Hm nice
But the Version before this Dev Build Crashs the Server.
And The Official Version Too
Thank for youre Help

**Comment by 95CivicSi** [comment]
I don't have any reports of crashes based on the version I suggested.  If you get a crash on that version, please report it and I'll fix it.
