### ISSUE TITLE
Tamed::getPositionNearOwner() is missing null return type

### ISSUE THREAD

**Issue by AirLeMineral** [RevivalPMMP/PureEntitiesX#423]
Error: Return value of revivalpmmp\pureentities\entity\monster\walking\Wolf::getPositionNearOwner() must be an instance of pocketmine\math\Vector3, null returned
File: plugins/PureEntitiesX-stable/src/revivalpmmp/pureentities/traits/Tameable
Line: 192
Type: TypeError

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: PureEntitiesX v0.6.7

**Comment by AkmalFairuz** [comment]
send backtrace

**Comment by HanifWadowsky** [comment]
haha
