### ISSUE TITLE
Villager shops in BedWars don't work

### ISSUE THREAD

**Issue by hamid0740** [RevivalPMMP/PureEntitiesX#428]
PocketMine-MP Version: 3.14.2
Plugin Version: 0.6.7
Other Installed Plugins: BedWars ( by @thebigsmileXD )

Description

When using the BedWars plugin beside your plugin, the Villager shops don't work.
They get completely black and just move.

**Comment by 95CivicSi** [comment]
There's not much I can do here.  There are major conflicting issues between the two plugins that aren't going to be fixed.  I would suggest you put your BedWars setup on a separate server instance that doesn't have any MobAI plugins on it.

**Comment by inxomnyaa** [comment]
I have already exchanged the villager with a custom mob (id: "bedwars:shop") to avoid such issues. There is jsut a slight issue with pmmp not supporting string mob ids with spawn eggs yet.

> you put your BedWars setup on a separate server instance that doesn't have any MobAI plugins on it.

Precisely what i wanted to say, as always.
