### ISSUE TITLE
Error Plugin?

### ISSUE THREAD

**Issue by AirLeMineral** [RevivalPMMP/PureEntitiesX#429]
PocketMine-MP Crash Dump Fri Jul 10 16:51:47 WIB 2020

Error: Class 'revivalpmmp\pureentities\utils\MobEquipmentConfigHolder' not found
File: plugins/PureEntitiesX-stable/src/revivalpmmp/pureentities/components/MobEquipment
Line: 124
Type: Error

Code:

Backtrace:
#0 plugins/PureEntitiesX-stable/src/revivalpmmp/pureentities/entity/monster/walking/Zombie(152): revivalpmmp\pureentities\components\MobEquipment->entityBaseTick(integer 1)
#1 plugins/PureEntitiesX-stable/src/revivalpmmp/pureentities/entity/monster/WalkingMonster(185): revivalpmmp\pureentities\entity\monster\walking\Zombie->entityBaseTick(integer 1)
#2 src/pocketmine/level/Level(852): revivalpmmp\pureentities\entity\monster\WalkingMonster->onUpdate(integer 22262)
#3 src/pocketmine/level/Level(785): pocketmine\level\Level->actuallyDoTick(integer 22262)
#4 src/pocketmine/Server(2267): pocketmine\level\Level->doTick(integer 22262)
#5 src/pocketmine/Server(2398): pocketmine\Server->checkTickUpdates(integer 22262, double 1594374707.1227)
#6 src/pocketmine/Server(2154): pocketmine\Server->tick()
#7 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
#8 src/pocketmine/Server(1588): pocketmine\Server->start()
#9 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[44] C:\Users\test\Desktop\PocketMine-MP-3.12.6\, string[52] C:\Users\test\Desktop\PocketMine-MP-3.12.6\plugins\)
#10 src/pocketmine/PocketMine(304): pocketmine\server()

**Comment by 95CivicSi** [comment]
This looks like a customized copy of PureEntitiesX.  This problem doesn't exist in the latest releases and didn't exist in the releases for PM 3.12
