### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shecter** [RevivalPMMP/PureEntitiesX#43]
I'm getting this error when viewing creepers. It displays repeatedly the same information each time.

phar:///home/gs/gs/data/servers/4813054/plugins/PureEntitiesX (3).phar/src/magicode/pureentities/entity/monster/walking/Creeper.php on line 62
2016-12-17 [06:08:25] [Server thread/CRITICAL]: Could not tick level "SW": Argument 3 passed to pocketmine\event\entity\ExplosionPrimeEvent::__construct() must be of the type boolean, none given, called in phar:///home/gs/gs/data/servers/4813054/plugins/PureEntitiesX (3).phar/src/magicode/pureentities/entity/monster/walking/Creeper.php on line 62

**Comment by Sandertv** [comment]
Yep, I'm aware of this one. I'll look for a fix soon.

**Comment by JunkDaCoder** [comment]
Can confirm

**Comment by shecter** [comment]
really dumb question. where do i download the updated version when this is fixed?

**Comment by Sandertv** [comment]
You can download it from the poggit button at the README.

**Comment by Sandertv** [comment]
Too bad it's not working every now and then. You can download the zip too and compile it to phar using pmt.mcpe.me if it happens not to work.

**Comment by Sandertv** [comment]
The cause of this is the event being different in PocketMine than for example Genisys. I can't fix this, as it will be either forks of PocketMine that have compatibility, or PocketMine, which this plugin was intended for.

**Comment by shecter** [comment]
Which versions of pocketmine will this plugin work with?

**Comment by Magicode1** [comment]
The Official Pocketmine Phar. Other 3rd party spoons (Such as Clearsky or Genisys) will not work.

**Comment by shecter** [comment]
Thanks @Magicode1. I assume you are talking about this version? http://screencast.com/t/jLwXhA7ytgk5

**Comment by caspervanneck** [comment]
nope @shecter

**Comment by shecter** [comment]
@caspervanneck @Magicode1 can you throw me a bone? what is the latest version and what's the link to get it?

**Comment by caspervanneck** [comment]
[PocketMine-MP_1.6.2dev.zip](https://github.com/RevivalPMMP/PureEntitiesX/files/661759/PocketMine-MP_1.6.2dev.zip)

here is 1.0.0 release

**Comment by caspervanneck** [comment]
@shecter

**Comment by shecter** [comment]
Thank you very much @caspervanneck . I'll give that version a try with this plugin. I hope that version of PMMP doesn't make my other plugins stop working.

**Comment by Magicode1** [comment]
That is actually a Phar that @caspervanneck made himself for 1.0 (Thats not bad or anything, it's just not official Pocketmine). If you want to download the official version, check here: https://github.com/pmmp/PocketMine-MP/releases

**Comment by shecter** [comment]
Thanks @Magicode1

**Comment by shecter** [comment]
Thanks. that worked.
