### ISSUE TITLE
Crashed while AFK (night time in MC)

### ISSUE THREAD

**Issue by firstfrostbite** [RevivalPMMP/PureEntitiesX#438]
Check these things before submitting your issue:
- [x] Server Software must be a released version of PocketMine-MP from [GitHub](https://github.com/pmmp/PocketMine-MP/releases/) or [Jenkins](https://jenkins.pmmp.io/job/PocketMine-MP/)
- [x] Make sure you are on the latest released version of PureEntitesX from [GitHub](https://github.com/RevivalPMMP/PureEntitiesX/releases/) or [Poggit](https://poggit.io/p/PureEntitiesX)
- [x] Issue must have not been reported previously
- [x] Have a detailed title.

Link to crashdump: 
PocketMine-MP Crash Dump Wed Oct 7 19:09:35 UTC 2020

Error: Undefined property: pocketmine\network\mcpe\protocol\MobArmorEquipmentPacket::$slots
File: src/pocketmine/network/mcpe/protocol/DataPacket
Line: 205
Type: Error

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PureEntitiesX v0.6.0

Code:
[196] 	}
[197] 
[198] 	/**
[199] 	 * @param string $name
[200] 	 * @param mixed  $value
[201] 	 *
[202] 	 * @return void
[203] 	 */
[204] 	public function __set($name, $value){
[205] 		throw new \Error("Undefined property: " . get_class($this) . "::\$" . $name);
[206] 	}
[207] }

Backtrace:
#0 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/components/MobEquipment(625): pocketmine\network\mcpe\protocol\DataPacket->__set(string[5] slots, array[4])
#1 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/components/MobEquipment(278): revivalpmmp\pureentities\components\MobEquipment->createArmorEquipPacket()
#2 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/entity/monster/walking/Skeleton(66): revivalpmmp\pureentities\components\MobEquipment->sendEquipmentUpdate(object pocketmine\Player)
#3 src/pocketmine/entity/Entity(1957): revivalpmmp\pureentities\entity\monster\walking\Skeleton->sendSpawnPacket(object pocketmine\Player)
#4 src/pocketmine/entity/Entity(1967): pocketmine\entity\Entity->spawnTo(object pocketmine\Player)
#5 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/PureEntities(298): pocketmine\entity\Entity->spawnToAll()
#6 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(231): revivalpmmp\pureentities\PureEntities->scheduleCreatureSpawn(object pocketmine\level\Position, integer 34, object pocketmine\level\Level, string[7] hostile, boolean )
#7 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(292): revivalpmmp\pureentities\task\AutoSpawnTask->spawnPackToLevel(object pocketmine\math\Vector3, integer 34, object pocketmine\level\Level, string[7] hostile)
#8 plugins/PureEntitiesX.phar/src/revivalpmmp/pureentities/task/AutoSpawnTask(118): revivalpmmp\pureentities\task\AutoSpawnTask->spawnHostileMob(object pocketmine\level\format\Chunk, object pocketmine\level\Level)
#9 src/pocketmine/scheduler/TaskHandler(137): revivalpmmp\pureentities\task\AutoSpawnTask->onRun(integer 901801)
#10 src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 901801)
#11 src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 901801)
#12 src/pocketmine/Server(2391): pocketmine\plugin\PluginManager->tickSchedulers(integer 901801)
#13 src/pocketmine/Server(2154): pocketmine\Server->tick()
#14 src/pocketmine/Server(1994): pocketmine\Server->tickProcessor()
#15 src/pocketmine/Server(1588): pocketmine\Server->start()
#16 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
#17 src/pocketmine/PocketMine(304): pocketmine\server()
#18 (11): require(string[71] phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.15.2 [Protocol 408]
Git commit: d7a66ad7559f23d24ffe95813421a720203109b1
uname -a: Linux d864dce5-59c3-4545-93fb-a584022c978b 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64
PHP Version: 7.3.23
Zend version: 3.3.23
OS : Linux, linux
Composer libraries: 
- adhocore/json-comment 0.1.0@8448076039389f558f39ad0553aab87db3f81614
- ocramius/package-versions 1.5.1@1d32342b8c1eb27353c8887c366147b4c2da673c
- pocketmine/binaryutils 0.1.12@566fa87829e007eda0bd96e39fe20b9b0d638132
- pocketmine/callback-validator 1.0.2@8321aa3ccfe63639b0d08f0cbf270755cfc99fe2
- pocketmine/classloader 0.1.1@7c0363491d1ce8f914fe96d41a4338c982adedff
- pocketmine/log 0.2.0@e59bedb5d4bbeb9a26647cb7c367cb2fa72addfa
- pocketmine/log-pthreads 0.1.1@9bbcef398b01487ab47c234a6a7054722abbe067
- pocketmine/math 0.2.5@8c46cfa95351fb0b2b30739a381310941934b55f
- pocketmine/nbt 0.2.15@f8a81d37d24eb79fb77d985a52549d68955bc6a1
- pocketmine/raklib 0.12.9@5f2a02009f486ca4d90892814570fa13ebdc078d
- pocketmine/snooze 0.1.3@849510fa62e57512b8467e3694e9b3add97038fd
- pocketmine/spl 0.4.1@ff0579a0be41bbe65d3637607715c0f87728a838
- doctrine/instantiator 1.3.1@f350df0268e904597e3bd9c4685c53e0e333feea
- myclabs/deep-copy 1.10.1@969b211f9a51aa1f6c01d1d2aef56d3bd91598e5
- nikic/php-parser v4.10.2@658f1be311a230e0907f5dfe0213742aff0596de
- phar-io/manifest 2.0.1@85265efd3af7ba3ca4b2a2c34dbfc5788dd29133
- phar-io/version 3.0.2@c6bb6825def89e0a32220f88337f8ceaf1975fa0
- phpdocumentor/reflection-common 2.2.0@1d01c49d4ed62f25aa84a747ad35d5a16924662b
- phpdocumentor/reflection-docblock 5.2.2@069a785b2141f5bcf49f3e353548dc1cce6df556
- phpdocumentor/type-resolver 1.4.0@6a467b8989322d92aa1c8bf2bebcc6e5c2ba55c0
- phpspec/prophecy 1.12.1@8ce87516be71aae9b956f81906aaf0338e0d8a2d
- phpstan/phpstan 0.12.48@d364cfbac9ffd869570cdfea7eaa6541c3dac666
- phpstan/phpstan-phpunit 0.12.16@1dd916d181b0539dea5cd37e91546afb8b107e17
- phpstan/phpstan-strict-rules 0.12.5@334898a32217e4605e0f9cfa3d3fc3101bda26be
- phpunit/php-code-coverage 9.2.0@53a4b737e83be724efd2bc4e7b929b9a30c48972
- phpunit/php-file-iterator 3.0.5@aa4be8575f26070b100fccb67faabb28f21f66f8
- phpunit/php-invoker 3.1.1@5a10147d0aaf65b58940a0b72f71c9ac0423cc67
- phpunit/php-text-template 2.0.3@18c887016e60e52477e54534956d7b47bc52cd84
- phpunit/php-timer 5.0.2@c9ff14f493699e2f6adee9fd06a0245b276643b7
- phpunit/phpunit 9.4.0@ef533467a7974c4b6c354f3eff42a115910bd4e5
- sebastian/cli-parser 1.0.1@442e7c7e687e42adc03470c7b668bc4b2402c0b2
- sebastian/code-unit 1.0.7@59236be62b1bb9919e6d7f60b0b832dc05cef9ab
- sebastian/code-unit-reverse-lookup 2.0.3@ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5
- sebastian/comparator 4.0.5@7a8ff306445707539c1a6397372a982a1ec55120
- sebastian/complexity 2.0.1@ba8cc2da0c0bfbc813d03b56406734030c7f1eff
- sebastian/diff 4.0.3@ffc949a1a2aae270ea064453d7535b82e4c32092
- sebastian/environment 5.1.3@388b6ced16caa751030f6a69e588299fa09200ac
- sebastian/exporter 4.0.3@d89cc98761b8cb5a1a235a6b703ae50d34080e65
- sebastian/global-state 5.0.1@ea779cb749a478b22a2564ac41cd7bda79c78dc7
- sebastian/lines-of-code 1.0.1@6514b8f21906b8b46f520d1fbd17a4523fa59a54
- sebastian/object-enumerator 4.0.3@f6f5957013d84725427d361507e13513702888a4
- sebastian/object-reflector 2.0.3@d9d0ab3b12acb1768bc1e0a89b23c90d2043cbe5
- sebastian/recursion-context 4.0.3@ed8c9cd355089134bc9cba421b5cfdd58f0eaef7
- sebastian/resource-operations 3.0.3@0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8
- sebastian/type 2.3.0@fa592377f3923946cb90bf1f6a71ba2e5f229909
- sebastian/version 3.0.2@c6c1022351a901512170118436c764e473f6de8c
- symfony/polyfill-ctype v1.18.1@1c302646f6efc070cd46856e600e5e0684d6b454
- theseer/tokenizer 1.2.0@75a63c33a8577608444246075ea0af0d052e452a
- webmozart/assert 1.9.1@bafc69caeb4d49c39fd0779086c03a3738cbb389
- pocketmine/pocketmine-mp 3.15.2@d7a66ad7559f23d24ffe95813421a720203109b1

Loaded plugins:
Backpack 0.2.1 by XenialDan for API(s) 3.9.3
WorldGuard 1.1.7 by Chalapa for API(s) 3.0.0
ShadowAntiCheat 3.6.3 by DarkWav for API(s) 3.0.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
LockMyStuff 1.1.0 by Mohagames205 for API(s) 3.0.0
GrabBag 2.4.3 by aliuly for API(s) 3.0.0
PureEntitiesX 0.6.0 by milk0417, RevivalPMMP for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtW2tz28iV/Std8tRGThEk3g+mNCXH9mRm115rLXmdqnDK1Wg0SMQggOAhiZOa/77ndjdIkJI9
WY+rdj84k7IIoPv2fd9zG41/nuV1u+X9h1vZdkVdnS292VlfbOXZ0glt106iKApmZyXv+pdtW7dn
y3+e9bsGj8/09exsK7uOr+nOuyqTeVHJjDVt3ci23y1ZU4uPst/i7mpVyf6ubj+uVlvR4BKD+lrU
5Wr1uk6ftdu6ffmPoWi2suqvOM1aLr/ryrrvsEg+lOUPRUmrNBveLheLxabeyoWoq56DeLu4Ugu9
xm/r9dWcBi26ViwO6y/M8gtafTEuvnjBe66Xw6SGltLL/C8nY2KJcWdL14a++pYL/P7b2RObNeWw
LqpucTW08mXVF30hu78eGGzlbXHLy2a7bRYNhkgzBKJtm7rCZbeAfvaqOQ/d4Om/qNcDe9b3Hz50
sj/v+rao1n8LfmZKszPG25bv/ub//BQCPHG+OrNuFIPZyTSwN5m3Wh0mKjfYz7S+F63kvTz4hRbk
XDHqfjGj6sdusa2rrofX3PHyIxSyuP4oS9nX1XkYfim/nayy/eW7JgPz53X6dyn6I2NdlXwnWyWF
x06czDCn5NmdO0kQfZ4ZPR5219KsVkac1WqUR7N13fC7yujv8yz5v8VSGJ0438iDHoH1aK2b+jfW
Cb7YgNPx524S/2vsPCtL7TnhFy/c8+7j4tnQ10qbN7g6dz3n8waargFexEZmQymfk2fjiSL0mKJK
eSsRvld1h5l1NWNF1cu1bJnnz9inx7+iPzNmYjz6mW3qrkc2m7G0rkvJK6ZUEH1VFSTu51VAc1ar
o0nGKuSQN7Vi+jEloCptVqv/xu269X6vCpTg8dcU3HHiLxX8R80T0sdnjK/r8mr1fDNUH39TZCVf
chq8o8O1C1r9R15l+H3ueNEXcF5Xb4fqfLRCYjux7eiiYX9+2evx6tyJkpNo3Y9crSYcWt+3n1jK
OV1KG3Rxpf685hWASHseBv7n19mzZH2/BXq42SAgsx8lb/sUkfnoyu7pyteyBWZCCkick8U0T5Tu
JkxZ3/eFOCzcPbqI96lFnAcS6Seaqs5sjv+J2U6SfG72VVsLQLi6NWSCT5EJ4vgTZLoeqjPTw9Pp
B2AGNOB9gsKHD4JqWDuIfYX6M+/kcwDP7lXNM9k+GgID4ogKMYz4ql6vaZQJfSf8mZ1CxP1D13/4
cEwNWoroM1J49gP30hrSU2OG3KACDGCglSPkipyf2RdD18MIAqlPz37+dXYm/0/x+O8GyZBAq/xD
Ud3W5a2kdUCyqDJoTdBY/Rz3jtI1Hog6kyQ54Aiervpfcc9JIvxWP2J1c/HHP6qrRF2xP7LLhrd8
a3yAfVdxdDmzM9e2TwZsi3uojH2H7DjoEY4ZoS7c/fBWoopX7LYuMvXEM08W6spXV82QloVg+VAJ
KuVMw3C1+Mws8fSfanygxq/6ftPWd6ySdwwohmx6vnrUkqszNmdr2X8QFCTn3/WbonuKW6uz5XK1
+k49Vus8/ZOif1CVa5Oqfj379Vuj8q1R+daofGtUvjUq3xqVb43Kt0blW6PyrVH5yo3K7GwtMZWX
hNcV5Aacn5IBKykUeHgBcebNnWDu0v2hKLOzpRM7weys6D5k8vZsmfOyk+gNDHY8W/p2jEUK6h2y
iIchz6IgSHLXy1w/z2USxI7nuw6PAN1tz7GT1AHtwfDyqqiGe5bFoZ8JGVhBIjzLD/zASrw8tXgQ
+7briiSKU+YTX7blOK6lZAKsR6B71rt0qPqBXb++Yjebgf37ULKEud7Sd5Zewt7dPGe0MruPww+h
T23NpsHC0dybux4ufwHuUVKbazz+UHcja7ihLkpzoWAdzPihLNKWt0iDpFiebaCMVi7+3gFKYYxp
puy5M7cvY9+P7Si0vcSLkzwI4txLeGYHgcd5GkdZ6uWxEzrEWy3QARVDt2hQ85AOLGMWYsGZB3Pn
0sk8F/pMY+HIFHESeCKO40h4IShEqS/cjIeRJ0iSg1+kRcXbnYoCw5bjXgZhmPM4it1E2nYkM26n
WRJKL8mla6dJamehB+O5x6QEL8sU3FkoCgXAKzXB4M2eu5exBztzT4hchl7oEQU7zm2R5m5kwytE
LhIifkKQYrdUsTvydhkJGwT8xMkcIeM8cXx4Upj5Dvc9LxZJ7GJ4lufHlMp6rSi4ULoMklRmaZD5
aSrThLth6EciJUXhj5vDH3mW5fwBBavpVZrfK+oySVMhYbM4tR0/jngKQrABD3lkB37kuhxL2GF0
TIpgieEmuIyFH4qcJ4EXOHlqp27q2RG8gPSLkPCdxPPTIDiRp0p7Q8EJLvOYxzB+hLCSaZTkaRRl
SRzwwA38JAvjJAhSEXLnmETLP8JTtSjuPLkMcpcjGuwk9+NQcD9L7DhxY8cPIjvnjifTTNhRnB1T
6aq6/kUahXhw6CRwMDx0ZRAFDpzRDyPphYkvk9SDWpPI9uL8lEhTKgqI48s8t4MogcNJ34HywiCD
uREiUeQEws7jKHIhrheDQlYLSoxygaTbc2CPvct5RMgL7Cy33TCWie0HCdiAE0PbcSACT9rS87xc
SjLzdgdPS7tFJmWDGG12iohjk4XDJHUdJ094AAd28lDY8LzM5TIPwowoOkESywBUquJjgZS7aayG
t51y2VufqLiXISLbSaXnONz1bGkndpQHWS5tF0jKdzkJDSeWKsnw1ipqOElV5LIjM8NpwUkcuGEg
88zjeZQilLifutwVnp+luQiiOM4yN3E8b0JjmrmJDRGmaRi7QSbzGJHNPdd1odLY86I8FpLnThIF
Obd1roN6B8pWdQtUm5dSbZOoFKZIuiqYnMx2BLzMl1no5m7AeezzyI945gVZwJ0wcf0wdNPPkcTd
tIQ3gCjKC/i0w4RHcQDF+04O3839JPckElrgx5lwhJBhhmwZPiBKG25WKzvatdKe4IPHkMMJ0ziJ
EwicJS7sKGJkHkS/EKEMhJtypCAjdtdIQVtkzUYK4wguqR/ZBh4dpjKCI8CbkyBEck7skPPcRuqR
dhZzNzNE4I8L83cMMT++hC/7IkeOTPIclQ3duS3gBjySnANyOsLLuAjD8CERC3+HquhHYk4I1cP5
wgxFOLUDL8kkDwSygIRH+iHP0zh1kLud6BFiBChEb7XAkd1IMbj0PB9KIq9wIumHdiDtPEFu8jIv
F0hGTpohWabaSxU3yttpzw//QON6czNRjoES5qcR2Ik9qAyZKc/cVPgyShMXyuOeLbBa5J4Qo+1L
q+hBS8cyOW5wyUFLxsgouYtMYEMwOxciDaMcdTJ149xFZMIcJ8Ro//Kj1GQoXcMfkaejzIbJwiAN
4sS3kWkiN48ckXBh+y5KVBidkOnlfY9/tk3Je2ni0bt0YpTXyHZCGdoycP0okkAnqEzIC6i2USoC
V2Sxf0qs2CqOAh2RcARUMD9BikykmwMjSZnkGbzKdn1EQITi5KUnHBlHSJR3IxHBcGHEoyTyhZ+G
AmGCcMlzJBYH2clB8fZVhuokAB3SZIXKWhyylKPyi++7MhKRDGMYHxUQddaHe0ZpGMYwXOoCbwnU
p2M6ZHvDDpGJLoPE9eAjCHmk7yRxEsRqlIc2ShtAAKgGqJgJTx8ng+ClpCWtsq4/Ds1e2YgYJ7cp
8pFsqMChGIV55kDlYA4FijzBOxUSiIyPjuQrR4p4nOeeHfpU1SJEjXA44Aj81OUEHRwpApQt+wGd
Ut4X/W6fjFMeC8JTNjSSpwK1OrO9NAh9FHvPt+HcUe5IhUIOdLICNzQnHuqcSPyEoyAgmwAESa64
8oCRvSCNXekLz7WTY3XL6rZo68pgyECVXC+OYXOZOSjaHBkKi8ONwkSi2XIBqjiI2DYXx4Tum7rt
ZbtnJ4sTAfAUhQ7wYxoQX17AwxTlmksUUggV26jGR1TWZZ3yEtlEx0WgVINsFiWAUxDOBzgHBnKh
Fy6Q3RAXGdxUAEWI6IgSvXzorDq39AsE45Jh4PgpBTeyLNKZH+aBa2eASZkTcT9wvZwHKMz+ESnd
41myQlGYGh8qx3xKuTBWDHAW+G6EhOwElCWBvrzIdgGY+aPkTLlS1LRLZgnySOqljstF6kQUJA5q
agy84InEzlzb90R64pKtFIOqyRb1bsgre+ZkBvCK/B0EgF3oi1JcpRztUQpwnGUAEHARmUcn5Lp6
aIW06NUD70074CmCdu77xIHHHdQ8VC8bBRD13UuFnVFtBmBwEh4fETRvrFwgKPuStOt6UQSA63oJ
YGqawNuRaXnkpBwIL3fhYHZyROEh5hAOGjXolye2g9hyYAAn9r1QRKEv/cjLAXxi5Z67bV5XO3St
5Q51oLSEYecWyTumDkd4wHNwg1DmwKKonYTmKAEjAwNnx34Wpr7yh34jO4nGuEcBqIpfTJ6jwhTB
rT3heRz1BLgSLZgPiIJkgAhEJUf3hdgLXMKFdzLd1r/wtl+gD5GtTnKJCv9chIngMvUzH40pZWx4
vQ3gjHjxIjQiaYqW7hjmHn5a22bfTl/+y73xr/s3c6q1/DNaLWoGJ/37/tbs7GAH1SXgDh/6Td12
9E7pr9AJL18Am/yM+01B9zxI5tG1rHhaSnS+fTugn89kgz6YpuFZV+f9i/2Nsxcv/7toaRU8om0w
rHavSGe8Wq1GblYrvf9CLxnxg/YZ3lzfvH/z9tULreSuUPmDXnu9r9sy+8vA22wi1uTmVDB4xTw6
Fuz5hpe84Udi2XP7fynWW5l1fV3J50UrBtS2g3SGvuOtVgempr9/S8ZN3zfdcrFYF/1mSOcoLYs9
zcWEDFRxveFZffcMfc3zjeT9RB+nT6ZK8ebh3DtWygvefnzPb3+fUg46MORWq+tnz9U/B5mvb569
vXl39cCqEuFD/VnZ3VxN5Di6fWxZV+0zHYT4SrxPV1ytTtb/Ted8hQB+vbvuB6rjeymmd0/d0z62
xOt6w9eY1dFL5a8k0nakuVpRE7XddcSJ3tH8Am+csriYigb5/9Ly9M98PZF9vDOVG53OqQfyshjK
3e+Myh9QYW5aXnU5UslBfk17tVqDlZSvv1zwoWjzQpbZYhQKEh+fb5hslJ6ce5hm2/DU6tui/Gj7
qhF7q1+ZXL1+ffW17P8vvjv8fJA+oo8Jq8cvu0a9XMl2253oRN87joIH3hD6P/xg2+zf2FVbE7j6
qcqLitD1V9LIB72All9xNPn5BZ6h5k5e+2k6qhrTsRQJHK3kmj+yDQ/allXV1l3xi64OlpUVHclk
wZMLElFv/c/N+RG1b3z25Gp/xZ7X0M+aUWe8alfVk/cyY29EzyJmh0snWtqHrWx6rslZRXNhz9V/
dFOr0frHINvdBalyMpI6gQsHmNOlm1t+bzXqLXt34frqTt1nF3+hlMB4lTGVDf7QsTd5XgjkTqZf
wNDIuw10aJVF11/USEG4w6uqHioAVE3S4mJTSH2iqLuoK8UFvSC06K2B3g66cEK6TTloi2bgQvGf
14Ry9/cMdeg3o8318bq5bQxRarUKMZT97sJT1NSrDsB3q5N9X1Tr7oJuq/efFvnvxR3V3sM9gMds
MoSA6MWLlz88e/fqZqLPFih+XJx+zxsARVDKLv6o/gcFDH1tdfxWGsZuC3lHHtBzaOUiplv3aX1v
UXiYISWv1gNfywtZren6CETOd1vaK33CKMsxoVxj0NBfeQiDptiRG8Jj2A2hYTaKzngrGQAyA8Tp
8IP3TJChepZKVlSiHDK4GMg/8EyidV1vMTNn/UOaHc/ljNV40nZEkqWt5B/ZDj2KocWKnMGCBRIt
rQDj0YkypG8Q/k95tye3yGTOYb6O3dXVH3rGm0bylpE2txCW3jTsiEM6WqXlvtvIig0NqkAGAvNV
Rf6tiS1XFWNP3m8kMcb6mtGBFgYS5mUedEBlhXZ3Mv1YsYpqykEY+ixlr/SVISUKyTbqHTPd2RJl
7Zuj1ZZMvQejB91m6IHTKssc/KOTYTpYmCjrTmarM8XZs7Ks7xiFDR1/Mwif3Rac/RfFK41RgWuZ
R0umIpimvlR+aOao8KR4oLNoUApRS3fMqJLGG7fdP54w++Q9Oi54BPTKs4yhs9TqJ7XSO162lbxD
8qPQZVB6KolpKEf+Y0ASgNrWxS3GqoNz7Nwsiqz0lKjrFWlvlrKNBbXTq9YlHqu1/3PYptAKvOpZ
t6sEvWBndB4NfjRXA95BW8q1R0lp2KatkV1gPQzvZkxFMDORrs680MYNBKFKpHSDLE/3tkMFD6Ih
mvi1Mi9kgpe19X0BD5NQA0RSnlvtmSPdGoZ+yslXaQz55IwV/R+gvr5V0zJJuUy5zMlkdg4ZBsSN
q9SixLCMpEtF6tRXuXKOdqgqMmdG2ahW58OYegnbzdkLeWt+s22x3iCYW95tZtPgM45DGmnboen1
Xa0wUswWvBm5lHERlOpNZaYDgtNBSrD9OAfkI+RzNRQN75pPHA2DLT1o72moJ8jh7U4H5V/UDhKj
Ss70fcTBtugptrdyzdNdD42za61qWylXl081/YasdlcozSuPQtDeWZrQ6GS6auUFWERGAveVopUD
KI1LaieHtQYKU7auYSjaz1ZeQQuZjS7F2pLZJAVWVylYvxL8fy8BQaPP8U+l9Pfxj465USyY9Lln
yZDrGNIH1UfkvZEhWnXkyrEBNzRjKgm8V1Fh+Ov+8BU4VHGhWKKMwcSA4lOh+DB5L8Wgkm+tWdYR
ScVqP1reC0CC7iCRTlxvbl4u2c2PP12zVz+9/umGPbu6evXTy2t29fItA7j8j5dvZwyD2M0bjHrJ
3v/45tVLdvX2zfOX19fz0xRwpA83CI06gDeLWhVkSsQdCSg2UqVkpY19snWge0CCTOUWNcRCKpQ6
zSpSwJKQEwka3kTyfsrZtJMBz1EBrGiYWUxR1kSQeg+JXFcktcYbqiFU59WE+cPR5AsG18NsjRQE
B7RmiV1tVz13LwPcSzbdQVTPNrJ2Tx9nyUjuGcnXvE3p1ISoS/PaUSWgx7WrQo3YMbOYmYXcveXV
oMDHlBMAswE++HQ21oRTJxzdUJfXPActLe/2EIJz9kbnfO3wQA/1UGZ7XgoUkbuKHfjvNOFGsQ9B
Q9s2smK1H1SyeFAkletoCnvZ8rbejsVWzzYjrKlrTi1M0hhLPvAN9ohLHXnH9QgYyWQtViI3NI6c
DdtGoysN4Zh5YNGD0V4vaJCZoHhXbI4S4AplHsHOH1EwijYKH1a4hZN13SApMfQbWG09ok1KWrTa
gavZaEiNEQyonGtuaOgn9UStlKCzl93I+3Pe0N1iO2xRY1FeWzb2AmRIprskzcVBrxQvRpUqYh76
GMB2YzhSC1qEggcUXX9vsRe1fnTq04SNKOtp+nrwGEKalhk4lUwhB0ugm5N72V6AFYVVAB9Je+BO
AwxNpVFnx5meoyU8SIdpRp+mNzYr0+AD2iUFltQGGLqfJ/U5P1xV5oOHpSkRgGabutQQM+U9ulRC
4orljg4OM1NkVG7TnY95qktLKvdgU5e3J1MrjY8orba7nojPmOVMDKiMpxa2+pEZUwJU1j7gWNWP
EoTMtOTUyyigT5PpMxTN1pz9CCwIX7pQ4I49v3o3w1zwkCK+7ooMbq+wgs6ee/qWor9k0Qi7D4i8
U9qZjJ2zZxkS1YaX+QKtpG4TMgkfNkthUUabLeRgk0A8lL0JsWkr8vKeshpBTF7OdNKkpd8XFdop
iHbTqnpRKyT97qq6GnH4oTekNoMm3dH+PGgOTdVY5vqk8XltArIrfpF7UxNiHy1Mm8QjmgKi154z
qbp+4upJT+fsyswpebtWE7hpUo2bqBXzlq9JOpgLYnVNqcAMdZ5bME95gLdkwudlQRslqpWms6Cy
69nrm3eK0w4ikdjp0DNq3ZWVD8vpvmM+pqFtP1g0a6m4pQDIZDqsl2Mv8z1zqIcxSG6DKFbPmelc
O91rk5NXXa1rmnEUh4jpvKWpPd/U6G3JOccWRo5NqkpuGe856/jtmERpc2TcHqJnh3inI13IBJL3
Y44Bp/qU6QiZVbvVtBqudA0QmoIvVS3KomFqLvT4mu+gQ3KWbX07drCU/k3OVHnLGp/pJbtDthh3
hKa7CTdqO0A7gD5nrzdS1Fhj7aEz2xL6OyTlh2aOpecsWQNAcVuUtIzOeSaezSqUtHm13oPqiqaV
p7VjNo462l16dAdHd3nPtvVAPp3r5GxcnFSpd/5UMaJwVr07DEO/VTXB5LeqtkwmK8ErqXvFVGpi
qczJI9XunioHm9EDlNHVpt9RldLi00J78RGZjJ+y2ujD5lhNogA8xqX9OJu8BSX4x+iIYHacTH/3
3HjKu6mTtgb1DVY3yRaCCpBaSO1zTrZifnqhFlMn2ToVkqRP2ZKlgWuRurbMSMfMzsNY7dScI9FB
z2Iue8LW6Fm6g3oOuxt7Dc0fqsgE6x0vVFODxAHEr23T1M1Qjs5oLijtqzEmRXgqQSg0bDUmrCm7
UqQu2Ygz1c6m3s9ZmopH20+qx9K3dcEw9qJvyvYbA9lBb+Tv6tTHya19uB3fbjaAZnk9sQiizNKb
9vuR9MXOUrMyp/ci86JWHFd1tdtSj0AnVmi7TXQH1qnxMc/Z4bkSQaUsvl636Db1zpLZhtLdNn2q
+fFUPsUfIvjNizd0kN8ySVDXAkoKd1IDUa6+KKUVO8X4QQB1bz7Z+0Xp2Wteu6Y2zgOlwqD6uXEm
VD114oRy9xRPqfv1VHWAqBX5yWSbZ4b82Gz4DLehBipY/R6yIPXmEm00TIgMVFFB0E/HwqI3jfjR
tpF5OTQpOAPgGWqbymJjsjAEleX183GNB5bWsk5N3aOH3udqU5GIKI0fgQNZlhImLaj2w8ykce9z
fljAPJmuMGrz8zXPpG1tXR0Vk20GQwPke6PPcUNhY26qjEEdgQGZJmPQ/ixwfKZQVpHvCQGqQxC9
GU8ZaOyydY4DPZMix8rGy4J3BsIDdXE652auCASAR2Or5Wg0/Qx+S9s9S/Y3Vb1RP2dq/+dnIqrQ
+aFMTl8SKDEISbVFZjrs8cWMap0fq1iqoKsK3SkwqToz2KcAr6bcTtnX6yoe9E9Gr3KoKujqdVhx
yX549exm6f4pmgXJvTPz7r2Z+yfnT5kUtc6x530rcYHkehHbOhXrKz94qmGP3o+fNrY6wqm2QMdm
30lBD7VxBKuJHdNfKQ3tmJRHNN/ud/JVxgEdlCqh3pR0o8Ks8S0AfEHjuyc/qFSjllLjj4gMCimY
D/ondywFtuaHLbK6Ub2gvEfi60wjJD4SXu4U6IdG0gJIdad7ZjWO5FWH70tdRnTMaCkVfYCRdp+r
z2Zn8r6Xlfls5Z9nz4EQph/cZPoc4f66LNJ79bprfwdOUXXd0a1GHBPp/gEmpXf0IY/+0GF/nQrz
Ccb+Dr3pqTLeHt1rd01fq1f6njpANR5HO4wY2iNWUOLp/INte47j0uEv+uhHvQOP1JmAvCj1mcv9
jLw/+uJonR1dbY8eblDOjgQFysvUQanDveurV0cKpPDI0skhsG2q33lNR2130Jn61Mn8Yuokp0vb
9wwwxHYC27cj/PzuJ0RSJAT+n4QyjII8zCJXBiK3czeMcj+WThgJ+uzF9dh3yjpVf6SjqxdvjqyX
1R/Uqqc3tRmPZm6O7XMojB8U7pl+w6TO8tddcX804fD5jkfqoK/WZmf7I5lrfepsP//t/guFI61v
tvWRWa4LSjt/fX2k+E7x1h05R2cONpFjFGv93ZU5mq5OLE5OKu4nnbg/LkmCB2Pu2uLEsXZczXSN
LL8UjT6RFKi1lMaLw/hff/0fg6Y3xQ==
===END CRASH DUMP===

Not quite sure, was AFK and it crashed :(

**Comment by 95CivicSi** [comment]
You're very out of date.  Please update to the latest version and report back if the issue continues to happen.

https://github.com/RevivalPMMP/PureEntitiesX/releases/tag/0.6.9
