### ISSUE TITLE
Entities walk through solid blocks

### ISSUE THREAD

**Issue by tjespe** [RevivalPMMP/PureEntitiesX#44]
Lag allows entities to occasionally walk through completely solid blocks. This makes farming impossible, because there is no way to trap entities. Even though you build a roof an four walls around them, they will still escape eventually. I don't think it was like this before the temporary wall climb solution was implemented, so this issue might resolve itself when we get a working solution for climbing blocks.

**Comment by erickwoc** [comment]
the same as you

**Comment by kniffo80** [comment]
Is this still valid?

**Comment by kniffo80** [comment]
As there's no feedback and i never saw this - closed!
