### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dmartin015** [RevivalPMMP/PureEntitiesX#444]
PocketMine-MP Version: 3.17.2
Plugin Version: 0.6.7
Other Installed Plugins: none

PHP version: Latest one

OS Version: Windows 10

1.  Start The Server

19:21:59 Server|INFO > Loading PureEntitiesX v0.6.7
19:21:59 Server|CRITICAL > Error: "Class 'pocketmine\entity\Squid' not found" (EXCEPTION) in "plugins/PureEntitiesX (2).phar/src/revivalpmmp/pureentities/entity/animal/swimming/Squid" at line 26
19:21:59 Server|CRITICAL > #0 vendor/pocketmine/classloader/src/BaseClassLoader(138): include()
19:21:59 Server|CRITICAL > #1 vendor/pocketmine/classloader/src/BaseClassLoader(124): BaseClassLoader->loadClass(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
19:21:59 Server|CRITICAL > #2 (): BaseClassLoader->{closure}(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
19:21:59 Server|CRITICAL > #3 (): spl_autoload_call(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
19:21:59 Server|CRITICAL > #4 src/pocketmine/entity/Entity(466): ReflectionClass->__construct(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
19:21:59 Server|CRITICAL > #5 plugins/PureEntitiesX (2).phar/src/revivalpmmp/pureentities/PureEntities(194): pocketmine\entity\Entity::registerEntity(string[53] revivalpmmp\pureentities\entity\animal\swimming\Squid)
19:21:59 Server|CRITICAL > #6 src/pocketmine/plugin/PluginManager(182): revivalpmmp\pureentities\PureEntities->onLoad()
19:21:59 Server|CRITICAL > #7 src/pocketmine/plugin/PluginManager(346): pocketmine\plugin\PluginManager->loadPlugin(string[46] /home/container/plugins/PureEntitiesX (2).phar, array[3])
19:21:59 Server|CRITICAL > #8 src/pocketmine/Server(1608): pocketmine\plugin\PluginManager->loadPlugins(string[24] /home/container/plugins/)
19:21:59 Server|CRITICAL > #9 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/container/, string[24] /home/container/plugins/)
19:21:59 Server|CRITICAL > #10 src/pocketmine/PocketMine(304): pocketmine\server()
19:21:59 Server|CRITICAL > #11 (11): require(string[63] phar:///home/container/Pocketmine.phar/src/pocketmine/PocketMine.php)
19:21:59 Server|CRITICAL > Could not load plugin 'PureEntitiesX'

**Comment by 95CivicSi** [comment]
I am unable to recreate this error.  Make sure you are using Pocketmine-MP and not a variant such as Altay
