### ISSUE TITLE
Make entities more careful

### ISSUE THREAD

**Issue by tjespe** [RevivalPMMP/PureEntitiesX#45]
Currently, entities walk off cliffs killing themselves without thinking twice.

**Comment by Sandertv** [comment]
Yeah. This will be hard one though.

**Comment by Magicode1** [comment]
We will have to have them check for air block under/in front of them. Caves may make this difficult though.

**Comment by xZeroMCPE** [comment]
Stupid MobAI's!

**Comment by archie426** [comment]
@Magicode1 Unless we make it so if there is only 1 or 2 blocks below them

**Comment by jasonwynn10** [comment]
we can add a check that when the entity sets a target to move to, anywhere in the path of movement, if there are 4 air spaces under them the mom won't move in the first place

**Comment by Magicode1** [comment]
I like that idea.

**Comment by jasonwynn10** [comment]
Passing to https://github.com/poggit-orphanage/PureEntitiesX
