### ISSUE TITLE
Colored Sheep , Drop Colored Wool? Breeding animals and baby ?

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#47]
You can implement this?

**Comment by caspervanneck** [comment]
idk @NycuRO

**Comment by Skull3x** [comment]
@NycuRO Yes we can 👍 . But the breeding animals may take time :)

**Comment by NycuRO** [comment]
https://github.com/RevivalPMMP/PureEntitiesX/issues/61
