### ISSUE TITLE
AutoSpawnTask

### ISSUE THREAD

**Issue by Magicode1** [RevivalPMMP/PureEntitiesX#5]
This task, which auto spawns mobs (Like Vanilla Minecraft), has another `//ToDo` under it. It is a huge part of the plugin, so we need to implement it

**Comment by Sandertv** [comment]
Yep. I'll take care of it soon :)

**Comment by Magicode1** [comment]
Sweet, thanks

**Comment by Sandertv** [comment]
This is all finished, time to close this!

**Comment by Sandertv** [comment]
This is all finished, time to close it!
