### ISSUE TITLE
Chickens don't 'float' down to the ground when falling

### ISSUE THREAD

**Issue by Rover656** [RevivalPMMP/PureEntitiesX#50]
Hi, Great Job with this, it really has potential
Just thought it would be worth mentioning that chickens don't 'float' to the ground when they're falling,
but great job, looking forward to a new release!

**Comment by Sandertv** [comment]
Thanks for reporting, we'll try to implement this as soon as possible!

**Comment by Rover656** [comment]
@Sandertv you are very welcome!

**Comment by Rover656** [comment]
@Sandertv i'd like to compile the master... how would one create the phar file???

**Comment by Sandertv** [comment]
A possible way is download it from the poggit button for an automatic compile phar, or
Download the zip and use pmt.mcpe.me to compile it, or
Download the zip and make it a phar using devtools.

**Comment by kniffo80** [comment]
Maybe this has to do with gravity settings. Will check soon ...

**Comment by kniffo80** [comment]
Fixed with https://github.com/RevivalPMMP/PureEntitiesX/commit/5b3e21bc4ad4a888542dc583f2689fd02749e3a6
