### ISSUE TITLE
When you are luring chickens

### ISSUE THREAD

**Issue by Rover656** [RevivalPMMP/PureEntitiesX#51]
When you are luring (I just found it about chickens) they don't leave you alone afterwards. They continue to follow you.
Just another bug, great job tho!

**Comment by Sandertv** [comment]
Yeah I've noticed this, it's really annoying. I'll try to fix this soon.

**Comment by Rover656** [comment]
@Sandertv Thank you

**Comment by Skull3x** [comment]
@Sandertv While we are at it, should we add breeding functions? 👍

**Comment by Sandertv** [comment]
Yeah. We'll have to use the buttons like shearing sheeps.

**Comment by Skull3x** [comment]
@Sandertv If we use those, do you have any idea how we can detect an interaction with that button "onPress"? Packets??

**Comment by XShockinFireX** [comment]
@Skull3x It is possible with InteractPacket, the action is right-click

**Comment by Sandertv** [comment]
You can look at the code I used for shearing sheep.

**Comment by kniffo80** [comment]
It's already fixed on 1.0.0-bug-fixes. Can be closed as soon as the https://github.com/RevivalPMMP/PureEntitiesX/pull/112 is merged!

**Comment by archie426** [comment]
@kniffo80 And as soon as I figure out how to work these conflicts

**Comment by kniffo80** [comment]
@archie426 you want to merge into master? You need help?

**Comment by jasonwynn10** [comment]
@archie426 @kniffo80 I think that we shouldn't try merging into the master until PocketMine's API 3 is completed

**Comment by archie426** [comment]
@kniffo80 No, I was just pre-thinking about how to do it..... It is quite complicated, but yeah, have a go if you want to of course

**Comment by jasonwynn10** [comment]
@archie426 I think my code cleanup may help with that

**Comment by archie426** [comment]
@jasonwynn10 Yeah it should

**Comment by kniffo80** [comment]
This can be closed - it's fixed on MASTER.
