### ISSUE TITLE
Special Mobs and Xp Drop on Mobs ?

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#55]
You can implement "Special Mobs"

![image](https://cloud.githubusercontent.com/assets/13573011/21314807/a8a0f980-c601-11e6-848c-25288d2b564e.png)

And XP Drop from Mobs? Thanks!

**Comment by Magicode1** [comment]
We can't make mobs drop XP until Pocketmine Implements XP (Maybe we could implement XP, but I will have to talk with @Sandertv) 

But, we can see about implementing special mobs 😄

**Comment by caspervanneck** [comment]
No XP  its for pmmp not genisys or other forks

**Comment by NycuRO** [comment]
@caspervanneck XP = PureEntitiesX ?

**Comment by jasonwynn10** [comment]
what do you mean by 'special' specifically? Do you just mean mobs riding on other mobs or something more?

**Comment by NycuRO** [comment]
https://github.com/RevivalPMMP/PureEntitiesX/issues/61
