### ISSUE TITLE
All type of Ocelot and Feature Creeper and Ocelot

### ISSUE THREAD

**Issue by NycuRO** [RevivalPMMP/PureEntitiesX#56]
1. You can add all type of Ocelot?

2. Feature Creeper:

" Creepers will actively avoid ocelots and cats. However, this will not deter them from chasing a player, only keeping the creeper a distance away. " 
Creeper fleets from Ocelot.

3. Ocelot sit on Bed.

WIKI : http://minecraft.gamepedia.com/Ocelot

**Comment by jasonwynn10** [comment]
I thought ocelots sit on chests...?

**Comment by Sandertv** [comment]
This is some really advanced stuff, which is not really smart to prioritize currently.

**Comment by NycuRO** [comment]
https://github.com/RevivalPMMP/PureEntitiesX/issues/61

**Comment by Sandertv** [comment]
It's in fact easier to have them in sepparated issues. We can keep track of them that way easier.

**Comment by NycuRO** [comment]
@Sandertv Open or close issue ?

**Comment by Sandertv** [comment]
Just leave them closed for now I guess.
