### ISSUE TITLE
Creeper don't explode and of that don't burst blocks

### ISSUE THREAD

**Issue by kniffo80** [RevivalPMMP/PureEntitiesX#66]
This is just a simple question. I've found the following line in the creeper entity class:

`$ev->setBlockBreaking(false); // This should be removed later. There should be a configurable option for this.`

Can anybody tell me, why? I assume because of performance?

Does this project has a gitter room?

**Comment by caspervanneck** [comment]
yes
it has a giter room

and no its for poeples spawn hubs

**Comment by caspervanneck** [comment]
@kniffo80

**Comment by Sandertv** [comment]
There is a gitter button in the README. For the creeper exploding. I've set that block breaking to false for the automatic mob spawning. Until there is configurable block breaking I'm leaving it that way to save people's lobbies.

**Comment by kniffo80** [comment]
Thanks @Sandertv and @caspervanneck - this can be closed then. Found the gitter room. Thanks.

**Comment by Sandertv** [comment]
Alright, no problem.
