### ISSUE TITLE
Animals randomly teleporting miles away when using spawn eggs

### ISSUE THREAD

**Issue by Sandertv** [RevivalPMMP/PureEntitiesX#7]
When using a spawn egg with an animal type, the animal teleports about 50 blocks away from the location where it got placed. This does not happen with monsters.

**Comment by Magicode1** [comment]
That's weird. I have never seen this

**Comment by Sandertv** [comment]
Could you try to reproduce this too? Just click the ground with an animal spawn egg a couple times.

**Comment by Magicode1** [comment]
Just did. Nothing happened. They all spawned as normal and started walking around

**Comment by Sandertv** [comment]
Hm! Guess it just fixed itself then 😆

**Comment by Magicode1** [comment]
That's good!
