### ISSUE TITLE
API v3.0 not supported

### ISSUE THREAD

**Issue by srcr** [RevivalPMMP/PureEntitiesX#71]
A bit of an open door IMHO, but the new minecraft clients need PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA1) which uses API 3.0 this is not supported yet by PureEntitiesX.

**Comment by Magicode1** [comment]
If you compile it from the 1.0 bug fixes branch, it should work.

**Comment by srcr** [comment]
Indeed that branch works.. I only tried the master.. thanks for the quick response.

**Comment by Magicode1** [comment]
No problem! Glad it worked for you!
