### ISSUE TITLE
Mob interactivity bug

### ISSUE THREAD

**Issue by archie426** [RevivalPMMP/PureEntitiesX#75]
- [x] This issue isn't duplicated - you can check if it is by using the search bar located at the top left hand corner and select "Issues" on the left.
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.

## Issue description
Every time an Entity spawns or I hit it (Not including burning) an error message shows up on console.

## Reproducing the issue
1. Start Server
2. wait for entities to spawn
3. hit entity

## Client information
PocketMine-MP Version: 1.0
Plugin Version: (insert commit label here)
PHP version: 7.0.13

## Optional information
```
This could be to-do with the API bump I did, but it doesn't seem likley. Here is the error message: Could not tick level 'World': Value 5 exceeds the range. InvalidArgumentException "Value five exceeds the range"
![image](https://cloud.githubusercontent.com/assets/13406648/21608283/78f2c7d2-d1b3-11e6-8924-60ccc7baa5e6.png)
```

**Comment by Magicode1** [comment]
We (Or I have) seen this before on my machine. 

Mobs can sometimes lag when there are too much of them, even in Vanilla Minecraft. When there are a lot of Mobs, and the server lags, it throws an error, because it is PureEntities that is causing the lag. That is what I have seen at least.

**Comment by archie426** [comment]
Yeah, makes sense, I killed all the mobs. Maybe it would be god to add a feature that when no one is online, no mobs spawn, because that is why there were so many

**Comment by Sandertv** [comment]
In fact no monsters spawn when you're offline...

**Comment by archie426** [comment]
@Sandertv How come there was so many, I didn't spawn them in

**Comment by jasonwynn10** [comment]
I've been working on a safety catch in an attempt to stop this error from happening

**Comment by Magicode1** [comment]
@jasonwynn10 Thanks, that should solve it.

**Comment by archie426** [comment]
Good will close

**Comment by jasonwynn10** [comment]
was the fix tested?

**Comment by archie426** [comment]
@jasonwynn10 Oops, my bad

**Comment by archie426** [comment]
Works (I think), closing
