### ISSUE TITLE
1.0.0 branch its not updated with master

### ISSUE THREAD

**Issue by caspervanneck** [RevivalPMMP/PureEntitiesX#79]
i need help and it needs to be update  from master branch i restart tomorow

**Comment by jasonwynn10** [comment]
WHY DID YOU DELETE THE 1.0.0 BRANCH?!

**Comment by Sandertv** [comment]
I got it saved locally, it's not gone.

**Comment by jasonwynn10** [comment]
was it the latest version?

**Comment by Sandertv** [comment]
I'm quite sure it is. I'll push it shortly when I'm at my laptop.

**Comment by Sandertv** [comment]
I re-added the branch. I'm not entirely sure if it's everything, but it should be most of what's done.

**Comment by caspervanneck** [comment]
@Sandertv  @jasonwynn10 its not updated with master

**Comment by jasonwynn10** [comment]
the 1.0.0 Branch is for 1.0.0, the master branch of for compatibility with 0.16. We will only merge the 1.0.0 into the master when dktapps finishes releasing the new API
