### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by caspervanneck** [RevivalPMMP/PureEntitiesX#81]
Warning: file_put_contents(C:\Users\Wesle\Desktop\s server\plugins\PureEntitiesX/config.yml): failed to open stream: No such file or directory in C:\Users\Wesle\Desktop\s server\src\pocketmine\utils\Config.php on line 208 

@Sandertv @jasonwynn10

**Comment by jasonwynn10** [comment]
I think someone used an incorrect slash in the config...
