### ISSUE TITLE
What's wrong？

### ISSUE THREAD

**Issue by xinghao2003** [RevivalPMMP/PureEntitiesX#89]
Warning: Declaration of revivalpmmp\pureentities\entity\BaseEntity::entityBaseTick($tickDiff = 1) should be compatible with pocketmine\entity\Living::entityBaseTick($tickDiff = 1, $EnchantL = 0) in C:\Users\UserX\Desktop\PM-MP\plugins\PureEntitiesX-1.0.0-bug-fixes\src\revivalpmmp\pureentities\entity\BaseEntity.php on line 0

**Comment by Sandertv** [comment]
I'll fix this, it's nothing critical but I've noticed it too.

**Comment by xinghao2003** [comment]
ok, thank

**Comment by Sandertv** [comment]
Fixed! Tell me if you still experience it.
