### ISSUE TITLE
Entities never stop walking

### ISSUE THREAD

**Issue by Sandertv** [RevivalPMMP/PureEntitiesX#9]
Spawned entities never stop walking. They tend to walk in one direction until they hit a block they can't walk past or find a target/get hit.

**Comment by Magicode1** [comment]
Yeah. And they eventually just walk away and never come back. We should also add a detection for drops so that they don't walk off cliffs and die :)

**Comment by Sandertv** [comment]
Yep! Too right!

**Comment by Magicode1** [comment]
I saw a cow and some other animals stop walking in the desert and I was like yaaaaaay.
